
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-04T20:27:10-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "24bf7205c1c3775fcdd69bf7554dd844057549a6",
 "version": "3.7.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
