[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tcoi"
version = "0.1.3"
authors = [
  { name="Husayn al-Qurashi", email="husayn@dnmx.org" },
]
description = "A New Form of Decentralised Hashing."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Topic :: Utilities",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/qurashiakh/tcoi"
"Bug Tracker" = "https://github.com/qurashiakh/tcoi/issues"
