name: linters

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  linters:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        id: setup
        with:
          python-version: ${{ vars.PY_VER_BUILD_TEST || '3.10' }}
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            .pre-commit-config.yaml

      - name: cache tox
        id: cache-tox
        uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ hashFiles('**/tox.ini') }}

      - name: cache pre-commit
        id: cache-pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}

      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox < 4"

      - name: linters
        run: tox -e linters

      - name: show diffs if failed
        if: failure()
        run: git diff
