name: mypy

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "tox.ini"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "tox.ini"
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        id: setup
        with:
          python-version: ${{ vars.PY_VER_BUILD_TEST || '3.10' }}
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml

      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox < 4"

      - name: mypy
        run: tox -e mypy
