def import_test():
    from schemaorg_types._3DModel import _3DModel
    from schemaorg_types.Abdomen import Abdomen
    from schemaorg_types.AboutPage import AboutPage
    from schemaorg_types.AcceptAction import AcceptAction
    from schemaorg_types.Accommodation import Accommodation
    from schemaorg_types.AccountingService import AccountingService
    from schemaorg_types.AchieveAction import AchieveAction
    from schemaorg_types.Action import Action
    from schemaorg_types.ActionAccessSpecification import ActionAccessSpecification
    from schemaorg_types.ActionStatusType import ActionStatusType
    from schemaorg_types.ActivateAction import ActivateAction
    from schemaorg_types.ActivationFee import ActivationFee
    from schemaorg_types.ActiveActionStatus import ActiveActionStatus
    from schemaorg_types.ActiveNotRecruiting import ActiveNotRecruiting
    from schemaorg_types.AddAction import AddAction
    from schemaorg_types.AdministrativeArea import AdministrativeArea
    from schemaorg_types.AdultEntertainment import AdultEntertainment
    from schemaorg_types.AdultOrientedEnumeration import AdultOrientedEnumeration
    from schemaorg_types.AdvertiserContentArticle import AdvertiserContentArticle
    from schemaorg_types.AerobicActivity import AerobicActivity
    from schemaorg_types.AggregateOffer import AggregateOffer
    from schemaorg_types.AggregateRating import AggregateRating
    from schemaorg_types.AgreeAction import AgreeAction
    from schemaorg_types.Airline import Airline
    from schemaorg_types.Airport import Airport
    from schemaorg_types.AlbumRelease import AlbumRelease
    from schemaorg_types.AlcoholConsideration import AlcoholConsideration
    from schemaorg_types.AlignmentObject import AlignmentObject
    from schemaorg_types.AllergiesHealthAspect import AllergiesHealthAspect
    from schemaorg_types.AllocateAction import AllocateAction
    from schemaorg_types.AllWheelDriveConfiguration import AllWheelDriveConfiguration
    from schemaorg_types.AmpStory import AmpStory
    from schemaorg_types.AMRadioChannel import AMRadioChannel
    from schemaorg_types.AmusementPark import AmusementPark
    from schemaorg_types.AnaerobicActivity import AnaerobicActivity
    from schemaorg_types.AnalysisNewsArticle import AnalysisNewsArticle
    from schemaorg_types.AnatomicalStructure import AnatomicalStructure
    from schemaorg_types.AnatomicalSystem import AnatomicalSystem
    from schemaorg_types.AndroidPlatform import AndroidPlatform
    from schemaorg_types.Anesthesia import Anesthesia
    from schemaorg_types.AnimalShelter import AnimalShelter
    from schemaorg_types.Answer import Answer
    from schemaorg_types.Apartment import Apartment
    from schemaorg_types.ApartmentComplex import ApartmentComplex
    from schemaorg_types.APIReference import APIReference
    from schemaorg_types.Appearance import Appearance
    from schemaorg_types.AppendAction import AppendAction
    from schemaorg_types.ApplyAction import ApplyAction
    from schemaorg_types.ApprovedIndication import ApprovedIndication
    from schemaorg_types.Aquarium import Aquarium
    from schemaorg_types.ArchiveComponent import ArchiveComponent
    from schemaorg_types.ArchiveOrganization import ArchiveOrganization
    from schemaorg_types.ArriveAction import ArriveAction
    from schemaorg_types.Artery import Artery
    from schemaorg_types.ArtGallery import ArtGallery
    from schemaorg_types.Article import Article
    from schemaorg_types.AskAction import AskAction
    from schemaorg_types.AskPublicNewsArticle import AskPublicNewsArticle
    from schemaorg_types.AssessAction import AssessAction
    from schemaorg_types.AssignAction import AssignAction
    from schemaorg_types.Atlas import Atlas
    from schemaorg_types.Attorney import Attorney
    from schemaorg_types.Audience import Audience
    from schemaorg_types.Audiobook import Audiobook
    from schemaorg_types.AudiobookFormat import AudiobookFormat
    from schemaorg_types.AudioObject import AudioObject
    from schemaorg_types.AudioObjectSnapshot import AudioObjectSnapshot
    from schemaorg_types.AuthoritativeLegalValue import AuthoritativeLegalValue
    from schemaorg_types.AuthorizeAction import AuthorizeAction
    from schemaorg_types.AutoBodyShop import AutoBodyShop
    from schemaorg_types.AutoDealer import AutoDealer
    from schemaorg_types.AutomatedTeller import AutomatedTeller
    from schemaorg_types.AutomotiveBusiness import AutomotiveBusiness
    from schemaorg_types.AutoPartsStore import AutoPartsStore
    from schemaorg_types.AutoRental import AutoRental
    from schemaorg_types.AutoRepair import AutoRepair
    from schemaorg_types.AutoWash import AutoWash
    from schemaorg_types.Ayurvedic import Ayurvedic
    from schemaorg_types.BackgroundNewsArticle import BackgroundNewsArticle
    from schemaorg_types.BackOrder import BackOrder
    from schemaorg_types.Bacteria import Bacteria
    from schemaorg_types.Bakery import Bakery
    from schemaorg_types.Balance import Balance
    from schemaorg_types.BankAccount import BankAccount
    from schemaorg_types.BankOrCreditUnion import BankOrCreditUnion
    from schemaorg_types.Barcode import Barcode
    from schemaorg_types.BarOrPub import BarOrPub
    from schemaorg_types.BasicIncome import BasicIncome
    from schemaorg_types.Beach import Beach
    from schemaorg_types.BeautySalon import BeautySalon
    from schemaorg_types.BedAndBreakfast import BedAndBreakfast
    from schemaorg_types.BedDetails import BedDetails
    from schemaorg_types.BedType import BedType
    from schemaorg_types.BefriendAction import BefriendAction
    from schemaorg_types.BenefitsHealthAspect import BenefitsHealthAspect
    from schemaorg_types.BikeStore import BikeStore
    from schemaorg_types.BioChemEntity import BioChemEntity
    from schemaorg_types.Blog import Blog
    from schemaorg_types.BlogPosting import BlogPosting
    from schemaorg_types.BloodTest import BloodTest
    from schemaorg_types.BoardingPolicyType import BoardingPolicyType
    from schemaorg_types.BoatReservation import BoatReservation
    from schemaorg_types.BoatTerminal import BoatTerminal
    from schemaorg_types.BoatTrip import BoatTrip
    from schemaorg_types.BodyMeasurementArm import BodyMeasurementArm
    from schemaorg_types.BodyMeasurementBust import BodyMeasurementBust
    from schemaorg_types.BodyMeasurementChest import BodyMeasurementChest
    from schemaorg_types.BodyMeasurementFoot import BodyMeasurementFoot
    from schemaorg_types.BodyMeasurementHand import BodyMeasurementHand
    from schemaorg_types.BodyMeasurementHead import BodyMeasurementHead
    from schemaorg_types.BodyMeasurementHeight import BodyMeasurementHeight
    from schemaorg_types.BodyMeasurementHips import BodyMeasurementHips
    from schemaorg_types.BodyMeasurementInsideLeg import BodyMeasurementInsideLeg
    from schemaorg_types.BodyMeasurementNeck import BodyMeasurementNeck
    from schemaorg_types.BodyMeasurementTypeEnumeration import (
        BodyMeasurementTypeEnumeration,
    )
    from schemaorg_types.BodyMeasurementUnderbust import BodyMeasurementUnderbust
    from schemaorg_types.BodyMeasurementWaist import BodyMeasurementWaist
    from schemaorg_types.BodyMeasurementWeight import BodyMeasurementWeight
    from schemaorg_types.BodyOfWater import BodyOfWater
    from schemaorg_types.Bone import Bone
    from schemaorg_types.Book import Book
    from schemaorg_types.BookFormatType import BookFormatType
    from schemaorg_types.BookmarkAction import BookmarkAction
    from schemaorg_types.BookSeries import BookSeries
    from schemaorg_types.BookStore import BookStore
    from schemaorg_types.Boolean import Boolean
    from schemaorg_types.BorrowAction import BorrowAction
    from schemaorg_types.BowlingAlley import BowlingAlley
    from schemaorg_types.BrainStructure import BrainStructure
    from schemaorg_types.Brand import Brand
    from schemaorg_types.BreadcrumbList import BreadcrumbList
    from schemaorg_types.Brewery import Brewery
    from schemaorg_types.Bridge import Bridge
    from schemaorg_types.BroadcastChannel import BroadcastChannel
    from schemaorg_types.BroadcastEvent import BroadcastEvent
    from schemaorg_types.BroadcastFrequencySpecification import (
        BroadcastFrequencySpecification,
    )
    from schemaorg_types.BroadcastRelease import BroadcastRelease
    from schemaorg_types.BroadcastService import BroadcastService
    from schemaorg_types.BrokerageAccount import BrokerageAccount
    from schemaorg_types.BuddhistTemple import BuddhistTemple
    from schemaorg_types.BusinessAudience import BusinessAudience
    from schemaorg_types.BusinessEntityType import BusinessEntityType
    from schemaorg_types.BusinessEvent import BusinessEvent
    from schemaorg_types.BusinessFunction import BusinessFunction
    from schemaorg_types.BusinessSupport import BusinessSupport
    from schemaorg_types.BusOrCoach import BusOrCoach
    from schemaorg_types.BusReservation import BusReservation
    from schemaorg_types.BusStation import BusStation
    from schemaorg_types.BusStop import BusStop
    from schemaorg_types.BusTrip import BusTrip
    from schemaorg_types.BuyAction import BuyAction
    from schemaorg_types.CableOrSatelliteService import CableOrSatelliteService
    from schemaorg_types.CafeOrCoffeeShop import CafeOrCoffeeShop
    from schemaorg_types.Campground import Campground
    from schemaorg_types.CampingPitch import CampingPitch
    from schemaorg_types.Canal import Canal
    from schemaorg_types.CancelAction import CancelAction
    from schemaorg_types.Car import Car
    from schemaorg_types.Cardiovascular import Cardiovascular
    from schemaorg_types.CardiovascularExam import CardiovascularExam
    from schemaorg_types.CarUsageType import CarUsageType
    from schemaorg_types.CaseSeries import CaseSeries
    from schemaorg_types.Casino import Casino
    from schemaorg_types.CassetteFormat import CassetteFormat
    from schemaorg_types.CategoryCode import CategoryCode
    from schemaorg_types.CategoryCodeSet import CategoryCodeSet
    from schemaorg_types.CatholicChurch import CatholicChurch
    from schemaorg_types.CausesHealthAspect import CausesHealthAspect
    from schemaorg_types.CDCPMDRecord import CDCPMDRecord
    from schemaorg_types.CDFormat import CDFormat
    from schemaorg_types.Cemetery import Cemetery
    from schemaorg_types.Chapter import Chapter
    from schemaorg_types.CharitableIncorporatedOrganization import (
        CharitableIncorporatedOrganization,
    )
    from schemaorg_types.CheckAction import CheckAction
    from schemaorg_types.CheckInAction import CheckInAction
    from schemaorg_types.CheckOutAction import CheckOutAction
    from schemaorg_types.CheckoutPage import CheckoutPage
    from schemaorg_types.ChemicalSubstance import ChemicalSubstance
    from schemaorg_types.ChildCare import ChildCare
    from schemaorg_types.ChildrensEvent import ChildrensEvent
    from schemaorg_types.Chiropractic import Chiropractic
    from schemaorg_types.ChooseAction import ChooseAction
    from schemaorg_types.Church import Church
    from schemaorg_types.City import City
    from schemaorg_types.CityHall import CityHall
    from schemaorg_types.CivicStructure import CivicStructure
    from schemaorg_types.Claim import Claim
    from schemaorg_types.ClaimReview import ClaimReview
    from schemaorg_types.Class import Class
    from schemaorg_types.CleaningFee import CleaningFee
    from schemaorg_types.Clinician import Clinician
    from schemaorg_types.Clip import Clip
    from schemaorg_types.ClothingStore import ClothingStore
    from schemaorg_types.Code import Code
    from schemaorg_types.CohortStudy import CohortStudy
    from schemaorg_types.Collection import Collection
    from schemaorg_types.CollectionPage import CollectionPage
    from schemaorg_types.CollegeOrUniversity import CollegeOrUniversity
    from schemaorg_types.ComedyClub import ComedyClub
    from schemaorg_types.ComedyEvent import ComedyEvent
    from schemaorg_types.ComicCoverArt import ComicCoverArt
    from schemaorg_types.ComicIssue import ComicIssue
    from schemaorg_types.ComicSeries import ComicSeries
    from schemaorg_types.ComicStory import ComicStory
    from schemaorg_types.Comment import Comment
    from schemaorg_types.CommentAction import CommentAction
    from schemaorg_types.CommentPermission import CommentPermission
    from schemaorg_types.CommunicateAction import CommunicateAction
    from schemaorg_types.CommunityHealth import CommunityHealth
    from schemaorg_types.CompilationAlbum import CompilationAlbum
    from schemaorg_types.Completed import Completed
    from schemaorg_types.CompletedActionStatus import CompletedActionStatus
    from schemaorg_types.CompleteDataFeed import CompleteDataFeed
    from schemaorg_types.CompoundPriceSpecification import CompoundPriceSpecification
    from schemaorg_types.ComputerLanguage import ComputerLanguage
    from schemaorg_types.ComputerStore import ComputerStore
    from schemaorg_types.ConfirmAction import ConfirmAction
    from schemaorg_types.Consortium import Consortium
    from schemaorg_types.ConsumeAction import ConsumeAction
    from schemaorg_types.ContactPage import ContactPage
    from schemaorg_types.ContactPoint import ContactPoint
    from schemaorg_types.ContactPointOption import ContactPointOption
    from schemaorg_types.ContagiousnessHealthAspect import ContagiousnessHealthAspect
    from schemaorg_types.Continent import Continent
    from schemaorg_types.ControlAction import ControlAction
    from schemaorg_types.ConvenienceStore import ConvenienceStore
    from schemaorg_types.Conversation import Conversation
    from schemaorg_types.CookAction import CookAction
    from schemaorg_types.CoOp import CoOp
    from schemaorg_types.Corporation import Corporation
    from schemaorg_types.CorrectionComment import CorrectionComment
    from schemaorg_types.Country import Country
    from schemaorg_types.Course import Course
    from schemaorg_types.CourseInstance import CourseInstance
    from schemaorg_types.Courthouse import Courthouse
    from schemaorg_types.CoverArt import CoverArt
    from schemaorg_types.CovidTestingFacility import CovidTestingFacility
    from schemaorg_types.CreateAction import CreateAction
    from schemaorg_types.CreativeWork import CreativeWork
    from schemaorg_types.CreativeWorkSeason import CreativeWorkSeason
    from schemaorg_types.CreativeWorkSeries import CreativeWorkSeries
    from schemaorg_types.CreditCard import CreditCard
    from schemaorg_types.Crematorium import Crematorium
    from schemaorg_types.CriticReview import CriticReview
    from schemaorg_types.CrossSectional import CrossSectional
    from schemaorg_types.CssSelectorType import CssSelectorType
    from schemaorg_types.CT import CT
    from schemaorg_types.CurrencyConversionService import CurrencyConversionService
    from schemaorg_types.DamagedCondition import DamagedCondition
    from schemaorg_types.DanceEvent import DanceEvent
    from schemaorg_types.DanceGroup import DanceGroup
    from schemaorg_types.DangerousGoodConsideration import DangerousGoodConsideration
    from schemaorg_types.DataCatalog import DataCatalog
    from schemaorg_types.DataDownload import DataDownload
    from schemaorg_types.DataFeed import DataFeed
    from schemaorg_types.DataFeedItem import DataFeedItem
    from schemaorg_types.Dataset import Dataset
    from schemaorg_types.DataType import DataType
    from schemaorg_types.Date import Date
    from schemaorg_types.DatedMoneySpecification import DatedMoneySpecification
    from schemaorg_types.DateTime import DateTime
    from schemaorg_types.DayOfWeek import DayOfWeek
    from schemaorg_types.DaySpa import DaySpa
    from schemaorg_types.DDxElement import DDxElement
    from schemaorg_types.DeactivateAction import DeactivateAction
    from schemaorg_types.DecontextualizedContent import DecontextualizedContent
    from schemaorg_types.DefenceEstablishment import DefenceEstablishment
    from schemaorg_types.DefinedRegion import DefinedRegion
    from schemaorg_types.DefinedTerm import DefinedTerm
    from schemaorg_types.DefinedTermSet import DefinedTermSet
    from schemaorg_types.DefinitiveLegalValue import DefinitiveLegalValue
    from schemaorg_types.DeleteAction import DeleteAction
    from schemaorg_types.DeliveryChargeSpecification import DeliveryChargeSpecification
    from schemaorg_types.DeliveryEvent import DeliveryEvent
    from schemaorg_types.DeliveryMethod import DeliveryMethod
    from schemaorg_types.DeliveryTimeSettings import DeliveryTimeSettings
    from schemaorg_types.Demand import Demand
    from schemaorg_types.DemoAlbum import DemoAlbum
    from schemaorg_types.DemoGameAvailability import DemoGameAvailability
    from schemaorg_types.Dentist import Dentist
    from schemaorg_types.Dentistry import Dentistry
    from schemaorg_types.DepartAction import DepartAction
    from schemaorg_types.DepartmentStore import DepartmentStore
    from schemaorg_types.DepositAccount import DepositAccount
    from schemaorg_types.Dermatologic import Dermatologic
    from schemaorg_types.Dermatology import Dermatology
    from schemaorg_types.DesktopWebPlatform import DesktopWebPlatform
    from schemaorg_types.DiabeticDiet import DiabeticDiet
    from schemaorg_types.Diagnostic import Diagnostic
    from schemaorg_types.DiagnosticLab import DiagnosticLab
    from schemaorg_types.DiagnosticProcedure import DiagnosticProcedure
    from schemaorg_types.Diet import Diet
    from schemaorg_types.DietarySupplement import DietarySupplement
    from schemaorg_types.DietNutrition import DietNutrition
    from schemaorg_types.DigitalAudioTapeFormat import DigitalAudioTapeFormat
    from schemaorg_types.DigitalDocument import DigitalDocument
    from schemaorg_types.DigitalDocumentPermission import DigitalDocumentPermission
    from schemaorg_types.DigitalDocumentPermissionType import (
        DigitalDocumentPermissionType,
    )
    from schemaorg_types.DigitalFormat import DigitalFormat
    from schemaorg_types.DigitalPlatformEnumeration import DigitalPlatformEnumeration
    from schemaorg_types.DisabilitySupport import DisabilitySupport
    from schemaorg_types.DisagreeAction import DisagreeAction
    from schemaorg_types.Discontinued import Discontinued
    from schemaorg_types.DiscoverAction import DiscoverAction
    from schemaorg_types.DiscussionForumPosting import DiscussionForumPosting
    from schemaorg_types.DislikeAction import DislikeAction
    from schemaorg_types.Distance import Distance
    from schemaorg_types.DistanceFee import DistanceFee
    from schemaorg_types.Distillery import Distillery
    from schemaorg_types.DJMixAlbum import DJMixAlbum
    from schemaorg_types.DonateAction import DonateAction
    from schemaorg_types.DoseSchedule import DoseSchedule
    from schemaorg_types.DoubleBlindedTrial import DoubleBlindedTrial
    from schemaorg_types.DownloadAction import DownloadAction
    from schemaorg_types.Downpayment import Downpayment
    from schemaorg_types.DrawAction import DrawAction
    from schemaorg_types.Drawing import Drawing
    from schemaorg_types.DrinkAction import DrinkAction
    from schemaorg_types.DriveWheelConfigurationValue import (
        DriveWheelConfigurationValue,
    )
    from schemaorg_types.DrivingSchoolVehicleUsage import DrivingSchoolVehicleUsage
    from schemaorg_types.Drug import Drug
    from schemaorg_types.DrugClass import DrugClass
    from schemaorg_types.DrugCost import DrugCost
    from schemaorg_types.DrugCostCategory import DrugCostCategory
    from schemaorg_types.DrugLegalStatus import DrugLegalStatus
    from schemaorg_types.DrugPregnancyCategory import DrugPregnancyCategory
    from schemaorg_types.DrugPrescriptionStatus import DrugPrescriptionStatus
    from schemaorg_types.DrugStrength import DrugStrength
    from schemaorg_types.DryCleaningOrLaundry import DryCleaningOrLaundry
    from schemaorg_types.Duration import Duration
    from schemaorg_types.DVDFormat import DVDFormat
    from schemaorg_types.Ear import Ear
    from schemaorg_types.EatAction import EatAction
    from schemaorg_types.EBook import EBook
    from schemaorg_types.EditedOrCroppedContent import EditedOrCroppedContent
    from schemaorg_types.EducationalAudience import EducationalAudience
    from schemaorg_types.EducationalOccupationalCredential import (
        EducationalOccupationalCredential,
    )
    from schemaorg_types.EducationalOccupationalProgram import (
        EducationalOccupationalProgram,
    )
    from schemaorg_types.EducationalOrganization import EducationalOrganization
    from schemaorg_types.EducationEvent import EducationEvent
    from schemaorg_types.EffectivenessHealthAspect import EffectivenessHealthAspect
    from schemaorg_types.Electrician import Electrician
    from schemaorg_types.ElectronicsStore import ElectronicsStore
    from schemaorg_types.ElementarySchool import ElementarySchool
    from schemaorg_types.EmailMessage import EmailMessage
    from schemaorg_types.Embassy import Embassy
    from schemaorg_types.Emergency import Emergency
    from schemaorg_types.EmergencyService import EmergencyService
    from schemaorg_types.EmployeeRole import EmployeeRole
    from schemaorg_types.EmployerAggregateRating import EmployerAggregateRating
    from schemaorg_types.EmployerReview import EmployerReview
    from schemaorg_types.EmploymentAgency import EmploymentAgency
    from schemaorg_types.Endocrine import Endocrine
    from schemaorg_types.EndorseAction import EndorseAction
    from schemaorg_types.EndorsementRating import EndorsementRating
    from schemaorg_types.Energy import Energy
    from schemaorg_types.EnergyConsumptionDetails import EnergyConsumptionDetails
    from schemaorg_types.EnergyEfficiencyEnumeration import EnergyEfficiencyEnumeration
    from schemaorg_types.EnergyStarCertified import EnergyStarCertified
    from schemaorg_types.EnergyStarEnergyEfficiencyEnumeration import (
        EnergyStarEnergyEfficiencyEnumeration,
    )
    from schemaorg_types.EngineSpecification import EngineSpecification
    from schemaorg_types.EnrollingByInvitation import EnrollingByInvitation
    from schemaorg_types.EntertainmentBusiness import EntertainmentBusiness
    from schemaorg_types.EntryPoint import EntryPoint
    from schemaorg_types.Enumeration import Enumeration
    from schemaorg_types.Episode import Episode
    from schemaorg_types.EPRelease import EPRelease
    from schemaorg_types.EUEnergyEfficiencyCategoryA import EUEnergyEfficiencyCategoryA
    from schemaorg_types.EUEnergyEfficiencyCategoryA1Plus import (
        EUEnergyEfficiencyCategoryA1Plus,
    )
    from schemaorg_types.EUEnergyEfficiencyCategoryA2Plus import (
        EUEnergyEfficiencyCategoryA2Plus,
    )
    from schemaorg_types.EUEnergyEfficiencyCategoryA3Plus import (
        EUEnergyEfficiencyCategoryA3Plus,
    )
    from schemaorg_types.EUEnergyEfficiencyCategoryB import EUEnergyEfficiencyCategoryB
    from schemaorg_types.EUEnergyEfficiencyCategoryC import EUEnergyEfficiencyCategoryC
    from schemaorg_types.EUEnergyEfficiencyCategoryD import EUEnergyEfficiencyCategoryD
    from schemaorg_types.EUEnergyEfficiencyCategoryE import EUEnergyEfficiencyCategoryE
    from schemaorg_types.EUEnergyEfficiencyCategoryF import EUEnergyEfficiencyCategoryF
    from schemaorg_types.EUEnergyEfficiencyCategoryG import EUEnergyEfficiencyCategoryG
    from schemaorg_types.EUEnergyEfficiencyEnumeration import (
        EUEnergyEfficiencyEnumeration,
    )
    from schemaorg_types.Event import Event
    from schemaorg_types.EventAttendanceModeEnumeration import (
        EventAttendanceModeEnumeration,
    )
    from schemaorg_types.EventCancelled import EventCancelled
    from schemaorg_types.EventMovedOnline import EventMovedOnline
    from schemaorg_types.EventPostponed import EventPostponed
    from schemaorg_types.EventRescheduled import EventRescheduled
    from schemaorg_types.EventReservation import EventReservation
    from schemaorg_types.EventScheduled import EventScheduled
    from schemaorg_types.EventSeries import EventSeries
    from schemaorg_types.EventStatusType import EventStatusType
    from schemaorg_types.EventVenue import EventVenue
    from schemaorg_types.EvidenceLevelA import EvidenceLevelA
    from schemaorg_types.EvidenceLevelB import EvidenceLevelB
    from schemaorg_types.EvidenceLevelC import EvidenceLevelC
    from schemaorg_types.ExchangeRateSpecification import ExchangeRateSpecification
    from schemaorg_types.ExchangeRefund import ExchangeRefund
    from schemaorg_types.ExerciseAction import ExerciseAction
    from schemaorg_types.ExerciseGym import ExerciseGym
    from schemaorg_types.ExercisePlan import ExercisePlan
    from schemaorg_types.ExhibitionEvent import ExhibitionEvent
    from schemaorg_types.Eye import Eye
    from schemaorg_types.FailedActionStatus import FailedActionStatus
    from schemaorg_types.False_ import False_
    from schemaorg_types.FAQPage import FAQPage
    from schemaorg_types.FastFoodRestaurant import FastFoodRestaurant
    from schemaorg_types.FDAcategoryA import FDAcategoryA
    from schemaorg_types.FDAcategoryB import FDAcategoryB
    from schemaorg_types.FDAcategoryC import FDAcategoryC
    from schemaorg_types.FDAcategoryD import FDAcategoryD
    from schemaorg_types.FDAcategoryX import FDAcategoryX
    from schemaorg_types.FDAnotEvaluated import FDAnotEvaluated
    from schemaorg_types.Female import Female
    from schemaorg_types.Festival import Festival
    from schemaorg_types.FilmAction import FilmAction
    from schemaorg_types.FinancialProduct import FinancialProduct
    from schemaorg_types.FinancialService import FinancialService
    from schemaorg_types.FindAction import FindAction
    from schemaorg_types.FireStation import FireStation
    from schemaorg_types.Flexibility import Flexibility
    from schemaorg_types.Flight import Flight
    from schemaorg_types.FlightReservation import FlightReservation
    from schemaorg_types.Float import Float
    from schemaorg_types.FloorPlan import FloorPlan
    from schemaorg_types.Florist import Florist
    from schemaorg_types.FMRadioChannel import FMRadioChannel
    from schemaorg_types.FollowAction import FollowAction
    from schemaorg_types.FoodEstablishment import FoodEstablishment
    from schemaorg_types.FoodEstablishmentReservation import (
        FoodEstablishmentReservation,
    )
    from schemaorg_types.FoodEvent import FoodEvent
    from schemaorg_types.FoodService import FoodService
    from schemaorg_types.FourWheelDriveConfiguration import FourWheelDriveConfiguration
    from schemaorg_types.FreeReturn import FreeReturn
    from schemaorg_types.Friday import Friday
    from schemaorg_types.FrontWheelDriveConfiguration import (
        FrontWheelDriveConfiguration,
    )
    from schemaorg_types.FullGameAvailability import FullGameAvailability
    from schemaorg_types.FullRefund import FullRefund
    from schemaorg_types.FundingAgency import FundingAgency
    from schemaorg_types.FundingScheme import FundingScheme
    from schemaorg_types.Fungus import Fungus
    from schemaorg_types.FurnitureStore import FurnitureStore
    from schemaorg_types.Game import Game
    from schemaorg_types.GameAvailabilityEnumeration import GameAvailabilityEnumeration
    from schemaorg_types.GamePlayMode import GamePlayMode
    from schemaorg_types.GameServer import GameServer
    from schemaorg_types.GameServerStatus import GameServerStatus
    from schemaorg_types.GardenStore import GardenStore
    from schemaorg_types.GasStation import GasStation
    from schemaorg_types.Gastroenterologic import Gastroenterologic
    from schemaorg_types.GatedResidenceCommunity import GatedResidenceCommunity
    from schemaorg_types.GenderType import GenderType
    from schemaorg_types.Gene import Gene
    from schemaorg_types.GeneralContractor import GeneralContractor
    from schemaorg_types.GenericWebPlatform import GenericWebPlatform
    from schemaorg_types.Genetic import Genetic
    from schemaorg_types.Genitourinary import Genitourinary
    from schemaorg_types.GeoCircle import GeoCircle
    from schemaorg_types.GeoCoordinates import GeoCoordinates
    from schemaorg_types.GeoShape import GeoShape
    from schemaorg_types.GeospatialGeometry import GeospatialGeometry
    from schemaorg_types.Geriatric import Geriatric
    from schemaorg_types.GettingAccessHealthAspect import GettingAccessHealthAspect
    from schemaorg_types.GiveAction import GiveAction
    from schemaorg_types.GlutenFreeDiet import GlutenFreeDiet
    from schemaorg_types.GolfCourse import GolfCourse
    from schemaorg_types.GovernmentBenefitsType import GovernmentBenefitsType
    from schemaorg_types.GovernmentBuilding import GovernmentBuilding
    from schemaorg_types.GovernmentOffice import GovernmentOffice
    from schemaorg_types.GovernmentOrganization import GovernmentOrganization
    from schemaorg_types.GovernmentPermit import GovernmentPermit
    from schemaorg_types.GovernmentService import GovernmentService
    from schemaorg_types.Grant import Grant
    from schemaorg_types.GraphicNovel import GraphicNovel
    from schemaorg_types.GroceryStore import GroceryStore
    from schemaorg_types.GroupBoardingPolicy import GroupBoardingPolicy
    from schemaorg_types.Guide import Guide
    from schemaorg_types.Gynecologic import Gynecologic
    from schemaorg_types.Hackathon import Hackathon
    from schemaorg_types.HairSalon import HairSalon
    from schemaorg_types.HalalDiet import HalalDiet
    from schemaorg_types.Hardcover import Hardcover
    from schemaorg_types.HardwareStore import HardwareStore
    from schemaorg_types.Head import Head
    from schemaorg_types.HealthAndBeautyBusiness import HealthAndBeautyBusiness
    from schemaorg_types.HealthAspectEnumeration import HealthAspectEnumeration
    from schemaorg_types.HealthCare import HealthCare
    from schemaorg_types.HealthcareConsideration import HealthcareConsideration
    from schemaorg_types.HealthClub import HealthClub
    from schemaorg_types.HealthInsurancePlan import HealthInsurancePlan
    from schemaorg_types.HealthPlanCostSharingSpecification import (
        HealthPlanCostSharingSpecification,
    )
    from schemaorg_types.HealthPlanFormulary import HealthPlanFormulary
    from schemaorg_types.HealthPlanNetwork import HealthPlanNetwork
    from schemaorg_types.HealthTopicContent import HealthTopicContent
    from schemaorg_types.HearingImpairedSupported import HearingImpairedSupported
    from schemaorg_types.Hematologic import Hematologic
    from schemaorg_types.HighSchool import HighSchool
    from schemaorg_types.HinduDiet import HinduDiet
    from schemaorg_types.HinduTemple import HinduTemple
    from schemaorg_types.HobbyShop import HobbyShop
    from schemaorg_types.HomeAndConstructionBusiness import HomeAndConstructionBusiness
    from schemaorg_types.HomeGoodsStore import HomeGoodsStore
    from schemaorg_types.Homeopathic import Homeopathic
    from schemaorg_types.Hospital import Hospital
    from schemaorg_types.Hostel import Hostel
    from schemaorg_types.Hotel import Hotel
    from schemaorg_types.HotelRoom import HotelRoom
    from schemaorg_types.House import House
    from schemaorg_types.HousePainter import HousePainter
    from schemaorg_types.HowItWorksHealthAspect import HowItWorksHealthAspect
    from schemaorg_types.HowOrWhereHealthAspect import HowOrWhereHealthAspect
    from schemaorg_types.HowTo import HowTo
    from schemaorg_types.HowToDirection import HowToDirection
    from schemaorg_types.HowToItem import HowToItem
    from schemaorg_types.HowToSection import HowToSection
    from schemaorg_types.HowToStep import HowToStep
    from schemaorg_types.HowToSupply import HowToSupply
    from schemaorg_types.HowToTip import HowToTip
    from schemaorg_types.HowToTool import HowToTool
    from schemaorg_types.HVACBusiness import HVACBusiness
    from schemaorg_types.HyperToc import HyperToc
    from schemaorg_types.HyperTocEntry import HyperTocEntry
    from schemaorg_types.IceCreamShop import IceCreamShop
    from schemaorg_types.IgnoreAction import IgnoreAction
    from schemaorg_types.ImageGallery import ImageGallery
    from schemaorg_types.ImageObject import ImageObject
    from schemaorg_types.ImageObjectSnapshot import ImageObjectSnapshot
    from schemaorg_types.ImagingTest import ImagingTest
    from schemaorg_types.IndividualProduct import IndividualProduct
    from schemaorg_types.Infectious import Infectious
    from schemaorg_types.InfectiousAgentClass import InfectiousAgentClass
    from schemaorg_types.InfectiousDisease import InfectiousDisease
    from schemaorg_types.InForce import InForce
    from schemaorg_types.InformAction import InformAction
    from schemaorg_types.IngredientsHealthAspect import IngredientsHealthAspect
    from schemaorg_types.InsertAction import InsertAction
    from schemaorg_types.InstallAction import InstallAction
    from schemaorg_types.Installment import Installment
    from schemaorg_types.InStock import InStock
    from schemaorg_types.InStoreOnly import InStoreOnly
    from schemaorg_types.InsuranceAgency import InsuranceAgency
    from schemaorg_types.Intangible import Intangible
    from schemaorg_types.Integer import Integer
    from schemaorg_types.InteractAction import InteractAction
    from schemaorg_types.InteractionCounter import InteractionCounter
    from schemaorg_types.InternationalTrial import InternationalTrial
    from schemaorg_types.InternetCafe import InternetCafe
    from schemaorg_types.InvestmentFund import InvestmentFund
    from schemaorg_types.InvestmentOrDeposit import InvestmentOrDeposit
    from schemaorg_types.InviteAction import InviteAction
    from schemaorg_types.Invoice import Invoice
    from schemaorg_types.InvoicePrice import InvoicePrice
    from schemaorg_types.IOSPlatform import IOSPlatform
    from schemaorg_types.ItemAvailability import ItemAvailability
    from schemaorg_types.ItemList import ItemList
    from schemaorg_types.ItemListOrderAscending import ItemListOrderAscending
    from schemaorg_types.ItemListOrderDescending import ItemListOrderDescending
    from schemaorg_types.ItemListOrderType import ItemListOrderType
    from schemaorg_types.ItemListUnordered import ItemListUnordered
    from schemaorg_types.ItemPage import ItemPage
    from schemaorg_types.JewelryStore import JewelryStore
    from schemaorg_types.JobPosting import JobPosting
    from schemaorg_types.JoinAction import JoinAction
    from schemaorg_types.Joint import Joint
    from schemaorg_types.KosherDiet import KosherDiet
    from schemaorg_types.LaboratoryScience import LaboratoryScience
    from schemaorg_types.LakeBodyOfWater import LakeBodyOfWater
    from schemaorg_types.Landform import Landform
    from schemaorg_types.LandmarksOrHistoricalBuildings import (
        LandmarksOrHistoricalBuildings,
    )
    from schemaorg_types.Language import Language
    from schemaorg_types.LaserDiscFormat import LaserDiscFormat
    from schemaorg_types.LearningResource import LearningResource
    from schemaorg_types.LeaveAction import LeaveAction
    from schemaorg_types.LeftHandDriving import LeftHandDriving
    from schemaorg_types.LegalForceStatus import LegalForceStatus
    from schemaorg_types.LegalService import LegalService
    from schemaorg_types.LegalValueLevel import LegalValueLevel
    from schemaorg_types.Legislation import Legislation
    from schemaorg_types.LegislationObject import LegislationObject
    from schemaorg_types.LegislativeBuilding import LegislativeBuilding
    from schemaorg_types.LeisureTimeActivity import LeisureTimeActivity
    from schemaorg_types.LendAction import LendAction
    from schemaorg_types.Library import Library
    from schemaorg_types.LibrarySystem import LibrarySystem
    from schemaorg_types.LifestyleModification import LifestyleModification
    from schemaorg_types.Ligament import Ligament
    from schemaorg_types.LikeAction import LikeAction
    from schemaorg_types.LimitedAvailability import LimitedAvailability
    from schemaorg_types.LimitedByGuaranteeCharity import LimitedByGuaranteeCharity
    from schemaorg_types.LinkRole import LinkRole
    from schemaorg_types.LiquorStore import LiquorStore
    from schemaorg_types.ListenAction import ListenAction
    from schemaorg_types.ListItem import ListItem
    from schemaorg_types.ListPrice import ListPrice
    from schemaorg_types.LiteraryEvent import LiteraryEvent
    from schemaorg_types.LiveAlbum import LiveAlbum
    from schemaorg_types.LiveBlogPosting import LiveBlogPosting
    from schemaorg_types.LivingWithHealthAspect import LivingWithHealthAspect
    from schemaorg_types.LoanOrCredit import LoanOrCredit
    from schemaorg_types.LocalBusiness import LocalBusiness
    from schemaorg_types.LocationFeatureSpecification import (
        LocationFeatureSpecification,
    )
    from schemaorg_types.LockerDelivery import LockerDelivery
    from schemaorg_types.Locksmith import Locksmith
    from schemaorg_types.LodgingBusiness import LodgingBusiness
    from schemaorg_types.LodgingReservation import LodgingReservation
    from schemaorg_types.Longitudinal import Longitudinal
    from schemaorg_types.LoseAction import LoseAction
    from schemaorg_types.LowCalorieDiet import LowCalorieDiet
    from schemaorg_types.LowFatDiet import LowFatDiet
    from schemaorg_types.LowLactoseDiet import LowLactoseDiet
    from schemaorg_types.LowSaltDiet import LowSaltDiet
    from schemaorg_types.Lung import Lung
    from schemaorg_types.LymphaticVessel import LymphaticVessel
    from schemaorg_types.Male import Male
    from schemaorg_types.Manuscript import Manuscript
    from schemaorg_types.Map import Map
    from schemaorg_types.MapCategoryType import MapCategoryType
    from schemaorg_types.MarryAction import MarryAction
    from schemaorg_types.Mass import Mass
    from schemaorg_types.MathSolver import MathSolver
    from schemaorg_types.MaximumDoseSchedule import MaximumDoseSchedule
    from schemaorg_types.MayTreatHealthAspect import MayTreatHealthAspect
    from schemaorg_types.MeasurementTypeEnumeration import MeasurementTypeEnumeration
    from schemaorg_types.MediaGallery import MediaGallery
    from schemaorg_types.MediaManipulationRatingEnumeration import (
        MediaManipulationRatingEnumeration,
    )
    from schemaorg_types.MediaObject import MediaObject
    from schemaorg_types.MediaReview import MediaReview
    from schemaorg_types.MediaReviewItem import MediaReviewItem
    from schemaorg_types.MediaSubscription import MediaSubscription
    from schemaorg_types.MedicalAudience import MedicalAudience
    from schemaorg_types.MedicalAudienceType import MedicalAudienceType
    from schemaorg_types.MedicalBusiness import MedicalBusiness
    from schemaorg_types.MedicalCause import MedicalCause
    from schemaorg_types.MedicalClinic import MedicalClinic
    from schemaorg_types.MedicalCode import MedicalCode
    from schemaorg_types.MedicalCondition import MedicalCondition
    from schemaorg_types.MedicalConditionStage import MedicalConditionStage
    from schemaorg_types.MedicalContraindication import MedicalContraindication
    from schemaorg_types.MedicalDevice import MedicalDevice
    from schemaorg_types.MedicalDevicePurpose import MedicalDevicePurpose
    from schemaorg_types.MedicalEntity import MedicalEntity
    from schemaorg_types.MedicalEnumeration import MedicalEnumeration
    from schemaorg_types.MedicalEvidenceLevel import MedicalEvidenceLevel
    from schemaorg_types.MedicalGuideline import MedicalGuideline
    from schemaorg_types.MedicalGuidelineContraindication import (
        MedicalGuidelineContraindication,
    )
    from schemaorg_types.MedicalGuidelineRecommendation import (
        MedicalGuidelineRecommendation,
    )
    from schemaorg_types.MedicalImagingTechnique import MedicalImagingTechnique
    from schemaorg_types.MedicalIndication import MedicalIndication
    from schemaorg_types.MedicalIntangible import MedicalIntangible
    from schemaorg_types.MedicalObservationalStudy import MedicalObservationalStudy
    from schemaorg_types.MedicalObservationalStudyDesign import (
        MedicalObservationalStudyDesign,
    )
    from schemaorg_types.MedicalOrganization import MedicalOrganization
    from schemaorg_types.MedicalProcedure import MedicalProcedure
    from schemaorg_types.MedicalProcedureType import MedicalProcedureType
    from schemaorg_types.MedicalResearcher import MedicalResearcher
    from schemaorg_types.MedicalRiskCalculator import MedicalRiskCalculator
    from schemaorg_types.MedicalRiskEstimator import MedicalRiskEstimator
    from schemaorg_types.MedicalRiskFactor import MedicalRiskFactor
    from schemaorg_types.MedicalRiskScore import MedicalRiskScore
    from schemaorg_types.MedicalScholarlyArticle import MedicalScholarlyArticle
    from schemaorg_types.MedicalSign import MedicalSign
    from schemaorg_types.MedicalSignOrSymptom import MedicalSignOrSymptom
    from schemaorg_types.MedicalSpecialty import MedicalSpecialty
    from schemaorg_types.MedicalStudy import MedicalStudy
    from schemaorg_types.MedicalStudyStatus import MedicalStudyStatus
    from schemaorg_types.MedicalSymptom import MedicalSymptom
    from schemaorg_types.MedicalTest import MedicalTest
    from schemaorg_types.MedicalTestPanel import MedicalTestPanel
    from schemaorg_types.MedicalTherapy import MedicalTherapy
    from schemaorg_types.MedicalTrial import MedicalTrial
    from schemaorg_types.MedicalTrialDesign import MedicalTrialDesign
    from schemaorg_types.MedicalWebPage import MedicalWebPage
    from schemaorg_types.MedicineSystem import MedicineSystem
    from schemaorg_types.MeetingRoom import MeetingRoom
    from schemaorg_types.MensClothingStore import MensClothingStore
    from schemaorg_types.Menu import Menu
    from schemaorg_types.MenuItem import MenuItem
    from schemaorg_types.MenuSection import MenuSection
    from schemaorg_types.MerchantReturnEnumeration import MerchantReturnEnumeration
    from schemaorg_types.MerchantReturnFiniteReturnWindow import (
        MerchantReturnFiniteReturnWindow,
    )
    from schemaorg_types.MerchantReturnNotPermitted import MerchantReturnNotPermitted
    from schemaorg_types.MerchantReturnPolicy import MerchantReturnPolicy
    from schemaorg_types.MerchantReturnPolicySeasonalOverride import (
        MerchantReturnPolicySeasonalOverride,
    )
    from schemaorg_types.MerchantReturnUnlimitedWindow import (
        MerchantReturnUnlimitedWindow,
    )
    from schemaorg_types.MerchantReturnUnspecified import MerchantReturnUnspecified
    from schemaorg_types.Message import Message
    from schemaorg_types.MiddleSchool import MiddleSchool
    from schemaorg_types.Midwifery import Midwifery
    from schemaorg_types.MinimumAdvertisedPrice import MinimumAdvertisedPrice
    from schemaorg_types.MisconceptionsHealthAspect import MisconceptionsHealthAspect
    from schemaorg_types.MixedEventAttendanceMode import MixedEventAttendanceMode
    from schemaorg_types.MixtapeAlbum import MixtapeAlbum
    from schemaorg_types.MobileApplication import MobileApplication
    from schemaorg_types.MobilePhoneStore import MobilePhoneStore
    from schemaorg_types.MobileWebPlatform import MobileWebPlatform
    from schemaorg_types.MolecularEntity import MolecularEntity
    from schemaorg_types.Monday import Monday
    from schemaorg_types.MonetaryAmount import MonetaryAmount
    from schemaorg_types.MonetaryAmountDistribution import MonetaryAmountDistribution
    from schemaorg_types.MonetaryGrant import MonetaryGrant
    from schemaorg_types.MoneyTransfer import MoneyTransfer
    from schemaorg_types.MortgageLoan import MortgageLoan
    from schemaorg_types.Mosque import Mosque
    from schemaorg_types.Motel import Motel
    from schemaorg_types.Motorcycle import Motorcycle
    from schemaorg_types.MotorcycleDealer import MotorcycleDealer
    from schemaorg_types.MotorcycleRepair import MotorcycleRepair
    from schemaorg_types.MotorizedBicycle import MotorizedBicycle
    from schemaorg_types.Mountain import Mountain
    from schemaorg_types.MoveAction import MoveAction
    from schemaorg_types.Movie import Movie
    from schemaorg_types.MovieClip import MovieClip
    from schemaorg_types.MovieRentalStore import MovieRentalStore
    from schemaorg_types.MovieSeries import MovieSeries
    from schemaorg_types.MovieTheater import MovieTheater
    from schemaorg_types.MovingCompany import MovingCompany
    from schemaorg_types.MRI import MRI
    from schemaorg_types.MSRP import MSRP
    from schemaorg_types.MulticellularParasite import MulticellularParasite
    from schemaorg_types.MultiCenterTrial import MultiCenterTrial
    from schemaorg_types.MultiPlayer import MultiPlayer
    from schemaorg_types.Muscle import Muscle
    from schemaorg_types.Musculoskeletal import Musculoskeletal
    from schemaorg_types.MusculoskeletalExam import MusculoskeletalExam
    from schemaorg_types.Museum import Museum
    from schemaorg_types.MusicAlbum import MusicAlbum
    from schemaorg_types.MusicAlbumProductionType import MusicAlbumProductionType
    from schemaorg_types.MusicAlbumReleaseType import MusicAlbumReleaseType
    from schemaorg_types.MusicComposition import MusicComposition
    from schemaorg_types.MusicEvent import MusicEvent
    from schemaorg_types.MusicGroup import MusicGroup
    from schemaorg_types.MusicPlaylist import MusicPlaylist
    from schemaorg_types.MusicRecording import MusicRecording
    from schemaorg_types.MusicRelease import MusicRelease
    from schemaorg_types.MusicReleaseFormatType import MusicReleaseFormatType
    from schemaorg_types.MusicStore import MusicStore
    from schemaorg_types.MusicVenue import MusicVenue
    from schemaorg_types.MusicVideoObject import MusicVideoObject
    from schemaorg_types.NailSalon import NailSalon
    from schemaorg_types.NarcoticConsideration import NarcoticConsideration
    from schemaorg_types.Neck import Neck
    from schemaorg_types.Nerve import Nerve
    from schemaorg_types.Neuro import Neuro
    from schemaorg_types.Neurologic import Neurologic
    from schemaorg_types.NewCondition import NewCondition
    from schemaorg_types.NewsArticle import NewsArticle
    from schemaorg_types.NewsMediaOrganization import NewsMediaOrganization
    from schemaorg_types.Newspaper import Newspaper
    from schemaorg_types.NGO import NGO
    from schemaorg_types.NightClub import NightClub
    from schemaorg_types.NLNonprofitType import NLNonprofitType
    from schemaorg_types.NoninvasiveProcedure import NoninvasiveProcedure
    from schemaorg_types.Nonprofit501a import Nonprofit501a
    from schemaorg_types.Nonprofit501c1 import Nonprofit501c1
    from schemaorg_types.Nonprofit501c2 import Nonprofit501c2
    from schemaorg_types.Nonprofit501c3 import Nonprofit501c3
    from schemaorg_types.Nonprofit501c4 import Nonprofit501c4
    from schemaorg_types.Nonprofit501c5 import Nonprofit501c5
    from schemaorg_types.Nonprofit501c6 import Nonprofit501c6
    from schemaorg_types.Nonprofit501c7 import Nonprofit501c7
    from schemaorg_types.Nonprofit501c8 import Nonprofit501c8
    from schemaorg_types.Nonprofit501c9 import Nonprofit501c9
    from schemaorg_types.Nonprofit501c10 import Nonprofit501c10
    from schemaorg_types.Nonprofit501c11 import Nonprofit501c11
    from schemaorg_types.Nonprofit501c12 import Nonprofit501c12
    from schemaorg_types.Nonprofit501c13 import Nonprofit501c13
    from schemaorg_types.Nonprofit501c14 import Nonprofit501c14
    from schemaorg_types.Nonprofit501c15 import Nonprofit501c15
    from schemaorg_types.Nonprofit501c16 import Nonprofit501c16
    from schemaorg_types.Nonprofit501c17 import Nonprofit501c17
    from schemaorg_types.Nonprofit501c18 import Nonprofit501c18
    from schemaorg_types.Nonprofit501c19 import Nonprofit501c19
    from schemaorg_types.Nonprofit501c20 import Nonprofit501c20
    from schemaorg_types.Nonprofit501c21 import Nonprofit501c21
    from schemaorg_types.Nonprofit501c22 import Nonprofit501c22
    from schemaorg_types.Nonprofit501c23 import Nonprofit501c23
    from schemaorg_types.Nonprofit501c24 import Nonprofit501c24
    from schemaorg_types.Nonprofit501c25 import Nonprofit501c25
    from schemaorg_types.Nonprofit501c26 import Nonprofit501c26
    from schemaorg_types.Nonprofit501c27 import Nonprofit501c27
    from schemaorg_types.Nonprofit501c28 import Nonprofit501c28
    from schemaorg_types.Nonprofit501d import Nonprofit501d
    from schemaorg_types.Nonprofit501e import Nonprofit501e
    from schemaorg_types.Nonprofit501f import Nonprofit501f
    from schemaorg_types.Nonprofit501k import Nonprofit501k
    from schemaorg_types.Nonprofit501n import Nonprofit501n
    from schemaorg_types.Nonprofit501q import Nonprofit501q
    from schemaorg_types.Nonprofit527 import Nonprofit527
    from schemaorg_types.NonprofitANBI import NonprofitANBI
    from schemaorg_types.NonprofitSBBI import NonprofitSBBI
    from schemaorg_types.NonprofitType import NonprofitType
    from schemaorg_types.Nose import Nose
    from schemaorg_types.Notary import Notary
    from schemaorg_types.NoteDigitalDocument import NoteDigitalDocument
    from schemaorg_types.NotInForce import NotInForce
    from schemaorg_types.NotYetRecruiting import NotYetRecruiting
    from schemaorg_types.Number import Number
    from schemaorg_types.Nursing import Nursing
    from schemaorg_types.NutritionInformation import NutritionInformation
    from schemaorg_types.Observation import Observation
    from schemaorg_types.Observational import Observational
    from schemaorg_types.Obstetric import Obstetric
    from schemaorg_types.Occupation import Occupation
    from schemaorg_types.OccupationalActivity import OccupationalActivity
    from schemaorg_types.OccupationalExperienceRequirements import (
        OccupationalExperienceRequirements,
    )
    from schemaorg_types.OccupationalTherapy import OccupationalTherapy
    from schemaorg_types.OceanBodyOfWater import OceanBodyOfWater
    from schemaorg_types.Offer import Offer
    from schemaorg_types.OfferCatalog import OfferCatalog
    from schemaorg_types.OfferForLease import OfferForLease
    from schemaorg_types.OfferForPurchase import OfferForPurchase
    from schemaorg_types.OfferItemCondition import OfferItemCondition
    from schemaorg_types.OfferShippingDetails import OfferShippingDetails
    from schemaorg_types.OfficeEquipmentStore import OfficeEquipmentStore
    from schemaorg_types.OfficialLegalValue import OfficialLegalValue
    from schemaorg_types.OfflineEventAttendanceMode import OfflineEventAttendanceMode
    from schemaorg_types.OfflinePermanently import OfflinePermanently
    from schemaorg_types.OfflineTemporarily import OfflineTemporarily
    from schemaorg_types.Oncologic import Oncologic
    from schemaorg_types.OnDemandEvent import OnDemandEvent
    from schemaorg_types.OneTimePayments import OneTimePayments
    from schemaorg_types.Online import Online
    from schemaorg_types.OnlineBusiness import OnlineBusiness
    from schemaorg_types.OnlineEventAttendanceMode import OnlineEventAttendanceMode
    from schemaorg_types.OnlineFull import OnlineFull
    from schemaorg_types.OnlineOnly import OnlineOnly
    from schemaorg_types.OnlineStore import OnlineStore
    from schemaorg_types.OnSitePickup import OnSitePickup
    from schemaorg_types.OpeningHoursSpecification import OpeningHoursSpecification
    from schemaorg_types.OpenTrial import OpenTrial
    from schemaorg_types.OpinionNewsArticle import OpinionNewsArticle
    from schemaorg_types.Optician import Optician
    from schemaorg_types.Optometric import Optometric
    from schemaorg_types.Order import Order
    from schemaorg_types.OrderAction import OrderAction
    from schemaorg_types.OrderCancelled import OrderCancelled
    from schemaorg_types.OrderDelivered import OrderDelivered
    from schemaorg_types.OrderInTransit import OrderInTransit
    from schemaorg_types.OrderItem import OrderItem
    from schemaorg_types.OrderPaymentDue import OrderPaymentDue
    from schemaorg_types.OrderPickupAvailable import OrderPickupAvailable
    from schemaorg_types.OrderProblem import OrderProblem
    from schemaorg_types.OrderProcessing import OrderProcessing
    from schemaorg_types.OrderReturned import OrderReturned
    from schemaorg_types.OrderStatus import OrderStatus
    from schemaorg_types.Organization import Organization
    from schemaorg_types.OrganizationRole import OrganizationRole
    from schemaorg_types.OrganizeAction import OrganizeAction
    from schemaorg_types.OriginalMediaContent import OriginalMediaContent
    from schemaorg_types.OriginalShippingFees import OriginalShippingFees
    from schemaorg_types.Osteopathic import Osteopathic
    from schemaorg_types.OTC import OTC
    from schemaorg_types.Otolaryngologic import Otolaryngologic
    from schemaorg_types.OutletStore import OutletStore
    from schemaorg_types.OutOfStock import OutOfStock
    from schemaorg_types.OverviewHealthAspect import OverviewHealthAspect
    from schemaorg_types.OwnershipInfo import OwnershipInfo
    from schemaorg_types.PaidLeave import PaidLeave
    from schemaorg_types.PaintAction import PaintAction
    from schemaorg_types.Painting import Painting
    from schemaorg_types.PalliativeProcedure import PalliativeProcedure
    from schemaorg_types.Paperback import Paperback
    from schemaorg_types.ParcelDelivery import ParcelDelivery
    from schemaorg_types.ParcelService import ParcelService
    from schemaorg_types.ParentalSupport import ParentalSupport
    from schemaorg_types.ParentAudience import ParentAudience
    from schemaorg_types.Park import Park
    from schemaorg_types.ParkingFacility import ParkingFacility
    from schemaorg_types.ParkingMap import ParkingMap
    from schemaorg_types.PartiallyInForce import PartiallyInForce
    from schemaorg_types.Pathology import Pathology
    from schemaorg_types.PathologyTest import PathologyTest
    from schemaorg_types.Patient import Patient
    from schemaorg_types.PatientExperienceHealthAspect import (
        PatientExperienceHealthAspect,
    )
    from schemaorg_types.PawnShop import PawnShop
    from schemaorg_types.PayAction import PayAction
    from schemaorg_types.PaymentAutomaticallyApplied import PaymentAutomaticallyApplied
    from schemaorg_types.PaymentCard import PaymentCard
    from schemaorg_types.PaymentChargeSpecification import PaymentChargeSpecification
    from schemaorg_types.PaymentComplete import PaymentComplete
    from schemaorg_types.PaymentDeclined import PaymentDeclined
    from schemaorg_types.PaymentDue import PaymentDue
    from schemaorg_types.PaymentMethod import PaymentMethod
    from schemaorg_types.PaymentPastDue import PaymentPastDue
    from schemaorg_types.PaymentService import PaymentService
    from schemaorg_types.PaymentStatusType import PaymentStatusType
    from schemaorg_types.Pediatric import Pediatric
    from schemaorg_types.PeopleAudience import PeopleAudience
    from schemaorg_types.PercutaneousProcedure import PercutaneousProcedure
    from schemaorg_types.PerformAction import PerformAction
    from schemaorg_types.PerformanceRole import PerformanceRole
    from schemaorg_types.PerformingArtsTheater import PerformingArtsTheater
    from schemaorg_types.PerformingGroup import PerformingGroup
    from schemaorg_types.Periodical import Periodical
    from schemaorg_types.Permit import Permit
    from schemaorg_types.Person import Person
    from schemaorg_types.PET import PET
    from schemaorg_types.PetStore import PetStore
    from schemaorg_types.Pharmacy import Pharmacy
    from schemaorg_types.PharmacySpecialty import PharmacySpecialty
    from schemaorg_types.Photograph import Photograph
    from schemaorg_types.PhotographAction import PhotographAction
    from schemaorg_types.PhysicalActivity import PhysicalActivity
    from schemaorg_types.PhysicalActivityCategory import PhysicalActivityCategory
    from schemaorg_types.PhysicalExam import PhysicalExam
    from schemaorg_types.PhysicalTherapy import PhysicalTherapy
    from schemaorg_types.Physician import Physician
    from schemaorg_types.Physiotherapy import Physiotherapy
    from schemaorg_types.Place import Place
    from schemaorg_types.PlaceboControlledTrial import PlaceboControlledTrial
    from schemaorg_types.PlaceOfWorship import PlaceOfWorship
    from schemaorg_types.PlanAction import PlanAction
    from schemaorg_types.PlasticSurgery import PlasticSurgery
    from schemaorg_types.Play import Play
    from schemaorg_types.PlayAction import PlayAction
    from schemaorg_types.PlayGameAction import PlayGameAction
    from schemaorg_types.Playground import Playground
    from schemaorg_types.Plumber import Plumber
    from schemaorg_types.PodcastEpisode import PodcastEpisode
    from schemaorg_types.PodcastSeason import PodcastSeason
    from schemaorg_types.PodcastSeries import PodcastSeries
    from schemaorg_types.Podiatric import Podiatric
    from schemaorg_types.PoliceStation import PoliceStation
    from schemaorg_types.Pond import Pond
    from schemaorg_types.PostalAddress import PostalAddress
    from schemaorg_types.PostalCodeRangeSpecification import (
        PostalCodeRangeSpecification,
    )
    from schemaorg_types.Poster import Poster
    from schemaorg_types.PostOffice import PostOffice
    from schemaorg_types.PotentialActionStatus import PotentialActionStatus
    from schemaorg_types.PregnancyHealthAspect import PregnancyHealthAspect
    from schemaorg_types.PreOrder import PreOrder
    from schemaorg_types.PreOrderAction import PreOrderAction
    from schemaorg_types.PrependAction import PrependAction
    from schemaorg_types.PreSale import PreSale
    from schemaorg_types.Preschool import Preschool
    from schemaorg_types.PrescriptionOnly import PrescriptionOnly
    from schemaorg_types.PresentationDigitalDocument import PresentationDigitalDocument
    from schemaorg_types.PreventionHealthAspect import PreventionHealthAspect
    from schemaorg_types.PreventionIndication import PreventionIndication
    from schemaorg_types.PriceComponentTypeEnumeration import (
        PriceComponentTypeEnumeration,
    )
    from schemaorg_types.PriceSpecification import PriceSpecification
    from schemaorg_types.PriceTypeEnumeration import PriceTypeEnumeration
    from schemaorg_types.PrimaryCare import PrimaryCare
    from schemaorg_types.Prion import Prion
    from schemaorg_types.Product import Product
    from schemaorg_types.ProductCollection import ProductCollection
    from schemaorg_types.ProductGroup import ProductGroup
    from schemaorg_types.ProductModel import ProductModel
    from schemaorg_types.ProfessionalService import ProfessionalService
    from schemaorg_types.ProfilePage import ProfilePage
    from schemaorg_types.PrognosisHealthAspect import PrognosisHealthAspect
    from schemaorg_types.ProgramMembership import ProgramMembership
    from schemaorg_types.Project import Project
    from schemaorg_types.PronounceableText import PronounceableText
    from schemaorg_types.Property import Property
    from schemaorg_types.PropertyValue import PropertyValue
    from schemaorg_types.PropertyValueSpecification import PropertyValueSpecification
    from schemaorg_types.Protein import Protein
    from schemaorg_types.Protozoa import Protozoa
    from schemaorg_types.Psychiatric import Psychiatric
    from schemaorg_types.PsychologicalTreatment import PsychologicalTreatment
    from schemaorg_types.PublicationEvent import PublicationEvent
    from schemaorg_types.PublicationIssue import PublicationIssue
    from schemaorg_types.PublicationVolume import PublicationVolume
    from schemaorg_types.PublicHealth import PublicHealth
    from schemaorg_types.PublicHolidays import PublicHolidays
    from schemaorg_types.PublicSwimmingPool import PublicSwimmingPool
    from schemaorg_types.PublicToilet import PublicToilet
    from schemaorg_types.Pulmonary import Pulmonary
    from schemaorg_types.QAPage import QAPage
    from schemaorg_types.QualitativeValue import QualitativeValue
    from schemaorg_types.QuantitativeValue import QuantitativeValue
    from schemaorg_types.QuantitativeValueDistribution import (
        QuantitativeValueDistribution,
    )
    from schemaorg_types.Quantity import Quantity
    from schemaorg_types.Question import Question
    from schemaorg_types.Quiz import Quiz
    from schemaorg_types.Quotation import Quotation
    from schemaorg_types.QuoteAction import QuoteAction
    from schemaorg_types.RadiationTherapy import RadiationTherapy
    from schemaorg_types.RadioBroadcastService import RadioBroadcastService
    from schemaorg_types.RadioChannel import RadioChannel
    from schemaorg_types.RadioClip import RadioClip
    from schemaorg_types.RadioEpisode import RadioEpisode
    from schemaorg_types.Radiography import Radiography
    from schemaorg_types.RadioSeason import RadioSeason
    from schemaorg_types.RadioSeries import RadioSeries
    from schemaorg_types.RadioStation import RadioStation
    from schemaorg_types.RandomizedTrial import RandomizedTrial
    from schemaorg_types.Rating import Rating
    from schemaorg_types.ReactAction import ReactAction
    from schemaorg_types.ReadAction import ReadAction
    from schemaorg_types.ReadPermission import ReadPermission
    from schemaorg_types.RealEstateAgent import RealEstateAgent
    from schemaorg_types.RealEstateListing import RealEstateListing
    from schemaorg_types.RearWheelDriveConfiguration import RearWheelDriveConfiguration
    from schemaorg_types.ReceiveAction import ReceiveAction
    from schemaorg_types.Recipe import Recipe
    from schemaorg_types.Recommendation import Recommendation
    from schemaorg_types.RecommendedDoseSchedule import RecommendedDoseSchedule
    from schemaorg_types.Recruiting import Recruiting
    from schemaorg_types.RecyclingCenter import RecyclingCenter
    from schemaorg_types.ReducedRelevanceForChildrenConsideration import (
        ReducedRelevanceForChildrenConsideration,
    )
    from schemaorg_types.RefundTypeEnumeration import RefundTypeEnumeration
    from schemaorg_types.RefurbishedCondition import RefurbishedCondition
    from schemaorg_types.RegisterAction import RegisterAction
    from schemaorg_types.Registry import Registry
    from schemaorg_types.ReimbursementCap import ReimbursementCap
    from schemaorg_types.RejectAction import RejectAction
    from schemaorg_types.RelatedTopicsHealthAspect import RelatedTopicsHealthAspect
    from schemaorg_types.RemixAlbum import RemixAlbum
    from schemaorg_types.Renal import Renal
    from schemaorg_types.RentAction import RentAction
    from schemaorg_types.RentalCarReservation import RentalCarReservation
    from schemaorg_types.RentalVehicleUsage import RentalVehicleUsage
    from schemaorg_types.RepaymentSpecification import RepaymentSpecification
    from schemaorg_types.ReplaceAction import ReplaceAction
    from schemaorg_types.ReplyAction import ReplyAction
    from schemaorg_types.Report import Report
    from schemaorg_types.ReportageNewsArticle import ReportageNewsArticle
    from schemaorg_types.ReportedDoseSchedule import ReportedDoseSchedule
    from schemaorg_types.Researcher import Researcher
    from schemaorg_types.ResearchOrganization import ResearchOrganization
    from schemaorg_types.ResearchProject import ResearchProject
    from schemaorg_types.Reservation import Reservation
    from schemaorg_types.ReservationCancelled import ReservationCancelled
    from schemaorg_types.ReservationConfirmed import ReservationConfirmed
    from schemaorg_types.ReservationHold import ReservationHold
    from schemaorg_types.ReservationPackage import ReservationPackage
    from schemaorg_types.ReservationPending import ReservationPending
    from schemaorg_types.ReservationStatusType import ReservationStatusType
    from schemaorg_types.ReserveAction import ReserveAction
    from schemaorg_types.Reservoir import Reservoir
    from schemaorg_types.Residence import Residence
    from schemaorg_types.Resort import Resort
    from schemaorg_types.RespiratoryTherapy import RespiratoryTherapy
    from schemaorg_types.Restaurant import Restaurant
    from schemaorg_types.RestockingFees import RestockingFees
    from schemaorg_types.RestrictedDiet import RestrictedDiet
    from schemaorg_types.ResultsAvailable import ResultsAvailable
    from schemaorg_types.ResultsNotAvailable import ResultsNotAvailable
    from schemaorg_types.ResumeAction import ResumeAction
    from schemaorg_types.Retail import Retail
    from schemaorg_types.ReturnAction import ReturnAction
    from schemaorg_types.ReturnAtKiosk import ReturnAtKiosk
    from schemaorg_types.ReturnByMail import ReturnByMail
    from schemaorg_types.ReturnFeesCustomerResponsibility import (
        ReturnFeesCustomerResponsibility,
    )
    from schemaorg_types.ReturnFeesEnumeration import ReturnFeesEnumeration
    from schemaorg_types.ReturnInStore import ReturnInStore
    from schemaorg_types.ReturnLabelCustomerResponsibility import (
        ReturnLabelCustomerResponsibility,
    )
    from schemaorg_types.ReturnLabelDownloadAndPrint import ReturnLabelDownloadAndPrint
    from schemaorg_types.ReturnLabelInBox import ReturnLabelInBox
    from schemaorg_types.ReturnLabelSourceEnumeration import (
        ReturnLabelSourceEnumeration,
    )
    from schemaorg_types.ReturnMethodEnumeration import ReturnMethodEnumeration
    from schemaorg_types.ReturnShippingFees import ReturnShippingFees
    from schemaorg_types.Review import Review
    from schemaorg_types.ReviewAction import ReviewAction
    from schemaorg_types.ReviewNewsArticle import ReviewNewsArticle
    from schemaorg_types.Rheumatologic import Rheumatologic
    from schemaorg_types.RightHandDriving import RightHandDriving
    from schemaorg_types.RisksOrComplicationsHealthAspect import (
        RisksOrComplicationsHealthAspect,
    )
    from schemaorg_types.RiverBodyOfWater import RiverBodyOfWater
    from schemaorg_types.Role import Role
    from schemaorg_types.RoofingContractor import RoofingContractor
    from schemaorg_types.Room import Room
    from schemaorg_types.RsvpAction import RsvpAction
    from schemaorg_types.RsvpResponseMaybe import RsvpResponseMaybe
    from schemaorg_types.RsvpResponseNo import RsvpResponseNo
    from schemaorg_types.RsvpResponseType import RsvpResponseType
    from schemaorg_types.RsvpResponseYes import RsvpResponseYes
    from schemaorg_types.RVPark import RVPark
    from schemaorg_types.SafetyHealthAspect import SafetyHealthAspect
    from schemaorg_types.SaleEvent import SaleEvent
    from schemaorg_types.SalePrice import SalePrice
    from schemaorg_types.SatireOrParodyContent import SatireOrParodyContent
    from schemaorg_types.SatiricalArticle import SatiricalArticle
    from schemaorg_types.Saturday import Saturday
    from schemaorg_types.Schedule import Schedule
    from schemaorg_types.ScheduleAction import ScheduleAction
    from schemaorg_types.ScholarlyArticle import ScholarlyArticle
    from schemaorg_types.School import School
    from schemaorg_types.SchoolDistrict import SchoolDistrict
    from schemaorg_types.ScreeningEvent import ScreeningEvent
    from schemaorg_types.ScreeningHealthAspect import ScreeningHealthAspect
    from schemaorg_types.Sculpture import Sculpture
    from schemaorg_types.SeaBodyOfWater import SeaBodyOfWater
    from schemaorg_types.SearchAction import SearchAction
    from schemaorg_types.SearchRescueOrganization import SearchRescueOrganization
    from schemaorg_types.SearchResultsPage import SearchResultsPage
    from schemaorg_types.Season import Season
    from schemaorg_types.Seat import Seat
    from schemaorg_types.SeatingMap import SeatingMap
    from schemaorg_types.SeeDoctorHealthAspect import SeeDoctorHealthAspect
    from schemaorg_types.SeekToAction import SeekToAction
    from schemaorg_types.SelfCareHealthAspect import SelfCareHealthAspect
    from schemaorg_types.SelfStorage import SelfStorage
    from schemaorg_types.SellAction import SellAction
    from schemaorg_types.SendAction import SendAction
    from schemaorg_types.Series import Series
    from schemaorg_types.Service import Service
    from schemaorg_types.ServiceChannel import ServiceChannel
    from schemaorg_types.SexualContentConsideration import SexualContentConsideration
    from schemaorg_types.ShareAction import ShareAction
    from schemaorg_types.SheetMusic import SheetMusic
    from schemaorg_types.ShippingDeliveryTime import ShippingDeliveryTime
    from schemaorg_types.ShippingRateSettings import ShippingRateSettings
    from schemaorg_types.ShoeStore import ShoeStore
    from schemaorg_types.ShoppingCenter import ShoppingCenter
    from schemaorg_types.ShortStory import ShortStory
    from schemaorg_types.SideEffectsHealthAspect import SideEffectsHealthAspect
    from schemaorg_types.SingleBlindedTrial import SingleBlindedTrial
    from schemaorg_types.SingleCenterTrial import SingleCenterTrial
    from schemaorg_types.SingleFamilyResidence import SingleFamilyResidence
    from schemaorg_types.SinglePlayer import SinglePlayer
    from schemaorg_types.SingleRelease import SingleRelease
    from schemaorg_types.SiteNavigationElement import SiteNavigationElement
    from schemaorg_types.SizeGroupEnumeration import SizeGroupEnumeration
    from schemaorg_types.SizeSpecification import SizeSpecification
    from schemaorg_types.SizeSystemEnumeration import SizeSystemEnumeration
    from schemaorg_types.SizeSystemImperial import SizeSystemImperial
    from schemaorg_types.SizeSystemMetric import SizeSystemMetric
    from schemaorg_types.Skin import Skin
    from schemaorg_types.SkiResort import SkiResort
    from schemaorg_types.SocialEvent import SocialEvent
    from schemaorg_types.SocialMediaPosting import SocialMediaPosting
    from schemaorg_types.SoftwareApplication import SoftwareApplication
    from schemaorg_types.SoftwareSourceCode import SoftwareSourceCode
    from schemaorg_types.SoldOut import SoldOut
    from schemaorg_types.SolveMathAction import SolveMathAction
    from schemaorg_types.SomeProducts import SomeProducts
    from schemaorg_types.SoundtrackAlbum import SoundtrackAlbum
    from schemaorg_types.SpeakableSpecification import SpeakableSpecification
    from schemaorg_types.SpecialAnnouncement import SpecialAnnouncement
    from schemaorg_types.Specialty import Specialty
    from schemaorg_types.SpeechPathology import SpeechPathology
    from schemaorg_types.SpokenWordAlbum import SpokenWordAlbum
    from schemaorg_types.SportingGoodsStore import SportingGoodsStore
    from schemaorg_types.SportsActivityLocation import SportsActivityLocation
    from schemaorg_types.SportsClub import SportsClub
    from schemaorg_types.SportsEvent import SportsEvent
    from schemaorg_types.SportsOrganization import SportsOrganization
    from schemaorg_types.SportsTeam import SportsTeam
    from schemaorg_types.SpreadsheetDigitalDocument import SpreadsheetDigitalDocument
    from schemaorg_types.SRP import SRP
    from schemaorg_types.StadiumOrArena import StadiumOrArena
    from schemaorg_types.StagedContent import StagedContent
    from schemaorg_types.StagesHealthAspect import StagesHealthAspect
    from schemaorg_types.State import State
    from schemaorg_types.Statement import Statement
    from schemaorg_types.StatisticalPopulation import StatisticalPopulation
    from schemaorg_types.StatusEnumeration import StatusEnumeration
    from schemaorg_types.SteeringPositionValue import SteeringPositionValue
    from schemaorg_types.Store import Store
    from schemaorg_types.StoreCreditRefund import StoreCreditRefund
    from schemaorg_types.StrengthTraining import StrengthTraining
    from schemaorg_types.StructuredValue import StructuredValue
    from schemaorg_types.StudioAlbum import StudioAlbum
    from schemaorg_types.SubscribeAction import SubscribeAction
    from schemaorg_types.Subscription import Subscription
    from schemaorg_types.Substance import Substance
    from schemaorg_types.SubwayStation import SubwayStation
    from schemaorg_types.Suite import Suite
    from schemaorg_types.Sunday import Sunday
    from schemaorg_types.SuperficialAnatomy import SuperficialAnatomy
    from schemaorg_types.Surgical import Surgical
    from schemaorg_types.SurgicalProcedure import SurgicalProcedure
    from schemaorg_types.SuspendAction import SuspendAction
    from schemaorg_types.Suspended import Suspended
    from schemaorg_types.SymptomsHealthAspect import SymptomsHealthAspect
    from schemaorg_types.Synagogue import Synagogue
    from schemaorg_types.Table import Table
    from schemaorg_types.TakeAction import TakeAction
    from schemaorg_types.TattooParlor import TattooParlor
    from schemaorg_types.Taxi import Taxi
    from schemaorg_types.TaxiReservation import TaxiReservation
    from schemaorg_types.TaxiService import TaxiService
    from schemaorg_types.TaxiStand import TaxiStand
    from schemaorg_types.TaxiVehicleUsage import TaxiVehicleUsage
    from schemaorg_types.Taxon import Taxon
    from schemaorg_types.TechArticle import TechArticle
    from schemaorg_types.TelevisionChannel import TelevisionChannel
    from schemaorg_types.TelevisionStation import TelevisionStation
    from schemaorg_types.TennisComplex import TennisComplex
    from schemaorg_types.Terminated import Terminated
    from schemaorg_types.Text import Text
    from schemaorg_types.TextDigitalDocument import TextDigitalDocument
    from schemaorg_types.TheaterEvent import TheaterEvent
    from schemaorg_types.TheaterGroup import TheaterGroup
    from schemaorg_types.Therapeutic import Therapeutic
    from schemaorg_types.TherapeuticProcedure import TherapeuticProcedure
    from schemaorg_types.Thesis import Thesis
    from schemaorg_types.Thing import Thing
    from schemaorg_types.Throat import Throat
    from schemaorg_types.Thursday import Thursday
    from schemaorg_types.Ticket import Ticket
    from schemaorg_types.TieAction import TieAction
    from schemaorg_types.Time import Time
    from schemaorg_types.TipAction import TipAction
    from schemaorg_types.TireShop import TireShop
    from schemaorg_types.TobaccoNicotineConsideration import (
        TobaccoNicotineConsideration,
    )
    from schemaorg_types.TollFree import TollFree
    from schemaorg_types.TouristAttraction import TouristAttraction
    from schemaorg_types.TouristDestination import TouristDestination
    from schemaorg_types.TouristInformationCenter import TouristInformationCenter
    from schemaorg_types.TouristTrip import TouristTrip
    from schemaorg_types.Toxicologic import Toxicologic
    from schemaorg_types.ToyStore import ToyStore
    from schemaorg_types.TrackAction import TrackAction
    from schemaorg_types.TradeAction import TradeAction
    from schemaorg_types.TraditionalChinese import TraditionalChinese
    from schemaorg_types.TrainReservation import TrainReservation
    from schemaorg_types.TrainStation import TrainStation
    from schemaorg_types.TrainTrip import TrainTrip
    from schemaorg_types.TransferAction import TransferAction
    from schemaorg_types.TransformedContent import TransformedContent
    from schemaorg_types.TransitMap import TransitMap
    from schemaorg_types.TravelAction import TravelAction
    from schemaorg_types.TravelAgency import TravelAgency
    from schemaorg_types.TreatmentIndication import TreatmentIndication
    from schemaorg_types.TreatmentsHealthAspect import TreatmentsHealthAspect
    from schemaorg_types.Trip import Trip
    from schemaorg_types.TripleBlindedTrial import TripleBlindedTrial
    from schemaorg_types.True_ import True_
    from schemaorg_types.Tuesday import Tuesday
    from schemaorg_types.TVClip import TVClip
    from schemaorg_types.TVEpisode import TVEpisode
    from schemaorg_types.TVSeason import TVSeason
    from schemaorg_types.TVSeries import TVSeries
    from schemaorg_types.TypeAndQuantityNode import TypeAndQuantityNode
    from schemaorg_types.TypesHealthAspect import TypesHealthAspect
    from schemaorg_types.UKNonprofitType import UKNonprofitType
    from schemaorg_types.UKTrust import UKTrust
    from schemaorg_types.Ultrasound import Ultrasound
    from schemaorg_types.UnclassifiedAdultConsideration import (
        UnclassifiedAdultConsideration,
    )
    from schemaorg_types.UnemploymentSupport import UnemploymentSupport
    from schemaorg_types.UnincorporatedAssociationCharity import (
        UnincorporatedAssociationCharity,
    )
    from schemaorg_types.UnitPriceSpecification import UnitPriceSpecification
    from schemaorg_types.UnofficialLegalValue import UnofficialLegalValue
    from schemaorg_types.UnRegisterAction import UnRegisterAction
    from schemaorg_types.UpdateAction import UpdateAction
    from schemaorg_types.URL import URL
    from schemaorg_types.Urologic import Urologic
    from schemaorg_types.UsageOrScheduleHealthAspect import UsageOrScheduleHealthAspect
    from schemaorg_types.UseAction import UseAction
    from schemaorg_types.UsedCondition import UsedCondition
    from schemaorg_types.UserBlocks import UserBlocks
    from schemaorg_types.UserCheckins import UserCheckins
    from schemaorg_types.UserComments import UserComments
    from schemaorg_types.UserDownloads import UserDownloads
    from schemaorg_types.UserInteraction import UserInteraction
    from schemaorg_types.UserLikes import UserLikes
    from schemaorg_types.UserPageVisits import UserPageVisits
    from schemaorg_types.UserPlays import UserPlays
    from schemaorg_types.UserPlusOnes import UserPlusOnes
    from schemaorg_types.UserReview import UserReview
    from schemaorg_types.UserTweets import UserTweets
    from schemaorg_types.USNonprofitType import USNonprofitType
    from schemaorg_types.VeganDiet import VeganDiet
    from schemaorg_types.VegetarianDiet import VegetarianDiet
    from schemaorg_types.Vehicle import Vehicle
    from schemaorg_types.Vein import Vein
    from schemaorg_types.VenueMap import VenueMap
    from schemaorg_types.Vessel import Vessel
    from schemaorg_types.VeterinaryCare import VeterinaryCare
    from schemaorg_types.VideoGallery import VideoGallery
    from schemaorg_types.VideoGame import VideoGame
    from schemaorg_types.VideoGameClip import VideoGameClip
    from schemaorg_types.VideoGameSeries import VideoGameSeries
    from schemaorg_types.VideoObject import VideoObject
    from schemaorg_types.VideoObjectSnapshot import VideoObjectSnapshot
    from schemaorg_types.ViewAction import ViewAction
    from schemaorg_types.VinylFormat import VinylFormat
    from schemaorg_types.ViolenceConsideration import ViolenceConsideration
    from schemaorg_types.VirtualLocation import VirtualLocation
    from schemaorg_types.Virus import Virus
    from schemaorg_types.VisualArtsEvent import VisualArtsEvent
    from schemaorg_types.VisualArtwork import VisualArtwork
    from schemaorg_types.VitalSign import VitalSign
    from schemaorg_types.Volcano import Volcano
    from schemaorg_types.VoteAction import VoteAction
    from schemaorg_types.WantAction import WantAction
    from schemaorg_types.WarrantyPromise import WarrantyPromise
    from schemaorg_types.WarrantyScope import WarrantyScope
    from schemaorg_types.WatchAction import WatchAction
    from schemaorg_types.Waterfall import Waterfall
    from schemaorg_types.WeaponConsideration import WeaponConsideration
    from schemaorg_types.WearableMeasurementBack import WearableMeasurementBack
    from schemaorg_types.WearableMeasurementChestOrBust import (
        WearableMeasurementChestOrBust,
    )
    from schemaorg_types.WearableMeasurementCollar import WearableMeasurementCollar
    from schemaorg_types.WearableMeasurementCup import WearableMeasurementCup
    from schemaorg_types.WearableMeasurementHeight import WearableMeasurementHeight
    from schemaorg_types.WearableMeasurementHips import WearableMeasurementHips
    from schemaorg_types.WearableMeasurementInseam import WearableMeasurementInseam
    from schemaorg_types.WearableMeasurementLength import WearableMeasurementLength
    from schemaorg_types.WearableMeasurementOutsideLeg import (
        WearableMeasurementOutsideLeg,
    )
    from schemaorg_types.WearableMeasurementSleeve import WearableMeasurementSleeve
    from schemaorg_types.WearableMeasurementTypeEnumeration import (
        WearableMeasurementTypeEnumeration,
    )
    from schemaorg_types.WearableMeasurementWaist import WearableMeasurementWaist
    from schemaorg_types.WearableMeasurementWidth import WearableMeasurementWidth
    from schemaorg_types.WearableSizeGroupBig import WearableSizeGroupBig
    from schemaorg_types.WearableSizeGroupBoys import WearableSizeGroupBoys
    from schemaorg_types.WearableSizeGroupEnumeration import (
        WearableSizeGroupEnumeration,
    )
    from schemaorg_types.WearableSizeGroupExtraShort import WearableSizeGroupExtraShort
    from schemaorg_types.WearableSizeGroupExtraTall import WearableSizeGroupExtraTall
    from schemaorg_types.WearableSizeGroupGirls import WearableSizeGroupGirls
    from schemaorg_types.WearableSizeGroupHusky import WearableSizeGroupHusky
    from schemaorg_types.WearableSizeGroupInfants import WearableSizeGroupInfants
    from schemaorg_types.WearableSizeGroupJuniors import WearableSizeGroupJuniors
    from schemaorg_types.WearableSizeGroupMaternity import WearableSizeGroupMaternity
    from schemaorg_types.WearableSizeGroupMens import WearableSizeGroupMens
    from schemaorg_types.WearableSizeGroupMisses import WearableSizeGroupMisses
    from schemaorg_types.WearableSizeGroupPetite import WearableSizeGroupPetite
    from schemaorg_types.WearableSizeGroupPlus import WearableSizeGroupPlus
    from schemaorg_types.WearableSizeGroupRegular import WearableSizeGroupRegular
    from schemaorg_types.WearableSizeGroupShort import WearableSizeGroupShort
    from schemaorg_types.WearableSizeGroupTall import WearableSizeGroupTall
    from schemaorg_types.WearableSizeGroupWomens import WearableSizeGroupWomens
    from schemaorg_types.WearableSizeSystemAU import WearableSizeSystemAU
    from schemaorg_types.WearableSizeSystemBR import WearableSizeSystemBR
    from schemaorg_types.WearableSizeSystemCN import WearableSizeSystemCN
    from schemaorg_types.WearableSizeSystemContinental import (
        WearableSizeSystemContinental,
    )
    from schemaorg_types.WearableSizeSystemDE import WearableSizeSystemDE
    from schemaorg_types.WearableSizeSystemEN13402 import WearableSizeSystemEN13402
    from schemaorg_types.WearableSizeSystemEnumeration import (
        WearableSizeSystemEnumeration,
    )
    from schemaorg_types.WearableSizeSystemEurope import WearableSizeSystemEurope
    from schemaorg_types.WearableSizeSystemFR import WearableSizeSystemFR
    from schemaorg_types.WearableSizeSystemGS1 import WearableSizeSystemGS1
    from schemaorg_types.WearableSizeSystemIT import WearableSizeSystemIT
    from schemaorg_types.WearableSizeSystemJP import WearableSizeSystemJP
    from schemaorg_types.WearableSizeSystemMX import WearableSizeSystemMX
    from schemaorg_types.WearableSizeSystemUK import WearableSizeSystemUK
    from schemaorg_types.WearableSizeSystemUS import WearableSizeSystemUS
    from schemaorg_types.WearAction import WearAction
    from schemaorg_types.WebAPI import WebAPI
    from schemaorg_types.WebApplication import WebApplication
    from schemaorg_types.WebContent import WebContent
    from schemaorg_types.WebPage import WebPage
    from schemaorg_types.WebPageElement import WebPageElement
    from schemaorg_types.WebSite import WebSite
    from schemaorg_types.Wednesday import Wednesday
    from schemaorg_types.WesternConventional import WesternConventional
    from schemaorg_types.Wholesale import Wholesale
    from schemaorg_types.WholesaleStore import WholesaleStore
    from schemaorg_types.WinAction import WinAction
    from schemaorg_types.Winery import Winery
    from schemaorg_types.Withdrawn import Withdrawn
    from schemaorg_types.WorkBasedProgram import WorkBasedProgram
    from schemaorg_types.WorkersUnion import WorkersUnion
    from schemaorg_types.WPAdBlock import WPAdBlock
    from schemaorg_types.WPFooter import WPFooter
    from schemaorg_types.WPHeader import WPHeader
    from schemaorg_types.WPSideBar import WPSideBar
    from schemaorg_types.WriteAction import WriteAction
    from schemaorg_types.WritePermission import WritePermission
    from schemaorg_types.XPathType import XPathType
    from schemaorg_types.XRay import XRay
    from schemaorg_types.ZoneBoardingPolicy import ZoneBoardingPolicy
    from schemaorg_types.Zoo import Zoo


def run_all():
    import_test()


if __name__ == "__main__":
    run_all()
