[tool.poetry]
name = "usepy"
version = "0.1.0"
description = "usepy"
authors = ["miclon <jcnd@163.com>"]
packages = [
    { include = 'usepy', from = 'src'}
]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
