# Primary information needed for devops.
primary:
  repository_name: dls-mainiac
  package_name: dls_mainiac_lib
  one_line_description: "Convenient Python helper classes for cli Main programs."
  author:
    name: David Erb
    email: david.erb@diamond.ac.uk
  project_urls:
    GitLab: https://gitlab.diamond.ac.uk/kbp43231
  project_scripts:
    dls-mainiac: "dls_mainiac_lib.__main__:main"
  dependencies:
    - type: pypi
      list:
        - dls-utilpack
        - dls-logformatter
        - prettytable
        - psutil
        - setproctitle
