[tool.poetry]
name = "cpunk_mongo"
version = "0.5.0"
description = ""
authors = ["matfonseca <mfonseca@fi.uba.ar>"]

[tool.poetry.dependencies]
python = "^3.7"
pymongo = "^4.3.3"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
mongomock = "^4.1.2"
pydantic = "^1.10.2"
coverage = "^6.5.0"
coveralls = "^3.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
