# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/fluent/v0/batch_ops.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ansys/api/fluent/v0/batch_ops.proto',
  package='ansys.api.fluent.v0',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#ansys/api/fluent/v0/batch_ops.proto\x12\x13\x61nsys.api.fluent.v0\"X\n\x0e\x45xecuteRequest\x12\x0f\n\x07package\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x14\n\x0crequest_body\x18\x04 \x01(\x0c\"\\\n\x0f\x45xecuteResponse\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".ansys.api.fluent.v0.ExecuteStatus\x12\x15\n\rresponse_body\x18\x02 \x01(\x0c*\x93\x01\n\rExecuteStatus\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x01\x12\x16\n\x12STATUS_UNSUPPORTED\x10\x02\x12\x15\n\x11STATUS_SUCCESSFUL\x10\x03\x12\x11\n\rSTATUS_FAILED\x10\x04\x12\x14\n\x10STATUS_CANCELLED\x10\x05\x32\x64\n\x08\x42\x61tchOps\x12X\n\x07\x45xecute\x12#.ansys.api.fluent.v0.ExecuteRequest\x1a$.ansys.api.fluent.v0.ExecuteResponse(\x01\x30\x01\x62\x06proto3')
)

_EXECUTESTATUS = _descriptor.EnumDescriptor(
  name='ExecuteStatus',
  full_name='ansys.api.fluent.v0.ExecuteStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_UNKNOWN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_UNSUPPORTED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_SUCCESSFUL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_FAILED', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_CANCELLED', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=245,
  serialized_end=392,
)
_sym_db.RegisterEnumDescriptor(_EXECUTESTATUS)

ExecuteStatus = enum_type_wrapper.EnumTypeWrapper(_EXECUTESTATUS)
STATUS_UNSPECIFIED = 0
STATUS_UNKNOWN = 1
STATUS_UNSUPPORTED = 2
STATUS_SUCCESSFUL = 3
STATUS_FAILED = 4
STATUS_CANCELLED = 5



_EXECUTEREQUEST = _descriptor.Descriptor(
  name='ExecuteRequest',
  full_name='ansys.api.fluent.v0.ExecuteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package', full_name='ansys.api.fluent.v0.ExecuteRequest.package', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='ansys.api.fluent.v0.ExecuteRequest.service', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='ansys.api.fluent.v0.ExecuteRequest.method', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_body', full_name='ansys.api.fluent.v0.ExecuteRequest.request_body', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=148,
)


_EXECUTERESPONSE = _descriptor.Descriptor(
  name='ExecuteResponse',
  full_name='ansys.api.fluent.v0.ExecuteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ansys.api.fluent.v0.ExecuteResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_body', full_name='ansys.api.fluent.v0.ExecuteResponse.response_body', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=242,
)

_EXECUTERESPONSE.fields_by_name['status'].enum_type = _EXECUTESTATUS
DESCRIPTOR.message_types_by_name['ExecuteRequest'] = _EXECUTEREQUEST
DESCRIPTOR.message_types_by_name['ExecuteResponse'] = _EXECUTERESPONSE
DESCRIPTOR.enum_types_by_name['ExecuteStatus'] = _EXECUTESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExecuteRequest = _reflection.GeneratedProtocolMessageType('ExecuteRequest', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTEREQUEST,
  __module__ = 'ansys.api.fluent.v0.batch_ops_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.fluent.v0.ExecuteRequest)
  ))
_sym_db.RegisterMessage(ExecuteRequest)

ExecuteResponse = _reflection.GeneratedProtocolMessageType('ExecuteResponse', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTERESPONSE,
  __module__ = 'ansys.api.fluent.v0.batch_ops_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.fluent.v0.ExecuteResponse)
  ))
_sym_db.RegisterMessage(ExecuteResponse)



_BATCHOPS = _descriptor.ServiceDescriptor(
  name='BatchOps',
  full_name='ansys.api.fluent.v0.BatchOps',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=394,
  serialized_end=494,
  methods=[
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='ansys.api.fluent.v0.BatchOps.Execute',
    index=0,
    containing_service=None,
    input_type=_EXECUTEREQUEST,
    output_type=_EXECUTERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BATCHOPS)

DESCRIPTOR.services_by_name['BatchOps'] = _BATCHOPS

# @@protoc_insertion_point(module_scope)
