# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ansys.api.fluent.v0 import events_pb2 as ansys_dot_api_dot_fluent_dot_v0_dot_events__pb2


class EventsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BeginStreaming = channel.unary_stream(
        '/grpcRemoting.Events/BeginStreaming',
        request_serializer=ansys_dot_api_dot_fluent_dot_v0_dot_events__pb2.BeginStreamingRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_fluent_dot_v0_dot_events__pb2.BeginStreamingResponse.FromString,
        )


class EventsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def BeginStreaming(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EventsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BeginStreaming': grpc.unary_stream_rpc_method_handler(
          servicer.BeginStreaming,
          request_deserializer=ansys_dot_api_dot_fluent_dot_v0_dot_events__pb2.BeginStreamingRequest.FromString,
          response_serializer=ansys_dot_api_dot_fluent_dot_v0_dot_events__pb2.BeginStreamingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpcRemoting.Events', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
