# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ansys.api.fluent.v0 import monitor_pb2 as ansys_dot_api_dot_fluent_dot_v0_dot_monitor__pb2


class MonitorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMonitors = channel.unary_unary(
        '/grpcRemoting.Monitor/GetMonitors',
        request_serializer=ansys_dot_api_dot_fluent_dot_v0_dot_monitor__pb2.GetMonitorsRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_fluent_dot_v0_dot_monitor__pb2.GetMonitorsResponse.FromString,
        )
    self.BeginStreaming = channel.unary_stream(
        '/grpcRemoting.Monitor/BeginStreaming',
        request_serializer=ansys_dot_api_dot_fluent_dot_v0_dot_monitor__pb2.StreamingRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_fluent_dot_v0_dot_monitor__pb2.StreamingResponse.FromString,
        )


class MonitorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetMonitors(self, request, context):
    """Get monitors info i.e. monitors name and their properties e.g. x-label, y-label, title etc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BeginStreaming(self, request, context):
    """Begin monitors data streaming i.e. monitors x-values and corresponding y-values.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MonitorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMonitors': grpc.unary_unary_rpc_method_handler(
          servicer.GetMonitors,
          request_deserializer=ansys_dot_api_dot_fluent_dot_v0_dot_monitor__pb2.GetMonitorsRequest.FromString,
          response_serializer=ansys_dot_api_dot_fluent_dot_v0_dot_monitor__pb2.GetMonitorsResponse.SerializeToString,
      ),
      'BeginStreaming': grpc.unary_stream_rpc_method_handler(
          servicer.BeginStreaming,
          request_deserializer=ansys_dot_api_dot_fluent_dot_v0_dot_monitor__pb2.StreamingRequest.FromString,
          response_serializer=ansys_dot_api_dot_fluent_dot_v0_dot_monitor__pb2.StreamingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpcRemoting.Monitor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
