[tool.poetry]
name = "pydantic-aioredis"
version = "1.2.2"
description = "Use your pydantic models as an ORM, storing data in Redis."
authors = ["Andrew Herrington <andrew.the.techie@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/andrewthetechie/pydantic-aioredis"
repository = "https://github.com/andrewthetechie/pydantic-aioredis"
documentation = "https://pydantic-aioredis.readthedocs.io/en/latest/"
classifiers = [
	"Development Status :: 4 - Beta",
	"Intended Audience :: Developers",
	"License :: OSI Approved :: MIT License",
	"Programming Language :: Python",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.7",
	"Programming Language :: Python :: 3.8",
	"Programming Language :: Python :: 3.9",
	"Programming Language :: Python :: 3.10",
	"Framework :: AsyncIO"
]

[tool.poetry.urls]
Changelog = "https://github.com/andrewthetechie/pydantic-aioredis/releases"

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.10.2"
redis = "^4.4.0"
anyio = "^3.6.2"
nest-asyncio = "^1.5.6"
fastapi = {version = "^0.91.0", optional = true}
fastapi-crudrouter = {version = "^0.8.6", optional = true}

[tool.poetry.extras]
FastAPI= ['fastapi']
fastapi-crudrouter=['fastapi-crudrouter']


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
coverage = {extras = ["toml"], version = "^6.5"}
safety = "^2.3.1"
mypy = "^0.991"
typeguard = "^2.13.2"
xdoctest = {extras = ["colors"], version = "^1.1.0"}
sphinx = "^4.3.2"
sphinx-autobuild = ">=2021.3.14"
pre-commit = ">=2.12.1"
flake8 = "^5.0.0"
black = ">=21.10b0"
flake8-bugbear = ">=21.9.2"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.3.0"
pep8-naming = "^0.13.2"
darglint = "^1.8.1"
reorder-python-imports = "^3.9.0"
pre-commit-hooks = "^4.2.0"
Pygments = "^2.13.0"
pyupgrade = "^3.3.1"
furo = ">=2021.11.12"
pytest-cov = "^4.0.0"
types-croniter = "^1.3.2"
pytest_async = "^0.1.1"
pytest-asyncio = "^0.20.1"
pytest-mock = "^3.10.0"
pytest-lazy-fixture = "^0.6.3"
fastapi = ">=0.6.3"
fastapi-crudrouter = ">=0.8.4"
httpx = "^0.23.0"
pytest-env = "^0.8.1"
pytest-mockservers = "^0.6.0"
pytest-xdist = "^3.1.0"
tox = "^3.27.0"
pylint = "^2.13.9"
setuptools-git-versioning = "^1.13.1"
bandit = "^1.7.4"
fakeredis = {extras = ["json"], version = "2.2.0"}
hypothesis = "^6.61.0"
pytest-rerunfailures = "^11.1"

[tool.coverage.paths]
source = ["pydantic_aioredis", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["pydantic_aioredis"]

[tool.coverage.report]
show_missing = true
fail_under = 98

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
dirty = true

[tool.poetry-dynamic-versioning.substitution]
files = ["pydantic_aioredis/__init__.py"]

[tool.pytest.ini_options]
addopts = "-n 4 --ignore examples --cov=pydantic_aioredis --cov-report=term-missing --cov-fail-under 82"

[tool.bandit]
exclude= "tests/ examples/*"

[pylint.MASTER]
extension-pkg-whitelist="pydantic"
suggestion-mode="yes"

[pylint.'MESSAGES CONTROL']
disable="R0903,R0801"
