[tool.poetry]
authors = ["Chris Gregory <christopher.b.gregory@gmail.com>"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
]
description = "Hamming-LUCB algorithm implementation"
keywords = [
  "hlucb",
  "hamming",
  "lucb",
  "approximate",
  "ranking",
  "pairwise",
  "comparisons",
]
license = "Apache Software License"
name = "hlucb"
readme = "README.md"
repository = "https://github.com/gregorybchris/hlucb"
version = "0.1.4"

[tool.poetry.dependencies]
python = ">=3.8.1"
numpy = "^1.24.2"

[tool.poetry.dev-dependencies]
flake8 = "^6.0.0"
mypy = "^1.0.0"
pylint = "^2.16.1"
pyproject-flake8 = "^6.0.0"
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pytest-forked = "^1.5.0"
pytest-xdist = "^3.2.0"
yapf = "^0.32.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.flake8]
ignore = ""           # Required to disable default ignores
max-line-length = 119

[tool.mypy]
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
ignore_missing_imports = true
plugins = ["numpy.typing.mypy_plugin"]

[tool.pylint.basic]
good-names = [
  "b1",
  "b2",
  "d1",
  "d2",
  "h",
  "i",
  "j",
  "k",
  "n",
  "o",
  "s",
  "u",
  "w",
  "xs",
  "T",
]
max-locals = 25
max-args = 7
notes = ["FIXME"]

[tool.pylint.format]
max-line-length = 119

[tool.pylint.messages_control]
disable = [
  "logging-fstring-interpolation", # W1203
  "unspecified-encoding",          # W1514
  "missing-docstring",             # C0114, C0115, C0116
  "wrong-import-order",            # C0411
  "duplicate-code",                # R0801
  "too-few-public-methods",        # R0903
]

[tool.yapf]
based_on_style = "pep8"
column_limit = 119
indent_width = 4
