// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: tensorflow/core/data/service/worker.proto

#include "tensorflow/core/data/service/worker.pb.h"
#include "tensorflow/core/data/service/worker.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace tensorflow {
namespace data {

class MockWorkerServiceStub : public WorkerService::StubInterface {
 public:
  MOCK_METHOD3(ProcessTask, ::grpc::Status(::grpc::ClientContext* context, const ::tensorflow::data::ProcessTaskRequest& request, ::tensorflow::data::ProcessTaskResponse* response));
  MOCK_METHOD3(AsyncProcessTaskRaw, ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::data::ProcessTaskResponse>*(::grpc::ClientContext* context, const ::tensorflow::data::ProcessTaskRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncProcessTaskRaw, ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::data::ProcessTaskResponse>*(::grpc::ClientContext* context, const ::tensorflow::data::ProcessTaskRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(GetElement, ::grpc::Status(::grpc::ClientContext* context, const ::tensorflow::data::GetElementRequest& request, ::tensorflow::data::GetElementResponse* response));
  MOCK_METHOD3(AsyncGetElementRaw, ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::data::GetElementResponse>*(::grpc::ClientContext* context, const ::tensorflow::data::GetElementRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetElementRaw, ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::data::GetElementResponse>*(::grpc::ClientContext* context, const ::tensorflow::data::GetElementRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(GetWorkerTasks, ::grpc::Status(::grpc::ClientContext* context, const ::tensorflow::data::GetWorkerTasksRequest& request, ::tensorflow::data::GetWorkerTasksResponse* response));
  MOCK_METHOD3(AsyncGetWorkerTasksRaw, ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::data::GetWorkerTasksResponse>*(::grpc::ClientContext* context, const ::tensorflow::data::GetWorkerTasksRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncGetWorkerTasksRaw, ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::data::GetWorkerTasksResponse>*(::grpc::ClientContext* context, const ::tensorflow::data::GetWorkerTasksRequest& request, ::grpc::CompletionQueue* cq));
};

} // namespace tensorflow
} // namespace data

