
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-13T13:47:49+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d27ad35b538e454a40b234452d720f1200778ad",
 "version": "0.16.3.post8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
