[tool.poetry]
name = "snypr-cli"
version = "0.1.1"
description = "A simple tool for converting Sigma detection rules to SNYPR Spotter queries."
authors = ["Securonix Threat Labs"]
repository = "https://github.com/Securonix/SigmaToSnypr"

packages = [
    { include = "omega" }
]


[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
pysigma = "^0.6.5"
sigmatools = "^0.21.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
snypr-cli = "omega.cli.main:main"

