[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hubrdvmairie"
version = "2.8.0"
description = "API de la plateforme de recherche de rendez-vous mairies"
readme = "README.md"
authors = [{ name = "ANTS", email = "ants-rdvmairie@interieur.gouv.fr" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["rendez-vous", "mairie", "proxy", "pré-demande", "passeport", "CNI"]
dependencies = [
    "asyncio >= 3.4.3",
    "fastapi >= 0.79.0",
    "fastapi-utils >= 0.2.1",
    "geopy >= 2.2.0",
    "pydantic >= 1.9.1",
    "python-dotenv >= 0.20.0",
    "requests >= 2.28.1",
    "requests-async >= 0.6.2",
    "uvicorn >= 0.18.2",
    "websockets >= 10.3",
    "pytest-mock >= 3.8.2"
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["black", "flake8", "isort", "autoflake", "bandit", "pytest", "pytest-asyncio", "pytest-mock", "pytest-cov", "coverage"]

[project.urls]
documentation = "https://rendez-vous-api.france-identite.fr/docs"
repository = "https://gitlab.com/france-identite/rendez-vous-mairie"