[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[project]
authors = [
  {name = "Alef Bruno Delpino de Oliveira", email = "alef@gmail.com"},
]
classifiers = [
  "Environment :: Console",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
description = "Base codes for creating python modules"
keywords = ["base", "template", "lib"]
license = {file = "LICENSE"}
name = "delpinos-base"
readme = "README.md"
requires-python = ">=3.6"
version = "0.0.1.dev3"

[project.urls]
"Bug Tracker" = "https://github.com/delpinos/python-base/issues"
"Homepage" = "https://github.com/delpinos/python-base"
