[tool.poetry]
name = "lcdp-postgres-utils"
# https://github.com/python-poetry/poetry/issues/1208
version = "1.0.4.dev35"
description = "Postgres Utils to create users, databases, functions, ..."
authors = ["Le Comptoir Des Pharmacies <webmaster@lecomptoirdespharmacies.fr>"]

[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
style = "pep440"
format-jinja = "{% if distance == 0 %}{{ base }}{% else %}{{ base }}.dev{{ distance }}{% endif %}"
bump = true

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.26.55"
pg8000 = "^1.29.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.1.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"