
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-09T10:41:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "748bccdf3b4c9772eb3f7c94344a3278ff3a0f82",
 "version": "v23.02.00"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
