[tool.poetry]
name = "numeral-converter"
version = "0.0.2"
description = ""
authors = [ "Tetiana Lytvynenko <lytvynenkotv@gmail.com>", "Denis Shchutskyi <denisshchutskyi@gmail.com>"]
readme = "README.md"
packages = [{include = "numeral_converter"}]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.5.3"
semiotic-tricks-data-loader = "^0.0.1"
fuzzy-multi-dict = "^0.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
