name: rheology
channels:
  - conda-forge
  - defaults
dependencies:
  - appmode
  - ipympl
  - lmfit
  - matplotlib
  - numpy
  - xlrd
  - pandas
  - pybroom
  - seaborn
  - jupyter_contrib_nbextensions
  - pivottablejs
  - pybroom
  - pymongo
  - jupyter_contrib_nbextensions
  - voila
  - pip:
    - ipyupload
    - xmltodict
    - emcee
    - corner
