[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "Dolar_BC"
version = "1.1.3"
authors = [
  { name="JOAO LUCAS CARVALHO", email="joao.carvalho43@fatec.sp.gov.br" },
]
description = "This script has as its objective to offer a pack of functions to work with Dollar, so it can be easily imported into your projects."
readme = "README.md"
readme-url = "https://github.com/Joaolpridolficarvalho/Dolar-BC/edit/main/README.md"
requires-python = ">=3.7"
dependencies = [
    "beautifulsoup4==4.11.1",
    "requests==2.28.1"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Natural Language :: English"
]
keywords = ["dolar", "USD", "BC", "BRL"]
[project.urls]
"Homepage" = "https://github.com/Joaolpridolficarvalho/Dolar-BC"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"