storage:
  cls: remote
  url: http://moma.internal.softwareheritage.org:5002

search:
  cls: remote
  url: http://moma.internal.softwareheritage.org:5010

debug: yes

introspection: yes

max_query_cost:
  anonymous: 500

