[project]
name = "mlargparser"
version = "0.8"
authors = [
  { name="Jared Sutton", email="jpsutton@gmail.com" },
]
description = "A multi-Level argument parser library for writing CLI-based applications"
readme = "README.md"
requires-python = ">=3.3"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Lesser General Public License v2 (LGPLv2)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/jpsutton/mlargparser"
"Bug Tracker" = "https://github.com/jpsutton/mlargparser/issues"
