from typing import List, Optional

class JsonFile:
    def __init__(self, path) -> None: ...
    @property
    def contents(self): ...
    def exists(self): ...
    def load(self): ...

class AppFile(JsonFile):
    def __init__(self) -> None: ...
    @property
    def analytics_cfg(self): ...
    @property
    def qa_images_cfg(self): ...
    @property
    def model_id_list(self): ...

class ProjectFile(JsonFile):
    def __init__(self) -> None: ...
    @property
    def project_id(self): ...

class AppConfig:
    def __init__(self) -> None: ...
    @property
    def model_id_list(self) -> List[str]: ...
    @property
    def analytics_cfg(self) -> Optional[dict]: ...
    @property
    def qa_images_cfg(self) -> Optional[dict]: ...
    @property
    def project_id(self) -> str: ...
