import multiprocessing.queues
from ._utils import MultiprocessingCircularQueue as MultiprocessingCircularQueue
from .edge_tools import convert_to_jpg as convert_to_jpg, resize as resize
from _typeshed import Incomplete
from collections.abc import Generator

class MjpgVideoWriter:
    def __init__(self, queue_depth: int = ..., port: int = ..., max_image_width: int = ..., max_image_height: int = ..., jpg_quality: int = ..., **kwargs) -> None: ...
    def start(self): ...
    def write_frame(self, frame) -> None: ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type, value, traceback) -> None: ...
    def __del__(self) -> None: ...

def gen_video_feed() -> Generator[Incomplete, None, None]: ...
def video(): ...

class _ServerProcess(multiprocessing.Process):
    def __init__(self, ipaddr, port, tx_queue, max_image_width, max_image_height, jpg_quality, error_queue, *args, **kwargs) -> None: ...
    def run(self) -> None: ...
