[project]
name = "pyconfrdemo"
description = "Demo package for PyConFR 2023 demo"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
version = "v0.0.11"

[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''
