[project]
name = "EOtool"
version = "0.0.2"
authors = [
  { name="정준호", email="01068552679j@gmail.com" },
]
description = "A small package for using some tools"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://pypi.org/project/EOtool/0.0.2/#description"