[package]
name = "flatten-serde-json"
version = "1.0.0"
edition = "2021"
description = "Flatten serde-json objects like elastic search"
readme = "README.md"
publish = false

[dependencies]
serde_json = "1.0"

[[bench]]
name = "benchmarks"
harness = false
