[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "calculatorGS"
version = "0.2"
authors = [
  { name="Gediminas Sumskis" },
]
description = "A calculator package which performs basic operations."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]