[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "chatbot_webraft"
version = "0.0.6"
license = {file="LICENSE"}
keywords = ["chatbot", "bot","chat bot", "webraft", "chatter", "chatgpt","chatbotwebraft","chat bot library"]
authors = [
  { name="Webraft", email="team@webraft.in" },
]
description = "A package for building chatbots easily without needing of any high system resources."
readme = "README.md"
requires-python = ">=3.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
"nltk"
]




