[virtualenvs]
path="/home/dennisl/miniconda3/envs/tknlp/bin/python"
create=false
in-project=false


[tool.poetry]
name = "tknlp"
version = "0.1.6"
description = ""
authors = ["dennislblog <dennisl@udel.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
optuna = "^3.0.5"
FastNLP = "1.0.1"
cloudpickle = "2.2.0"
hydra-core = "1.2.0"
fitlog = "0.9.15"
scipy = "1.8.1"
pandas = "1.5.1"
transformers = "4.25.1"
scikit-learn = "1.1.3"
python-dotenv = "0.19.2"
torchmetrics = "^0.11.0"
sentence-transformers = "2.2.2"
numpy = "1.23.5"
ipython = "8.7.0"
emoji = "1.7.0"
ftfy = "6.1.1"
pyspellchecker = "0.7.0"
Unidecode = "^1.3.6"
lemminflect = "^0.2.3"
contractions = "^0.1.73"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
