[project]
name = "damagescanner"
dynamic = ["version"]
authors = [
    {name = "Elco Koks", email = "elco.koks@vu.nl"},
]

license = {text = "MIT License"}
description = "Direct damage assessments for natural disasters"
keywords = ["GIS", "natural_hazards", "geopandas"]
classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Topic :: Scientific/Engineering :: GIS",
        "Topic :: Utilities",
    ]
requires-python = ">=3.8"
dependencies = [
    "geopandas >= 0.12.2",
    "matplotlib >= 3.0",	
    "numpy >= 1.20",
    "pyproj >= 3.0",
    "rasterio >= 1.2.6",
    "xarray >= 0.19.0",
    "rioxarray >= 0.7.1",
    "packaging",
    "pandas >= 1.4.0",
    "shapely >= 2.0",
]

[project.readme]
text = """\
A python toolkit for direct damage assessments for natural disasters. Even though the method is initially developed for flood damage assessments, it can calculate damages for any hazard for which you just require a vulnerability curve (i.e. a one-dimensional relation).
"""
content-type = "text/x-rst"
