default_language_version:
    python: python

repos:

- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: 'v9.3.0'
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black

- repo: https://github.com/myint/autoflake
  rev: 'v2.0.0'
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports']
      # args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
    - id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.991'  # Use the sha / tag you want to point at
  hooks:
  - id: mypy
    files: "^src/"
    pass_filenames: true
    args: ["--config-file", "setup.cfg", "--ignore-missing-imports", "--explicit-package-bases"]
    additional_dependencies: [pydantic>=1.8.0, rich>=10.0.0, ruamel.yaml, sqlalchemy-stubs, types-python-slugify, types-setuptools, types-python-dateutil]

- repo: https://github.com/Kludex/no-optional
  rev: 0.3.1
  hooks:
    - id: no_optional

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.3.0'
  hooks:
  - id: trailing-whitespace
    exclude: 'setup.cfg'
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
    exclude: 'tests/\*'
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: '.*.json'
  - id: requirements-txt-fixer
  - id: fix-encoding-pragma
  - id: mixed-line-ending
    args: ['--fix=no']
  #- id: no-commit-to-branch
  #  args: [--branch, master]
