[build-system]
requires = [
    "setuptools>=63",
    "setuptools_scm[toml]>7.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "kiara_plugin.network_analysis"
description = "kiara modules and datatypes for network analysis."
authors = [
    {name = "Markus Binsteiner", email = "markus@frkl.io"}
]
readme = "README.md"
requires-python = ">=3.8"
keywords = ["kiara"]
license = {text = "MPL-2.0"}
classifiers = [
    "Framework :: Django",
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11"
]
dependencies = [
    "kiara-plugin.tabular>=0.4.22"
]
dynamic = ["version"]

[project.optional-dependencies]
dev_documentation = [
    "kiara[dev_documentation]"
]
dev_testing = [
    "kiara[dev_testing]",
    "types-setuptools",
    "sqlalchemy-stubs"
]
dev_utils = [
    "kiara[dev_utils]"
]
dev_all = [
    "kiara[dev_all]"
]

[project.entry-points."kiara.plugin"]
network_analysis = "kiara_plugin.network_analysis"

[project.entry-points."kiara.data_types"]
network_analysis = "kiara_plugin.network_analysis:find_data_types"

[project.entry-points."kiara.model_classes"]
network_analysis = "kiara_plugin.network_analysis:find_model_classes"

[project.entry-points."kiara.modules"]
network_analysis = "kiara_plugin.network_analysis:find_modules"

[project.entry-points."kiara.pipelines"]
network_analysis = "kiara_plugin.network_analysis:find_pipelines"


[project.urls]
homepage = "https://github.com/DHARPA-Project/kiara_plugin.network_analysis"
documentation = "https://DHARPA-Project.github.io/kiara_plugin.network_analysis"
repository = "https://github.com/DHARPA-Project/kiara_plugin.network_analysis"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | external
)/
'''

[tool.setuptools_scm]
write_to = "src/kiara_plugin/network_analysis/version.txt"
