
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-11T13:10:12-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a5ddc775844a95bd014edf3c9412c4e10b9ce762",
 "version": "0.3.0.post0.dev31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
