[tool.poetry]
name = "jommerce"
version = "0.1.0.post"
description = ""
authors = ["githashem <PersonalHashem@gmail.com>"]
packages = [
    {include = "djplus"},
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
