from .credentials import CLIENT_ID as CLIENT_ID, CREDENTIALS_EXIST as CREDENTIALS_EXIST, ENDPOINT as ENDPOINT, PATH_TO_CERT as PATH_TO_CERT, PATH_TO_KEY as PATH_TO_KEY, PATH_TO_ROOT as PATH_TO_ROOT
from _typeshed import Incomplete
from typing import Callable

class ConnectionError(Exception): ...
class PublishError(Exception): ...

class IoTCoreConnection:
    AT_LEAST_ONCE: Incomplete
    AT_MOST_ONCE: Incomplete
    def __new__(cls): ...
    mqtt_connection: Incomplete
    def __init__(self) -> None: ...
    def connect(self) -> None: ...
    def subscribe(self, topic: str, callback: Callable): ...
    def publish(self, message: str, topic: str): ...
    def disconnect(self) -> None: ...
