
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-10T02:49:23-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f95cf97e9b75169859628f1da07f9fc8b5076ac",
 "version": "4.9.65"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
