[tool.poetry]
name = "fortressofsolitude"
version = "0.1.0"
description = "A client to retrieve new releases of comic books, filterable by publisher and format."
authors = ["Aaron Steed <asteed7@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.28.1"
beautifulsoup4 = "4.11.1"
pyyaml = "^6.0"

[tool.poetry.group.dev.dependencies]
pyflakes = "^3.0.1"
pylama = "^8.4.1"
Sphinx = "^6.1.3"
sphinxawesome-theme = "^3.3.7"
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
