[tool.poetry]
name = "nonebot_plugin_maimai"
version = "0.0.8"
description= "Maimai DX plugin for NoneBot"
authors = ["Agnes_Digital <Z735803792@163.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Umamusume-Agnes-Digital/nonebot_plugin_maimai"
repository = "https://github.com/Umamusume-Agnes-Digital/nonebot_plugin_maimai"
keywords = ["maimai", "nonebot2", "plugin"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",

]
include = [
    "LICENSE","README.md"
]
 
[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.8.1"
nonebot2 = "^2.0.0rc1"
nonebot-adapter-onebot = ">=2.1.3"
pillow = ">=8.3.0"
httpx = ">=0.23.0"
 
[tool.poetry.dev-dependencies]
 
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"