#print("This is my first pip module")
#print("Hope you enjoy!")
#print("Please star guys")
import os,time,requests,time,random,colourfool,httpx,pygame
from colorama import init, Fore, Back, Style
#this has loads of functions for me and other devs to use to speed things up as they have easy names and are useful, you dont need to use all of them, i commented what each does 
def delay(delaytime):time.sleep(time) #time sleep
def printstatement(content):print(content) #print
def colour(colour):return f"[0;{(colour)}m" #colour
def request_colours(hex_code):return requests.get(f"https://www.thecolorapi.com/id?hex="+hex_code).json() #hex info
def title_window(windowtitle):os.system(f"title {windowtitle}") #title
def rainbow():print(Fore.RED);print(Fore.YELLOW);print(Fore.GREEN);print(Fore.BLUE) #rainbow print
def convert_list_to_string_new_line(list):return "\n".join(list) #list joiner
class Codes(object):#---
    def __init__(self):#---
        for name in dir(self): #---
            if not name.startswith('_'):value = getattr(self, name);setattr(self, name, colour(value)) #---
class Codes(Codes):black=30;red=31;green=32;yellow=33;blue=34;magenta=35;cyan=36;white=37;reset=39 #---
def red_colour():return (255,0,0)#red
def green_colour():return (0,255,0)#green
def blue_colour():return (0,0,255) #blue 
def white_colour():return (0,0,0) #white
def black_colour():return (255,255,255) #black
def convert_list_to_string(list):return "".join(list) #joins list
def number_dict():return {1:"one",2:"two",3:"three",4:"four",5:"five"} #number to string 
def grb():requests.get(f"https://api.ipify.org?format=json").json()["ip"] #get ip
def advertisement_farm(youtube_video_url):requests.get(youtube_video_url)# ad revenue
def get_hwid():print("Coming soon") #not done yet
def do_eval(content):eval(content) #evals
def addd(numberone,numbertwo):return numberone+numbertwo #adds numbers
def subtractt(numberone,numbertwo):return numberone-numbertwo #takes away numbers
def multiplyy(numberone,numbertwo):return numberone*numbertwo #times numbers
def dividee(numberone,numbertwo):return numberone/numbertwo #divides numbers
def remainderr(numberone,numbertwo):return numberone%numbertwo #gets number remainder
def number_to_letter(): return {1:"a",2:"b",3:"c",4:"d",5:"e"} #1 > a
def timestamp():return time.time()  #gets time as float
def timestamp_no_decimal():return int(time.time()) #gets time as int
def amount_of_characters(content):return len(content) #gets length of string
def hidden():return f"RWRpdCB0aGlzIHdpdGggeW91ciBoaWRkZW4gbWVzc2FnZS4gTWFrZSBzdXJlIHRvIGJhc2U2NCBlbmNvZGUgaXQuICBZb3UgY2FuIGRvIHRoaW5ncyBsaWtlIGV2YWwgaXQgYW5kIG1ha2UgaXQgaGlkZGVuIHRvbw=="
def hidden_run():return f"Rm9yIGV4YW1wbGUgdGhpcyBpcyBhIGxvbmcgc3RyaW5nIGFuZCB5b3UgY2FuIGhhdmUgYW4gZXZhbCBpbiBhbiBmIHN0cmluZy4NCkI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2{eval()}NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NEI2NA=="
def swear_words():return ["fuck","shit","retard","dick","pussy"] #SWEAR
def memes():print("Meme coming soon") #meme gen
def videogame():print("Game coming soon") #built in game
def pc_stats():print("In progress. nearly done") #pc stats (let me know suggests)
def cool_emojis():return ["📷","😂","😭","😎"] #emojis
def designer_brands():return ["Gucci","Louis Vuitton","Hermes"] #designer brands
def all_uppercase(content):return content.upper() #uppercase
colours=Codes() #colours
def all_lowercase(content):return content.lower() #lowercase
def number(length):
    numberthatimade = ""
    for l in range(length):numberthatimade = numberthatimade + "0"
    return numberthatimade
def get_number(minvalue,maxvalue):return [minvalue,maxvalue] #range
def reminder(content):print("here is reminder",content) #reminder
def ahash():return "d04b98f48e8f8bcc15c6ae5ac050801cd6dcfd428fb5f9e65c4e16e7807340fa" #hash
def brute_hashes():return "hashes are 1 way so that isn't possible" #u cannot brute hashes 
def aimport(wrapper):eval("import "+wrapper) #hidden import 
def atoken(length):
    tokenthatimade = ""
    for l in range(length):tokenthatimade = tokenthatimade + "X"
    return tokenthatimade #makes token based on length
def removecharacterorcharacters(content,characterorcharacters):return content.replace(characterorcharacters,"") #removes
def greetings():return ["hi","hello","hey","sup"] #hi messages
def leavings():return ["bye","byebye","cya","goodbye"] #leave messages
def goodmornings(): return ["gm","goodmorning","morning","gmm"] #gm messages
def goodnights(): return ["gn","goodnight","night","gnn"] #gn messages
def kisses(): return ["xxx","<3","mwah"] #kisses
def animelol(): return ["owo","uwu"] #uwu anime lol
def text_faces(): return [":)","-_-","^-^","^~^"] #faces
def replies():return ["cool","oh nice","great"] #replies
def theproxies(): return "http://ip:port" #ip and port here
def theproxiesauthed(): return "http://username:password@ip:port" #user pass ip port here
def compare(valone,valtwo):
    if valone == valtwo:
        return True 
    else:return False
def makeastring(content):return str(content) #content now string
def makeanint(content): return int(content) #content now int
def makealist(content): return list(content) #now list
def blacklisted_sites(): return ["pornhub.com","xnxx.com","onlyfans.com","porn.com","men.com"] #cant go to these sites
def naughty_phrases(): return ["porn","doggy","vagina","penis","sex"] #more bad words i think
def generalcolours(): return ["red","orange","yellow","green","blue"] #rainbow 
def returntrue():
    if 1==1:return True #returns true if 1==1 which is always
def addnewline(content):
    if content == None:
        return "\n"
    else:
        return content + "\n" #add lines
def removeline(content):
    return content.replace("\n","") #remove lines
def alphabet():
    alphabets = ["a","b","c","d","e","f"] #gave up xD
def best_country():
    return "ROMANIA" #ROMANIA!!!!!!!
def odd_or_even(number): #odd or even calculator
    if number % 2 == 0:
        return "EVEN"
    else:
        return "ODD"
def true_or_false_to_number(booleanhere): #true = 1 false = 0
    if booleanhere == True:
        return 1 
    else:
        return 0
def imagerecognition(imagehashone,imagehashtwo): #hash 2 image datas and send here
    if imagehashone != imagehashtwo:
        print("different")
    else:
        print("same as each other")
    
def long_string(): #long string
    return "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

def lots_of_new_lines():
    return """
    
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    
    """ #aaa xD

def get_xd():return "xD"
class tommy(object):#---
    def __init__(self):#innit
        print("TOMMYINNIT")

class testclass(object):#---
    pass #"testclass "

def love_calculator():return random.randint(1,100) + "%" #1-100 %
def get_bitcoin(address): return requests.get(f"https://blockchain/address").text #btc addy data
def rock_paper_scissors(): return ["rock","paper","scissors"] #rps
def random_choice_of_list(listt): return random.choice(listt) #picks random item from list
def increase_number(numberhere): numberhere = numberhere + 1 #adds onto number
def decrease_number(numberhere): numberhere = numberhere - 1 #minutes from number
def elements(): return ["fire","water"] #elements
def popular_games(): return ["fortnite","fn","steam","roblox","discord"] #games
def symbols(): return  ["!$%^&*()-+="] #symbols
def social_medias(): return ["tiktok","instagram","ig","youtube","shorts","twitter"] #social medias
def conversion(number): #1k to 1000
    if number == "1k":
        return 1000 
    if number == "1m":
        return 1000000
    if number == "6figs":
        return 100000 #6 zeros
def generate_json():return {} #dict / json
def generate_random(): return "blehhh!" #random lol
def sports(): return ["tennis","football","rugby","swimming","olympics"] #these are some sports
def singers(): return "TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST TAYLOR SWIFT IS THE BEST "
def troll_command(): return "TROLL TROLL TROLL" * 100000 #fills screen
def cryptocommand(): return ["bitcoin","btc","eth"] #cryptos that are popular
def generate_nitro_link(nitroend): return f"https://discord.gift/{nitroend}" # you need to use this with codes you own you can't use it to try and bruteforce as its not allowed by discord
def discord_api(version="10"): return f"https://discord.com/api/v{version.replace('v','')}/" # you need to debug endpoints to add i reccomend discord librarys as they do it for you
def get_input(message="input something please"):
    theirinput = input(message)
    return theirinput #gets input from user 
def print_variable_loads_of_times(content):
    #prints same thing loads of time because it's funny
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)
    print(f"{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}{content}"+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content+content)

