[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "t5html"
version = "23.06.2"
description = "Converts text to html. Text muste be in t5html form."
readme = "doc/ReadMe.md"
requires-python = ">=3.8"
keywords = ["web", "html", "html5", "template", "templating"]
authors = [
  { name="splendor", email="splendor@tuta.io" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Topic :: Text Processing :: Markup :: HTML",
]


[project.urls]
Homepage = "https://github.com/Exsplendor/t5html"
"Bug Tracker" = "https://github.com/Exsplendor/t5html/issues"


[project.scripts]
t5html = "t5html.__main__:start"


[tool.hatch.build.targets.wheel]
inlcude = [
	"src/data",
	"doc/manpage",
]
[tool.hatch.build.targets.sdist]
exclude = [
	"/.github",
	"/.gitignore",
	"/meta",
]


[tool.pytest.ini_options]
pythonpath = [ "src", ]
testpaths = [ "test", ] 
