
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-14T08:58:06-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "790d6848d81dd3cab75e149c902d4f34dec11f70",
 "version": "0.3.0.post0.dev45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
