[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "postgresdave_package"
version = "1.0.7"
authors = [
  { name="Dave Skura", email="dskura@gmail.com" },
]
description = "A wrapper for simplified Postgres usage using psycopg2."
readme = "README.md"
dependences = ["psycopg2"]
requires-python = ">=3.7"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/daveskura/postgresdave"
"Author Linkedin" = "https://www.linkedin.com/in/2166883"
