
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-13T11:35:03-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e71948e15f51d699a4ae099c4c3827224a93cda7",
 "version": "0.3.0.post0.dev37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
