
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-10T12:51:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d8a8ef6e287e3b869db73645258e0ffb4cd5e9c",
 "version": "1.18.2.post0.dev52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
