[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vensible"
version = "0.0.0"
authors = [
  { name="Kristian Heljas", email="kristian@kristian.ee" },
]
description = "Placeholder for an upcoming project"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
]