[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "camelsnake"
version = "0.0.2"
authors = [
  { name="Ankit Chandawala", email="ankitchandawala@gmail.com" },
]
description = "camelsnake is a Python library for converting between camel case and snake case strings"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/nerandell/camelsnake"
"Bug Tracker" = "https://github.com/nerandell/camelsnake/issues"