---
ontology_remaps:

  survival_status:
    search_fields:
      - info.survival_status
    class_patterns:
      - id: "EFO:0030041"
        label: "alive (follow-up status)"
        pattern: "^alive$"
      - id: "EFO:0030049"
        label: "dead (follow-up status)"
        pattern: "^dea(?:d|th)$"

  pathological_tnm_findings:
    search_fields:
      - info.tumor_tnm_text
    class_patterns:
      - id: "NCIT:C48699"
        label: "M0 Stage Finding"
        pattern: "^.*?T0[^abcd]*?$"
      - id: "NCIT:C95956"
        label: "cM0 (i+) Stage Finding"
        pattern: "^.*?cM0.*?$"
      - id: "NCIT:C48701"
        label: "M1a Stage Finding"
        pattern: "^.*?M1a.*?$"
      - id: "NCIT:C48702"
        label: "M1b Stage Finding"
        pattern: "^.*?M1b.*?$"
      - id: "NCIT:C48703"
        label: "M1c Stage Finding"
        pattern: "^.*?M1c.*?$"
      - id: "NCIT:C48700"
        label: "M1 Stage Finding"
        pattern: "^.*?M1[^abcd]*?$"
      - id: "NCIT:C48704"
        label: "MX Stage Finding"
        pattern: "^.*?MX[^abcd]*?$"
      - id: "NCIT:C48705"
        label: "N0 Stage Finding"
        pattern: "^.*?N0[^abcd]*?$"
      - id: "NCIT:C48706"
        label: "N1 Stage Finding"
        pattern: "^.*?N1[^abciI]*?$"
      - id: "NCIT:C48707"
        label: "N1a Stage Finding"
        pattern: "^.*?N1a.*?$"
      - id: "NCIT:C48708"
        label: "N1b Stage Finding"
        pattern: "^.*?N1b[^I]*?$"
      - id: "NCIT:C95929"
        label: "N1bI Stage Finding"
        pattern: "^.*?N1bI[^IV]*?$"
      - id: "NCIT:C95935"
        label: "N1bII Stage Finding"
        pattern: "^.*?N1bII[^I]*?$"
      - id: "NCIT:C95936"
        label: "N1bIII Stage Finding"
        pattern: "^.*?N1bIII.*?$"
      - id: "NCIT:C95937"
        label: "N1bIV Stage Finding"
        pattern: "^.*?N1bIV.*?$"
      - id: "NCIT:C48709"
        label: "N1c Stage Finding"
        pattern: "^.*?N1c.*?$"
      - id: "NCIT:C95955"
        label: "N1mi Stage Finding"
        pattern: "^.*?N1mi.*?$"
      - id: "NCIT:C48786"
        label: "N2 Stage Finding"
        pattern: "^.*?N2[^abciI]*?$"
      - id: "NCIT:C48711"
        label: "N2a Stage Finding"
        pattern: "^.*?N2a.*?$"
      - id: "NCIT:C48712"
        label: "N2b Stage Finding"
        pattern: "^.*?N2b.*?$"
      - id: "NCIT:C48713"
        label: "N2c Stage Finding"
        pattern: "^.*?N2c.*?$"
      - id: "NCIT:C48714"
        label: "N3 Stage Finding"
        pattern: "^.*?N1[^abciI]*?$"
      - id: "NCIT:C48715"
        label: "N3a Stage Finding"
        pattern: "^.*?N3a.*?$"
      - id: "NCIT:C48716"
        label: "N3b Stage Finding"
        pattern: "^.*?N3b.*?$"
      - id: "NCIT:C48717"
        label: "N3c Stage Finding"
        pattern: "^.*?N3c.*?$"
      - id: "NCIT:C48718"
        label: "NX Stage Finding"
        pattern: "^.*?NX.*?$"
      - id: "NCIT:C96026"
        label: "N4 Stage Finding"
        pattern: "^.*?N4.*?$"
      - id: "NCIT:C132010"
        label: "T5 Stage Finding"
        pattern: "^.*?T5.*?$"
      - id: "NCIT:C48719"
        label: "T0 Stage Finding"
        pattern: "^.*?T0.*?$"
      - id: "NCIT:C48720"
        label: "T1 Stage Finding"
        pattern: "^.*?T1[^abcdi]*?$"
      - id: "NCIT:C48721"
        label: "T1a Stage Finding"
        pattern: "^.*?T1a.*?$"
      - id: "NCIT:C48722"
        label: "T1b Stage Finding"
        pattern: "^.*?T1b.*?$"
      - id: "NCIT:C48723"
        label: "T1c Stage Finding"
        pattern: "^.*?T1c.*?$"
      - id: "NCIT:C95805"
        label: "T1b Stage Finding"
        pattern: "^.*?T1mi.*?$"
      - id: "NCIT:C48724"
        label: "T2 Stage Finding"
        pattern: "^.*?T2[^abcdi]*?$"
      - id: "NCIT:C48725"
        label: "T2a Stage Finding"
        pattern: "^.*?T2a.*?$"
      - id: "NCIT:C48726"
        label: "T2b Stage Finding"
        pattern: "^.*?T2b.*?$"
      - id: "NCIT:C48727"
        label: "T2c Stage Finding"
        pattern: "^.*?T2c.*?$"
      - id: "NCIT:C148411"
        label: "T2d Stage Finding"
        pattern: "^.*?T2d.*?$"
      - id: "NCIT:C48728"
        label: "T3 Stage Finding"
        pattern: "^.*?T3[^abcd]*?$"
      - id: "NCIT:C48729"
        label: "T3a Stage Finding"
        pattern: "^.*?T3a.*?$"
      - id: "NCIT:C48730"
        label: "T3b Stage Finding"
        pattern: "^.*?T3b.*?$"
      - id: "NCIT:C48731"
        label: "T3c Stage Finding"
        pattern: "^.*?T3c.*?$"
      - id: "NCIT:C148412"
        label: "T3d Stage Finding"
        pattern: "^.*?T3d.*?$"
      - id: "NCIT:C48732"
        label: "T4 Stage Finding"
        pattern: "^.*?T4[^abcd]*?$"
      - id: "NCIT:C48733"
        label: "T2a Stage Finding"
        pattern: "^.*?T2a.*?$"
      - id: "NCIT:C48734"
        label: "T4b Stage Finding"
        pattern: "^.*?T4b.*?$"
      - id: "NCIT:C48735"
        label: "T4c Stage Finding"
        pattern: "^.*?T4c.*?$"
      - id: "NCIT:C48736"
        label: "T4d Stage Finding"
        pattern: "^.*?T4d.*?$"
      - id: "NCIT:C48737"
        label: "TX Stage Finding"
        pattern: "^.*?TX.*?$"
      - id: "NCIT:C48738"
        label: "Tis Stage Finding"
        pattern: "^.*?Tis.*?$"
      - id: "NCIT:C96025"
        label: "Ta Stage Finding"
        pattern: "^.*?Ta.*?$"

  pathological_stage:
    search_fields:
      - info.tumor_stage_text
    class_patterns:
      - id: "NCIT:C27966"
        label: "Stage I"
        pattern: "^i[^iabcd]*?$"
      - id: "NCIT:C27975"
        label: "Stage Ia"
        pattern: "^ia[^i1234]*?$"
      - id: "NCIT:C27966"
        label: "Stage Ia3"
        pattern: "^ia3[^i]*?$"
      - id: "NCIT:C279836"
        label: "Stage Ia1"
        pattern: "^ia1[^i]*?$"
      - id: "NCIT:C27984"
        label: "Stage Ia2"
        pattern: "^ia2[^i]*?$"
      - id: "NCIT:C27976"
        label: "Stage Ib"
        pattern: "^ib[^i1234]*?$"
      - id: "NCIT:C28052"
        label: "Stage Ib1"
        pattern: "^ib1[^i]*?$"
      - id: "NCIT:C28053"
        label: "Stage Ib2"
        pattern: "^ib2[^i]*?$"
      - id: "NCIT:C28053"
        label: "Stage Ic"
        pattern: "^ic[^i1234]*?$"   
      - id: "NCIT:C27970"
        label: "Stage III"
        pattern: "^iii[^iabcd]*?$"
      - id: "NCIT:C137676"
        label: "Stage IIID"
        pattern: "^iiid[^iabc]*?$"
      - id: "NCIT:C27977"
        label: "Stage IIIa"
        pattern: "^iiia[^123ibcd]*?$"
      - id: "NCIT:C139980"
        label: "Stage IIIa1"
        pattern: "^iiia1[^23ibcd]*?$"
      - id: "NCIT:C139981"
        label: "Stage IIIa2"
        pattern: "^iiia2[^13ibcd]*?$"
      - id: "NCIT:C27978"
        label: "Stage IIIb"
        pattern: "^iiib[^123ibcd]*?$"  
      - id: "NCIT:C27982"
        label: "Stage IIIc"
        pattern: "^iiic[^123iabd]*?$"    
      - id: "NCIT:C95179"
        label: "Stage IIIc1"
        pattern: "^iiic1[^23iabd]*?$"  
      - id: "NCIT:C95180"
        label: "Stage IIIc2"
        pattern: "^iiic2[^13iabd]*?$" 
      - id: "NCIT:C27971"
        label: "Stage IV"
        pattern: "^iv[^123isabcd]*?$"  
      - id: "NCIT:C27972"
        label: "Stage IVS"
        pattern: "^ivs[^123iabcd]*?$"   
      - id: "NCIT:C27979"
        label: "Stage IVa"
        pattern: "^iva[^123isbcd]*?$"  
      - id: "NCIT:C141344"
        label: "Stage IVa1"
        pattern: "^iva1[^23isbcd]*?$"  
      - id: "NCIT:C141345"
        label: "Stage IVa2"
        pattern: "^iva2[^13isbcd]*?$"  
      - id: "NCIT:C27980"
        label: "Stage IVb"
        pattern: "^ivb[^123isacd]*?$"   
      - id: "NCIT:C28055"
        label: "Stage IVc"
        pattern: "^ivc[^123isbad]*?$"  
      - id: "NCIT:C27973"
        label: "Stage V"
        pattern: "^v[^123isabcd]*?$"  
      - id: "NCIT:C28051"
        label: "Stage 0"
        pattern: "^0[^123isabcd]*?$"    
      - id: "NCIT:C27964"
        label: "Stage 0a"
        pattern: "^0a[^123isbcd]*?$"  
      - id: "NCIT:C27965"
        label: "Stage 0is"
        pattern: "^0is[^123isabcd]*?$"   
      - id: "NCIT:C28054"
        label: "Stage II"
        pattern: "^ii[^123isabcd]*?$"  
      - id: "NCIT:C27967"
        label: "Stage IIa"
        pattern: "^iia[^123isabcd]*?$"   
      - id: "NCIT:C95177"
        label: "Stage IIa1"
        pattern: "^iia1[^23isabcd]*?$"   
      - id: "NCIT:C95178"
        label: "Stage IIa2"
        pattern: "^iia2[^123isabcd]*?$"   
      - id: "NCIT:C95178"
        label: "Stage IIa2"
        pattern: "^iia2[^123isabcd]*?$"  
      - id: "NCIT:C27968"
        label: "Stage IIb"
        pattern: "^iib[^123isabcd]*?$"
      - id: "NCIT:C27969"
        label: "Stage IIc"
        pattern: "^iic[^123isabcd]*?$"  
      - id: "NCIT:C95177"
        label: "Stage IIa1"
        pattern: "^iia1[^123isabcd]*?$"
      - id: "NCIT:C95178"
        label: "Stage IIa2"
        pattern: "^iia2[^123isabcd]*?$"
      - id: "NCIT:C134971"
        label: "AIDS-Related Kaposi Sarcoma T0 (Good Risk): Localized Tumor"
        pattern: "l*?$"
      - id: "NCIT:C28285"
        label: "Stage Is"
        pattern: "^is[^123isabcd]*?$"
      - id: "NCIT:C28056"
        label: "Stage A"
        pattern: "^a[^123isabcd]*?$"
       
