[tool.poetry]
name = "ververser"
version = "0.1.1"
description = ""
authors = ["Berry <berryvansomeren@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pyglet = "^2.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

packages = [
    { include = "ververser" }
]