[tool.poetry]
name = "kardiasclean"
version = "0.3.3"
description = "Medical Records Normalizer"
authors = ["AlbertoV5 <58243333+AlbertoV5@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include="kardiasclean", from="src"}]
repository = "https://github.com/AlbertoV5/kardiasclean"
documentation = "https://albertov5.github.io/kardiasclean"


[tool.poetry.dependencies]
python = "^3.7.6,<3.11"
pandas = "^1.3.5"
phonetics = "^1.0.5"
nltk = "^3.7"
numpy = "^1.21.6"


[tool.poetry.group.dev.dependencies]
ipykernel = "6.16.2"
matplotlib = "3.5.2"
black = "^22.10.0"
pytest = "^7.2.0"
sqlalchemy = "^1.4.44"
sphinx = "^5.3.0"
furo = "^2022.9.29"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)s] (%(filename)s:%(lineno)s): %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_file = "tests/tests.log"
log_file_level = "DEBUG"
log_file_format = "%(asctime)s [%(levelname)s] (%(filename)s:%(lineno)s): %(message)s"
log_file_date_format = "%Y-%m-%d %H:%M:%S"