# https://toml.io/en/v1.0.0
# https://peps.python.org/pep-0518/
# https://peps.python.org/pep-0621/
# https://flit.pypa.io/en/latest/

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "puf"
version = "0.0.2"
authors = [
  { name="Sokrato", email="dlutxx@gmail.com" },
]
description = "Python Utility Functions"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "requests"
]

[project.optional-dependencies]
dev = [
    "black"
]

[project.urls]
"Homepage" = "https://github.com/sokrato/puf"
"Bug Tracker" = "https://github.com/sokrato/puf/issues"

[project.scripts]
to-html = "puf.to_html:main"
