[tool.poetry]
name = "iolanta"
version = "0.1.2"
description = "Semantic Web browser"
authors = ["Anatoly Scherbakov <altaisoft@gmail.com>"]
license = "MIT"
readme = "README.md"

packages = [
  { include = "ldflex" },
  { include = "iolanta" },
  { include = "iolanta_record" },
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
rdflib = "^6.2.0"
python-frontmatter = "^0.5.0"
requests = "^2.25.1"
deepmerge = "^0.1.1"
documented = "^0.1.1"
urlpath = "^1.1.7"
typer = "^0.7.0"
classes = "^0.4.0"
PyLD = "^2.0.3"
dominate = "^2.6.0"
more-itertools = "^9.0.0"
owlrl = "^6.0.2"
funcy = "^1.17"
lambdas = "^0.1.0"
rich = "^13.3.1"

[tool.poetry.scripts]
iolanta = "iolanta.cli:app"


[tool.poetry.plugins."iolanta.plugins"]
record = "iolanta_record:IolantaRecord"
base = "iolanta:IolantaBase"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
