[tool.poetry]
name = "flake8-import-as-module"
version = "0.1.0"
description = "A Flake8 plugin to check if specific packages are imported as modules."
authors = ["João Palmeiro <joaopalmeiro@proton.me>"]
license = "MIT"
readme = "README.md"
keywords = ["flake8", "linter", "qa", "import", "flake8 plugin", "code quality"]
packages = [{ include = "flake8_import_as_module" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Framework :: Flake8",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Quality Assurance",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.7"
flake8 = ">=5"

[tool.poetry.plugins."flake8.extension"]
IM = "flake8_import_as_module:Plugin"

[tool.poetry.group.dev.dependencies]
mypy = "^1.0.0"
black = "^23.1.0"
pytest = "^7.2.1"
flake8-pyproject = "^1.2.2"
flake8-bandit = "^4.1.1"
flake8-pytest-style = "^1.6.0"
isort = "^5.11.5"
pytablewriter = "^0.64.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# https://flake8.pycqa.org/en/5.0.0/user/options.html#cmdoption-flake8-count
# https://flake8.pycqa.org/en/5.0.0/user/options.html#cmdoption-flake8-statistics
# https://github.com/tylerwince/flake8-bandit#configuration + https://github.com/tylerwince/flake8-bandit/issues/3
# https://github.com/tylerwince/flake8-bandit/blob/v4.1.1/flake8_bandit.py#L34
# https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html
# Even though the `.bandit` file excludes the `tests/` folder, VS Code continues to report the S101 code.
# However, when running Flake8 in the terminal (`flake8 tests/`), the error does not appear.
# To avoid this error being reported in VS Code, it is also ignored via Flake8 (the `.bandit` file could be dropped).
[tool.flake8]
max-line-length = 88
count = true
statistics = true
per-file-ignores = ["tests/test_plugin.py:S101"]

# https://pycqa.github.io/isort/docs/configuration/config_files.html#pyprojecttoml-preferred-format
# https://pycqa.github.io/isort/docs/configuration/black_compatibility.html
[tool.isort]
profile = "black"
