[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pip-change-repo"
version = "0.0.2"
authors = [
  { name="xiaojian.liang", email="wakeam@outlook.com" },
]
description = "Redirecting Base URL of the Python Package Index to Mirrors"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "inquirer"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://gitee.com/siogian/pip-change-repo"
"Bug Tracker" = "https://gitee.com/siogian/pip-change-repo/issues"
[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
pip-change-repo = "pip_change_repo._cli:main"
