[tool.poetry]
name = "ghepy"
version = "0.1.0"
description = "(Greenhouse energy-python) is a python tool for evaluation of heating demand in greenhouses when data are not provided elsewhere."
authors = ["Mehran Ahmadpour <mehran.hmdpr@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
vincent = "^0.4.4"
folium = "^0.14.0"
coolprop = "^6.4.3.post1"
numpy = "^1.24.2"
plotly = "^5.13.0"
requests = "^2.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
