# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_change_id.ipynb.

# %% auto 0
__all__ = ['foo', 'change_package_name']

# %% ../nbs/01_change_id.ipynb 3
def foo(): pass

# %% ../nbs/01_change_id.ipynb 5
import os

# %% ../nbs/01_change_id.ipynb 6
def change_package_name(path, newname, oldname = "hilmarzech"):
    
    for path, dirs, files in os.walk(path,topdown=False):
        if oldname in dirs:
            os.chdir(path)
            os.rename(oldname, newname)
            
    for path, dirs, files in os.walk(path,topdown=False):
        os.chdir(path)
        for file_name in files:
            with open(file_name,"r",encoding='utf-8',errors='ignore') as file:
                text = file.read()
            if (oldname in text) and (file_name!="local.properties"):
                text = text.replace(oldname, newname)
                with open(file_name,"w",encoding='utf-8',errors='ignore') as file:
                    file.write(text)
