[build-system]
requires = ["flit"]
build-backend = "flit_core.buildapi"

[project]
name = "phronesitron"
authors = [
    {name = "Reto Stamm", email = "phronesitron@retostamm.edu"},
]
description = "Interact with scientific papers and ML language models"
readme = "README.md"
requires-python = ">=3.9"
version = "0.1.0"
keywords = ["openai", "literature"]
license = {text = "GPL-3"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "wheel",
    "openai",
    "argparse",
    "datetime",
    "pyperclip",
    "pdfminer.six",
    "termcolor",
]

[project.urls]
Home="https://github.com/retospect/phronesitron"

[project.scripts]
#my-script = "my_package.module:function"

[tool.bumpver]
current_version = "0.1.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"src/phronesitron/__init__.py" = ["{version}"]

