[tool.poetry]
name = "pandas-object"
version = "0.1.1"
description = ""
authors = ["dwpeng <1732889554@qq.com>"]
readme = "README.md"
packages = [{include = "pandas_object"}]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.3.0"
rich = "^13.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "aliyun"
url = "http://mirrors.aliyun.com/pypi/simple"
default = true
