[package]
name = "fastxm"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fastxm"
crate-type = ["cdylib"]

[dependencies]
ahash = "0.8.3"
numpy = "0.18.0"
pyo3 = { version = "0.18.0", features = ["extension-module"] }
rayon = "1.6.1"
