[tool.poetry]
name = "easy_wrap"
version = "0.1.1"
description = ""
authors = ["Su <wxlxy316@163.com>"]
readme = "README.md"
repository = "https://github.com/bridgeL/easy_wrap"
packages = [
    { include = "easy_wrap" }
]

[tool.poetry.dependencies]
python = "^3.8"
pillow = "^9.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
