[build-system]
requires = [
    "hatchling",
    "wheel"
    ]
build-backend = "hatchling.build"

[project]
name = "Package-Ethon-setup"
version = "0.0.2"
authors = [
  { name="Rudraa", email="rudraa2213@gmail.com" },
]
description = "This Package Is Helpfull for Save Restriction Bot"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/rohitsir1999/Package-Ethon"
"Bug Tracker" = "https://github.com/rohitsir1999/Package-Ethon/issues"