
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-11T20:09:23-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9258772d0ef5b6954a4cb8143039e6b332bb769f",
 "version": "0.9.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
