[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rei-preso-plot"
version = "0.1.0"
description = "Python package for drawing graphs for presentation materials with matplotlib."
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
keywords = ["graph", "plot", "presentation", "preso"]
authors = [
    { name="NakuRei", email="nakurei7901@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
  "matplotlib",
]

[project.urls]
"Homepage" = "https://github.com/NakuRei/rei-preso-plot"
"Bug Tracker" = "https://github.com/NakuRei/rei-preso-plot/issues"
