
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-13T13:18:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "43694068ed9fe26d8ee5bf6150167c185bca2544",
 "version": "2.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
