[tool.poetry]
name = "liketunicorn"
version = "0.0.2"
description = "The runner for liketapi"
authors = ["toymaj <sermed512@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.8.3"
pydantic = "^1.10.4"
aiofiles = "^23.1.0"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "liketunicorn"
version = "0.0.2"
authors = [
    { name = "liketapi", email = "seryumed@gmail.com" }
]
description = "The runner for liketapi"
readme = "README.md"
requires-python = ">=3.6"

[project.urls]
"Homepage" = "https://github.com/liketapi/liketunicorn"
"Bug Tracker" = "https://github.com/liketapi/liketunicorn/issues"
