
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-10T19:43:48+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "66e8d71cf4035f5f4aa31e2efb13b79383a5c8c9",
 "version": "1.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
