[tool.poetry]
name = "np_logging"
version = "0.3.5"
description = "Pre-configured file, web, and email logging for Mindscope neuropixels projects, repackaging code from AIBS mpeconfig."
authors = [
    "Ben Hardcastle <ben.hardcastle@alleninstitute.org>",
    "Ross Hytnen <rossh@alleninstitute.org>", 
    "Ben Sutton <ben.sutton@alleninstitute.org>",
]
maintainers = ["Ben Hardcastle <ben.hardcastle@alleninstitute.org>"]
readme = "README.md"
include = ["configs/*"]
packages = [{include = "np_logging", from = "src"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.urls]
"Repository" = "https://github.com/alleninstitute/np_logging"
"Bug Tracker" = "https://github.com/alleninstitute/np_logging/issues"

[tool.poetry.dependencies]
python = "^3.7"
np_config = "*"
importlib_resources = ">1.4"
pip-tools = {version = "*", optional = true}
isort = {version = "*", optional = true}
mypy = {version = "*", optional = true}
black = {version = "*", optional = true}
pytest = {version = "*", optional = true}
poetry = {version = "*", optional = true}

[tool.poetry.extras]
dev = [
    "pip-tools", # convert pyproject.toml to requirements.txt
    "isort", # sort imports
    "mypy",
    "black",
    "pytest",
    "poetry",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--doctest-modules",
]

doctest_optionflags = [
    "NORMALIZE_WHITESPACE",
    "IGNORE_EXCEPTION_DETAIL",
    "ELLIPSIS",
]

testpaths = [
    "tests",
    "src",
]