
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "spat4apitesting"
version = "0.0.205"
authors = [
  { name="Jasmine-Arabella Post", email="jasmine@Jasmine-Arabella.tech" },
]
description = "Simple Python API Testing"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Persnickety-Rose/spat"
"Bug Tracker" = "https://github.com/Persnickety-Rose/spat/issues"
