
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-14T14:51:30-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd8e5b1d4143f6702a2d80adb289d646c8e19a52",
 "version": "2.6.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
