# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api.ipynb.

# %% auto 0
__all__ = ['ApiClient']

# %% ../nbs/api.ipynb 3
class ApiClient:
    "API client"
    def __init__(self, url):
        self.url = url

    def get(self, path):
        "GET request"
        return f"GET {self.url}/{path}"

    def post(self, path, data):
        "POST request"
        return f"POST {self.url}/{path} {data}"
