[tool.poetry]
name = "notas-musicais"
version = "0.1.1"
description = ""
authors = ["dunossauro <mendesxeduardo@gmail.com>"]
readme = "README.md"
packages = [{include = "notas_musicais"}]
license = "BeerWare"
classifiers = [
    "Topic :: Education",
    "Environment :: Console",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Natural Language :: Portuguese",
    "Development Status :: 5 - Production/Stable"
]

[tool.poetry.urls]
"Documentação" = "https://notas-musicais.readthedocs.io/pt/latest/"
"Repositório" = "https://github.com/dunossauro/notas-musicais"
"Bug Tracker" = "https://github.com/dunossauro/notas-musicais/issues"

[tool.poetry.scripts]
notas-musicais = "notas_musicais.cli:app"

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.7.0"
rich = "^13.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
blue = "^0.9.1"
isort = "^5.11.4"
taskipy = "^1.10.3"

[tool.poetry.group.doc.dependencies]
mkdocs-material = "^9.0.5"
mkdocstrings = "^0.19.1"
mkdocstrings-python = "^0.8.3"
mkdocs-macros-plugin = "^0.7.0"
jinja2 = "^3.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "."
addopts = "--doctest-modules"

[tool.isort]
profile = "black"
line_length = 79

[tool.taskipy.tasks]
lint = "blue --check --diff . && isort --check --diff ."
docs = "mkdocs serve"
pre_test = "task lint"
test = "pytest -s -x --cov=notas_musicais -vv"
post_test = "coverage html"