[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "enchant"
version = "0.0.1"
authors = [
  { name="Vinay Sahni", email="vinay@enchant.com" },
]
description = "Easier integration with Enchant.com"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/enchant/enchant-python"
#"Bug Tracker" = "https://github.com/enchant/enchant-python/issues"
