[tool.poetry]
name = "mysoc-dataset"
version = "0.3.0"
description = "Tool to download mySociety datasets"
authors = ["Alex Parsons <alex.parsons@mysociety.org>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/mysociety/mysoc-dataset"
repository = "https://github.com/mysociety/mysoc-dataset"
include = [
    "LICENSE.md",
]


[tool.poetry_bumpversion.file."src/mysoc_dataset/__init__.py"]

[tool.poetry.scripts]

mysoc-dataset = 'mysoc_dataset.__main__:main'

[tool.poetry.dependencies]
python = "^3.7.1"
rich = "^12.5.1"
rich-click = "^1.5.2"
pandas = [{ version = "1.3.5", python = "<3.8" }, { version = ">=1.3.5", python = ">=3.8" }]

[tool.poetry.group.dev.dependencies]
httpretty = "^1.1.4"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pylint = "^2.12.2"
black = "^22.3.0"
pyright = "^1.1"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
