
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-12T14:52:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a57e713b60758a3ff560bdea71e551ead8f9541d",
 "version": "2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
