ProdSteps:
  - ID: 1
    input_meta_query:
      parentID:
      dataset: Prod5b_LaPalma_AdvancedBaseline_NSB1x_gamma-diffuse_North_20deg_DL0
    job_config:
      type: CtapipeProcessing
      version: v0.17.0
      ctapipe_site_config: prod5b_lapalma_alpha.yml
      array_layout: Alpha
      group_size: 5
  - ID: 2
    input_meta_query:
      parentID: 1
      dataset:
    job_config:
      type: Merging
      version: v0.17.0
      group_size: 2
      options: --skip-images --skip-simu-images
      catalogs: DIRACFileCatalog, TSCatalog

Common:
  MCCampaign: Prod6Test
  configuration_id: 15
  base_path: /vo.cta.in2p3.fr/user/a/afaure/prod6/
