
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-03T16:08:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "48ee882ed1dd39497118ac232c2c192512b6af1d",
 "version": "1.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
