// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: tensorflow/core/profiler/profiler_analysis.proto
#ifndef GRPC_tensorflow_2fcore_2fprofiler_2fprofiler_5fanalysis_2eproto__INCLUDED
#define GRPC_tensorflow_2fcore_2fprofiler_2fprofiler_5fanalysis_2eproto__INCLUDED

#include "tensorflow/core/profiler/profiler_analysis.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace tensorflow {


namespace grpc {

// //////////////////////////////////////////////////////////////////////////////
// ProfileAnalysis service provide entry point for profiling TPU and for
// serving profiled data to Tensorboard through GRPC
// //////////////////////////////////////////////////////////////////////////////
class ProfileAnalysis final {
 public:
  static constexpr char const* service_full_name() {
    return "tensorflow.ProfileAnalysis";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Starts a profiling session, blocks until it completes.
    // TPUProfileAnalysis service delegate this to TPUProfiler service.
    // Populate the profiled data in repository, then return status to caller.
    virtual ::grpc::Status NewSession(::grpc::ClientContext* context, const ::tensorflow::NewProfileSessionRequest& request, ::tensorflow::NewProfileSessionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::NewProfileSessionResponse>> AsyncNewSession(::grpc::ClientContext* context, const ::tensorflow::NewProfileSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::NewProfileSessionResponse>>(AsyncNewSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::NewProfileSessionResponse>> PrepareAsyncNewSession(::grpc::ClientContext* context, const ::tensorflow::NewProfileSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::NewProfileSessionResponse>>(PrepareAsyncNewSessionRaw(context, request, cq));
    }
    // Enumerate existing sessions and return available profile tools.
    virtual ::grpc::Status EnumSessions(::grpc::ClientContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest& request, ::tensorflow::EnumProfileSessionsAndToolsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::EnumProfileSessionsAndToolsResponse>> AsyncEnumSessions(::grpc::ClientContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::EnumProfileSessionsAndToolsResponse>>(AsyncEnumSessionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::EnumProfileSessionsAndToolsResponse>> PrepareAsyncEnumSessions(::grpc::ClientContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::EnumProfileSessionsAndToolsResponse>>(PrepareAsyncEnumSessionsRaw(context, request, cq));
    }
    // Retrieve specific tool's data for specific session.
    virtual ::grpc::Status GetSessionToolData(::grpc::ClientContext* context, const ::tensorflow::ProfileSessionDataRequest& request, ::tensorflow::ProfileSessionDataResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::ProfileSessionDataResponse>> AsyncGetSessionToolData(::grpc::ClientContext* context, const ::tensorflow::ProfileSessionDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::ProfileSessionDataResponse>>(AsyncGetSessionToolDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::ProfileSessionDataResponse>> PrepareAsyncGetSessionToolData(::grpc::ClientContext* context, const ::tensorflow::ProfileSessionDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::ProfileSessionDataResponse>>(PrepareAsyncGetSessionToolDataRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Starts a profiling session, blocks until it completes.
      // TPUProfileAnalysis service delegate this to TPUProfiler service.
      // Populate the profiled data in repository, then return status to caller.
      virtual void NewSession(::grpc::ClientContext* context, const ::tensorflow::NewProfileSessionRequest* request, ::tensorflow::NewProfileSessionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void NewSession(::grpc::ClientContext* context, const ::tensorflow::NewProfileSessionRequest* request, ::tensorflow::NewProfileSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Enumerate existing sessions and return available profile tools.
      virtual void EnumSessions(::grpc::ClientContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest* request, ::tensorflow::EnumProfileSessionsAndToolsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void EnumSessions(::grpc::ClientContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest* request, ::tensorflow::EnumProfileSessionsAndToolsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Retrieve specific tool's data for specific session.
      virtual void GetSessionToolData(::grpc::ClientContext* context, const ::tensorflow::ProfileSessionDataRequest* request, ::tensorflow::ProfileSessionDataResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetSessionToolData(::grpc::ClientContext* context, const ::tensorflow::ProfileSessionDataRequest* request, ::tensorflow::ProfileSessionDataResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::NewProfileSessionResponse>* AsyncNewSessionRaw(::grpc::ClientContext* context, const ::tensorflow::NewProfileSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::NewProfileSessionResponse>* PrepareAsyncNewSessionRaw(::grpc::ClientContext* context, const ::tensorflow::NewProfileSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::EnumProfileSessionsAndToolsResponse>* AsyncEnumSessionsRaw(::grpc::ClientContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::EnumProfileSessionsAndToolsResponse>* PrepareAsyncEnumSessionsRaw(::grpc::ClientContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::ProfileSessionDataResponse>* AsyncGetSessionToolDataRaw(::grpc::ClientContext* context, const ::tensorflow::ProfileSessionDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::ProfileSessionDataResponse>* PrepareAsyncGetSessionToolDataRaw(::grpc::ClientContext* context, const ::tensorflow::ProfileSessionDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status NewSession(::grpc::ClientContext* context, const ::tensorflow::NewProfileSessionRequest& request, ::tensorflow::NewProfileSessionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::NewProfileSessionResponse>> AsyncNewSession(::grpc::ClientContext* context, const ::tensorflow::NewProfileSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::NewProfileSessionResponse>>(AsyncNewSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::NewProfileSessionResponse>> PrepareAsyncNewSession(::grpc::ClientContext* context, const ::tensorflow::NewProfileSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::NewProfileSessionResponse>>(PrepareAsyncNewSessionRaw(context, request, cq));
    }
    ::grpc::Status EnumSessions(::grpc::ClientContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest& request, ::tensorflow::EnumProfileSessionsAndToolsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::EnumProfileSessionsAndToolsResponse>> AsyncEnumSessions(::grpc::ClientContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::EnumProfileSessionsAndToolsResponse>>(AsyncEnumSessionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::EnumProfileSessionsAndToolsResponse>> PrepareAsyncEnumSessions(::grpc::ClientContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::EnumProfileSessionsAndToolsResponse>>(PrepareAsyncEnumSessionsRaw(context, request, cq));
    }
    ::grpc::Status GetSessionToolData(::grpc::ClientContext* context, const ::tensorflow::ProfileSessionDataRequest& request, ::tensorflow::ProfileSessionDataResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::ProfileSessionDataResponse>> AsyncGetSessionToolData(::grpc::ClientContext* context, const ::tensorflow::ProfileSessionDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::ProfileSessionDataResponse>>(AsyncGetSessionToolDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::ProfileSessionDataResponse>> PrepareAsyncGetSessionToolData(::grpc::ClientContext* context, const ::tensorflow::ProfileSessionDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::ProfileSessionDataResponse>>(PrepareAsyncGetSessionToolDataRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void NewSession(::grpc::ClientContext* context, const ::tensorflow::NewProfileSessionRequest* request, ::tensorflow::NewProfileSessionResponse* response, std::function<void(::grpc::Status)>) override;
      void NewSession(::grpc::ClientContext* context, const ::tensorflow::NewProfileSessionRequest* request, ::tensorflow::NewProfileSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void EnumSessions(::grpc::ClientContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest* request, ::tensorflow::EnumProfileSessionsAndToolsResponse* response, std::function<void(::grpc::Status)>) override;
      void EnumSessions(::grpc::ClientContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest* request, ::tensorflow::EnumProfileSessionsAndToolsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetSessionToolData(::grpc::ClientContext* context, const ::tensorflow::ProfileSessionDataRequest* request, ::tensorflow::ProfileSessionDataResponse* response, std::function<void(::grpc::Status)>) override;
      void GetSessionToolData(::grpc::ClientContext* context, const ::tensorflow::ProfileSessionDataRequest* request, ::tensorflow::ProfileSessionDataResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::tensorflow::NewProfileSessionResponse>* AsyncNewSessionRaw(::grpc::ClientContext* context, const ::tensorflow::NewProfileSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::tensorflow::NewProfileSessionResponse>* PrepareAsyncNewSessionRaw(::grpc::ClientContext* context, const ::tensorflow::NewProfileSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::tensorflow::EnumProfileSessionsAndToolsResponse>* AsyncEnumSessionsRaw(::grpc::ClientContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::tensorflow::EnumProfileSessionsAndToolsResponse>* PrepareAsyncEnumSessionsRaw(::grpc::ClientContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::tensorflow::ProfileSessionDataResponse>* AsyncGetSessionToolDataRaw(::grpc::ClientContext* context, const ::tensorflow::ProfileSessionDataRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::tensorflow::ProfileSessionDataResponse>* PrepareAsyncGetSessionToolDataRaw(::grpc::ClientContext* context, const ::tensorflow::ProfileSessionDataRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_NewSession_;
    const ::grpc::internal::RpcMethod rpcmethod_EnumSessions_;
    const ::grpc::internal::RpcMethod rpcmethod_GetSessionToolData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Starts a profiling session, blocks until it completes.
    // TPUProfileAnalysis service delegate this to TPUProfiler service.
    // Populate the profiled data in repository, then return status to caller.
    virtual ::grpc::Status NewSession(::grpc::ServerContext* context, const ::tensorflow::NewProfileSessionRequest* request, ::tensorflow::NewProfileSessionResponse* response);
    // Enumerate existing sessions and return available profile tools.
    virtual ::grpc::Status EnumSessions(::grpc::ServerContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest* request, ::tensorflow::EnumProfileSessionsAndToolsResponse* response);
    // Retrieve specific tool's data for specific session.
    virtual ::grpc::Status GetSessionToolData(::grpc::ServerContext* context, const ::tensorflow::ProfileSessionDataRequest* request, ::tensorflow::ProfileSessionDataResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_NewSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_NewSession() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_NewSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewSession(::grpc::ServerContext* /*context*/, const ::tensorflow::NewProfileSessionRequest* /*request*/, ::tensorflow::NewProfileSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNewSession(::grpc::ServerContext* context, ::tensorflow::NewProfileSessionRequest* request, ::grpc::ServerAsyncResponseWriter< ::tensorflow::NewProfileSessionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_EnumSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_EnumSessions() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_EnumSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnumSessions(::grpc::ServerContext* /*context*/, const ::tensorflow::EnumProfileSessionsAndToolsRequest* /*request*/, ::tensorflow::EnumProfileSessionsAndToolsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEnumSessions(::grpc::ServerContext* context, ::tensorflow::EnumProfileSessionsAndToolsRequest* request, ::grpc::ServerAsyncResponseWriter< ::tensorflow::EnumProfileSessionsAndToolsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetSessionToolData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetSessionToolData() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetSessionToolData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSessionToolData(::grpc::ServerContext* /*context*/, const ::tensorflow::ProfileSessionDataRequest* /*request*/, ::tensorflow::ProfileSessionDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSessionToolData(::grpc::ServerContext* context, ::tensorflow::ProfileSessionDataRequest* request, ::grpc::ServerAsyncResponseWriter< ::tensorflow::ProfileSessionDataResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_NewSession<WithAsyncMethod_EnumSessions<WithAsyncMethod_GetSessionToolData<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_NewSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_NewSession() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::tensorflow::NewProfileSessionRequest, ::tensorflow::NewProfileSessionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::tensorflow::NewProfileSessionRequest* request, ::tensorflow::NewProfileSessionResponse* response) { return this->NewSession(context, request, response); }));}
    void SetMessageAllocatorFor_NewSession(
        ::grpc::MessageAllocator< ::tensorflow::NewProfileSessionRequest, ::tensorflow::NewProfileSessionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::tensorflow::NewProfileSessionRequest, ::tensorflow::NewProfileSessionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_NewSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewSession(::grpc::ServerContext* /*context*/, const ::tensorflow::NewProfileSessionRequest* /*request*/, ::tensorflow::NewProfileSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* NewSession(
      ::grpc::CallbackServerContext* /*context*/, const ::tensorflow::NewProfileSessionRequest* /*request*/, ::tensorflow::NewProfileSessionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_EnumSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_EnumSessions() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::tensorflow::EnumProfileSessionsAndToolsRequest, ::tensorflow::EnumProfileSessionsAndToolsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::tensorflow::EnumProfileSessionsAndToolsRequest* request, ::tensorflow::EnumProfileSessionsAndToolsResponse* response) { return this->EnumSessions(context, request, response); }));}
    void SetMessageAllocatorFor_EnumSessions(
        ::grpc::MessageAllocator< ::tensorflow::EnumProfileSessionsAndToolsRequest, ::tensorflow::EnumProfileSessionsAndToolsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::tensorflow::EnumProfileSessionsAndToolsRequest, ::tensorflow::EnumProfileSessionsAndToolsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_EnumSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnumSessions(::grpc::ServerContext* /*context*/, const ::tensorflow::EnumProfileSessionsAndToolsRequest* /*request*/, ::tensorflow::EnumProfileSessionsAndToolsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EnumSessions(
      ::grpc::CallbackServerContext* /*context*/, const ::tensorflow::EnumProfileSessionsAndToolsRequest* /*request*/, ::tensorflow::EnumProfileSessionsAndToolsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetSessionToolData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetSessionToolData() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::tensorflow::ProfileSessionDataRequest, ::tensorflow::ProfileSessionDataResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::tensorflow::ProfileSessionDataRequest* request, ::tensorflow::ProfileSessionDataResponse* response) { return this->GetSessionToolData(context, request, response); }));}
    void SetMessageAllocatorFor_GetSessionToolData(
        ::grpc::MessageAllocator< ::tensorflow::ProfileSessionDataRequest, ::tensorflow::ProfileSessionDataResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::tensorflow::ProfileSessionDataRequest, ::tensorflow::ProfileSessionDataResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetSessionToolData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSessionToolData(::grpc::ServerContext* /*context*/, const ::tensorflow::ProfileSessionDataRequest* /*request*/, ::tensorflow::ProfileSessionDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSessionToolData(
      ::grpc::CallbackServerContext* /*context*/, const ::tensorflow::ProfileSessionDataRequest* /*request*/, ::tensorflow::ProfileSessionDataResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_NewSession<WithCallbackMethod_EnumSessions<WithCallbackMethod_GetSessionToolData<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_NewSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_NewSession() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_NewSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewSession(::grpc::ServerContext* /*context*/, const ::tensorflow::NewProfileSessionRequest* /*request*/, ::tensorflow::NewProfileSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_EnumSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_EnumSessions() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_EnumSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnumSessions(::grpc::ServerContext* /*context*/, const ::tensorflow::EnumProfileSessionsAndToolsRequest* /*request*/, ::tensorflow::EnumProfileSessionsAndToolsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetSessionToolData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetSessionToolData() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetSessionToolData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSessionToolData(::grpc::ServerContext* /*context*/, const ::tensorflow::ProfileSessionDataRequest* /*request*/, ::tensorflow::ProfileSessionDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_NewSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_NewSession() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_NewSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewSession(::grpc::ServerContext* /*context*/, const ::tensorflow::NewProfileSessionRequest* /*request*/, ::tensorflow::NewProfileSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNewSession(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_EnumSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_EnumSessions() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_EnumSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnumSessions(::grpc::ServerContext* /*context*/, const ::tensorflow::EnumProfileSessionsAndToolsRequest* /*request*/, ::tensorflow::EnumProfileSessionsAndToolsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEnumSessions(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetSessionToolData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetSessionToolData() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetSessionToolData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSessionToolData(::grpc::ServerContext* /*context*/, const ::tensorflow::ProfileSessionDataRequest* /*request*/, ::tensorflow::ProfileSessionDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSessionToolData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_NewSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_NewSession() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->NewSession(context, request, response); }));
    }
    ~WithRawCallbackMethod_NewSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewSession(::grpc::ServerContext* /*context*/, const ::tensorflow::NewProfileSessionRequest* /*request*/, ::tensorflow::NewProfileSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* NewSession(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_EnumSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_EnumSessions() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->EnumSessions(context, request, response); }));
    }
    ~WithRawCallbackMethod_EnumSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnumSessions(::grpc::ServerContext* /*context*/, const ::tensorflow::EnumProfileSessionsAndToolsRequest* /*request*/, ::tensorflow::EnumProfileSessionsAndToolsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EnumSessions(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetSessionToolData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetSessionToolData() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetSessionToolData(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetSessionToolData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSessionToolData(::grpc::ServerContext* /*context*/, const ::tensorflow::ProfileSessionDataRequest* /*request*/, ::tensorflow::ProfileSessionDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSessionToolData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_NewSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_NewSession() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::tensorflow::NewProfileSessionRequest, ::tensorflow::NewProfileSessionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::tensorflow::NewProfileSessionRequest, ::tensorflow::NewProfileSessionResponse>* streamer) {
                       return this->StreamedNewSession(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_NewSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status NewSession(::grpc::ServerContext* /*context*/, const ::tensorflow::NewProfileSessionRequest* /*request*/, ::tensorflow::NewProfileSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedNewSession(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::tensorflow::NewProfileSessionRequest,::tensorflow::NewProfileSessionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_EnumSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_EnumSessions() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::tensorflow::EnumProfileSessionsAndToolsRequest, ::tensorflow::EnumProfileSessionsAndToolsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::tensorflow::EnumProfileSessionsAndToolsRequest, ::tensorflow::EnumProfileSessionsAndToolsResponse>* streamer) {
                       return this->StreamedEnumSessions(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_EnumSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status EnumSessions(::grpc::ServerContext* /*context*/, const ::tensorflow::EnumProfileSessionsAndToolsRequest* /*request*/, ::tensorflow::EnumProfileSessionsAndToolsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEnumSessions(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::tensorflow::EnumProfileSessionsAndToolsRequest,::tensorflow::EnumProfileSessionsAndToolsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetSessionToolData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetSessionToolData() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::tensorflow::ProfileSessionDataRequest, ::tensorflow::ProfileSessionDataResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::tensorflow::ProfileSessionDataRequest, ::tensorflow::ProfileSessionDataResponse>* streamer) {
                       return this->StreamedGetSessionToolData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetSessionToolData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetSessionToolData(::grpc::ServerContext* /*context*/, const ::tensorflow::ProfileSessionDataRequest* /*request*/, ::tensorflow::ProfileSessionDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetSessionToolData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::tensorflow::ProfileSessionDataRequest,::tensorflow::ProfileSessionDataResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_NewSession<WithStreamedUnaryMethod_EnumSessions<WithStreamedUnaryMethod_GetSessionToolData<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_NewSession<WithStreamedUnaryMethod_EnumSessions<WithStreamedUnaryMethod_GetSessionToolData<Service > > > StreamedService;
};

}  // namespace grpc

}  // namespace tensorflow


#endif  // GRPC_tensorflow_2fcore_2fprofiler_2fprofiler_5fanalysis_2eproto__INCLUDED
