[tool.poetry]
name = "microdegree-management"
version = "1.3.0"
description = ""
authors = ["Vincent Nys <vincent.nys@ap.be>"]

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "^6.0"
types-PyYAML = "^6.0.12"
pydantic = "^1.10.2"
pydantic-yaml = "^0.8.1"
graphviz = "^0.20.1"
networkx = "^3.0"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.991"
black = {version = "^22.10.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
manage-microdegree = "microdegree_management.main:cli"
