
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-14T12:00:51-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "902ca7fc3d3ed4395742b4e74d1f8e2e932b5cf5",
 "version": "0.3.0.post0.dev47"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
