
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-14T05:54:17-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "f57090486dd0798aa7bed7f6edbc93253a438b0b",
 "version": "v0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
