
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-10T10:46:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f359051ec1273e7b08642473c3f899f0d4d6c9f2",
 "version": "v0.0.1-beta.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
