[tool.poetry]
name = "dependency-resolution"
version = "0.2.2"
description = "A simple dependency resolution library using container concepts"
authors = [ "Saroopashree K <saroopa25@gmail.com>" ]
license = "MIT"
keywords = [ "dependency", "resolution", "injection" ]
packages = [
    { include = "dependency_resolution" },
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.0"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
isort = "^5.12.0"
pytest = "^7.2.1"
poethepoet = "^0.18.1"
pytest-cov = "^4.0.0"

[tool.poe.tasks]
test = "pytest -v --color=yes --cov-branch --cov-report term --cov-report xml:coverage.xml --no-cov-on-fail --cov dependency_resolution ./tests"
format = "isort . && black ."

[tool.pytest.ini_options]
testpaths = "tests"

[tool.isort]
py_version = 310
profile = "black"
line_length = 120
skip_gitignore = true

[tool.black]
line-length = 120
target-version = ['py310']