[tool.poetry]
name = "repoupdate"
version = "0.1.0"
description = "Sync your local with remote"
authors = ["Jiri Podivin <jpodivin@redhat.com>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = ">=3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
repoupdate = 'repoupdate:main'
