CREATE TABLE "prod2-generico"."car-churn" (
	"patient-id" int8 NOT NULL,
	"store-id" int4 NOT NULL,
	"bill-id" int8 NOT NULL,
	"bill-created-at" timestamp NOT NULL,
	"bill-date" date NOT NULL,
	"year-bill" int4 NOT NULL,
	"month-bill" int4 NOT NULL,
	"nob-till-bill" int4 NOT NULL,
	"next-bill-date" date NULL,
	"day-diff-next-bill" int4 NULL,
	"day-diff-today" int4 NULL,
	"lost-event-flag" int4 NULL,
	"bill-date-plus90" date NULL,
	"lost-attribution-date" date NULL,
	"overall-min-bill-date" date NULL,
	"month-diff-acq" int4 NULL,
	"total-spend" numeric(17, 4) NULL,
	"spend-till-bill" numeric(17, 4) NULL,
	"average-bill-value" numeric(17, 4) NULL,
	"pr-72hrs-delay" int4 NULL,
	"min-created-at" timestamp NULL,
	"max-completed-at" timestamp NULL,
	"lost-pr-date-diff" int4 NULL,
	"pr-lost" int4 NULL,
	"hd-24hrs-delay" int4 NULL,
	rating int4 NULL,
	"feedback-date" date NULL,
	"nps-date-diff" int4 NULL,
	"nps-detractor-lost" int4 NULL,
	"return-flag" int4 NULL,
	items int4 NULL,
	"expiry-less-6m" int4 NULL,
	"expiry-less-6m-pc" numeric(17, 4) NULL,
	"near-expiry-flag" int4 NULL,
	"churn-event" varchar(255) NULL,
	"latest-is-repeatable" varchar(255) NULL,
	"latest-is-generic" varchar(255) NULL,
	"latest-hd-flag" varchar(255) NULL,
	"primary-disease" varchar(255) NULL,
	"normalized-date" date NULL,
	"value-segment-calc-date" date NULL,
	"value-segment" varchar(255) NULL,
	"behaviour-segment-calc-date" date NULL,
	"behaviour-segment" varchar(255) NULL,
	"store-name" varchar(255) NULL,
	"store-opened-at" timestamp NULL,
	abo varchar(255) NULL,
	"created-at" timestamp NULL,
	"created-by" varchar(255) NULL,
	"updated-at" timestamp NULL,
	"updated-by" varchar(255) NULL
);

CREATE TABLE "prod2-generico"."store-call-logs-entries" (
	"call-type" varchar(255) NULL,
	status varchar(255) NULL,
	"type" varchar(255) NULL,
	"is-active" varchar(255) NULL,
	"to-number" varchar(255) NULL,
	"from-number" varchar(255) NULL,
	"store-id" int4 NULL,
	duration varchar(255) NULL,
	"date-time" timestamp NULL,
	"created-at" timestamp NULL,
	"created-by" varchar(255) NULL,
	"updated-at" timestamp NULL,
	"updated-by" varchar(255) NULL
);