[workspace]
members = ["local_dependencies/sha1_smol_r"]

[package]
name = "rust_lib"
version = "0.0.0"
authors = ["Kirill Kuzminykh <cykooz@gmail.com>"]
edition = "2021"


[lib]
name = "rust_lib"
crate-type = ["cdylib"]


[package.metadata.maturin]
name = "cykooz.rehash.rust_lib"


[dependencies]
pyo3 = "0.18.1"
sha1_smol_r = { path = "local_dependencies/sha1_smol_r" }


[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]


[profile.release]
lto = true
opt-level = 3
codegen-units = 1
strip = true
