
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-13T15:18:52-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c80195f284c68a8d6efca0ee787be7cbc89c182",
 "version": "0.3.0.post0.dev42"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
