
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-14T16:38:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c2cfa089d8a29f10a248be62619f4e070b12960",
 "version": "1.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
