
[tool.poetry]
name = "markus-pettersen"
version = "0.1.0"
description = "Random useful python stuff I sometimes use"
authors = ["Markus Pettersen <mp.markus94@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.5.3"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
