[project]
name = "lm-detect"
version = "0.0.1"
description = "Zero-Shot Machine-Generated Text Detection"
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE.txt"}
authors = [
    {name = "André Storhaug", email = "andr3.storhaug@gmail.com" }
]
maintainers = [
    {name = "André Storhaug", email = "andr3.storhaug@gmail.com" }
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "torch",
    "tqdm"
]

[project.optional-dependencies]
dev = ["transformers", "tokenizers"]
test = ["pytest"]

[project.urls]
"Homepage" = "https://github.com/andstor/lm-detect/"
"Tracker" = "https://github.com/andstor/lm-detect/issues"
"Funding" = "https://github.com/sponsors/andstor"
"Source" = "https://github.com/andstor/lm-detect/"

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"