[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[[tool.mypy.overrides]]
module = [
    'mashumaro.mixins.dict',
    'mashumaro.mixins.msgpack',
    'mashumaro.mixins.toml',
]
disable_error_code = 'empty-body'

[[tool.mypy.overrides]]
module = [
    'mashumaro.core.meta.types.pack',
    'mashumaro.core.meta.types.unpack',
]
disable_error_code = 'return'

[flake8]
max-line-length = 79

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
ensure_newline_before_comments = true

[tool.black]
line-length = 79
target-version = ['py37', 'py38', 'py39']
