[tool.poetry]
name = "getx"
version = "0.1.1"
description = ""
authors = ["Elsafy Hegazy <safy.dev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.2"
cryptography = "^39.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
