[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "animeFlvV2"
version = "0.0.3"
authors = [
    { name="julianmorera", email="xxx@gmail.com" },
]
description = "Nueva versión del api AnimeFlv"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.5"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/JulianMorera07/anime-flv-api"
