[project]
name = "epot_test_deps"
description = "Deps of `epot-test`"
readme = "README.md"
requires-python = ">=3.8"
authors = [{name = "Conchylicultor", email="etils@google.com"}]

# This is set automatically by flit using `etils.__version__`
dynamic = ["version"]

dependencies = []

[build-system]
requires = ["flit_core >=3.5,<4"]
build-backend = "flit_core.buildapi"