[tool.poetry]
name = "essencia-engine"
version = "0.1.0"
description = ""
authors = ["Daniel Arantes <arantesdv@me.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = {extras = ["email", "dotenv"], version = "^1.10.4"}
deta = {version = "1.1.0a2", extras = ["async"]}
starlette = "^0.24.0"
Jinja2 = "^3.1.2"
anyio = "^3.6.2"
Unidecode = "^1.3.6"
bcrypt = "^4.0.1"
python-multipart = "^0.0.5"
itsdangerous = "^2.1.2"
httpx = "^0.23.3"
asgi-csrf = "^0.9"
uvicorn = "^0.20.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
