# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Frankenfit Documentation
author: Max Bane <max@thebanes.org>
logo: "favicon-32x32.png"
copyright: 2023, Max Bane

only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'force'
  # execute_notebooks: 'off'

# Information about where the book exists on the web
repository:
  url: https://github.com/maxbane/frankenfit  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

html:
  favicon: favicon-32x32.png

sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  config:
    html_theme: furo
    # Setting the following conf.py attribute requires building the book in a special
    # way. See tox.ini.
    pygments_style: dracula
    pygments_dark_style: dracula
    html_static_path: ["_static"]
    html_css_files: ["pygments_overrides.css"]
    html_theme_options:
      footer_icons:
        - name: PyPI
          url: "https://pypi.org/project/frankenfit"
          class: ""
          html: '<span id="snake">🐍</span>'
        - name: GitHub
          url: "https://github.com/maxbane/frankenfit"
          class: ""
          html:
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
            </svg>

      # Make furo dark and ligh mode use Dracula palette (there is only dark!)
      light_css_variables:
        color-background-item: "#6272A4"
        color-brand-primary: "#50FA7B"
        color-brand-content: "#50FA7B"
        color-problematic: "#FF5555"
        color-foreground-primary: "#F8F8F2"
        color-foreground-secondary: "#6272A4"
        color-foreground-border: "#6272A4"
        color-background-primary: "#282A36"
        color-background-secondary: "#343746"
        color-background-hover: "#44475A"
        color-background-hover--transparent: "#44475A"
        color-highlighted-background: "#44475A75"

        # Admonitions
        color-admonition-background: "#343746"
        # "caution"
        color-admonition-title--caution: "#FFB86C"
        color-admonition-title-background--caution: "rgba(255, 184, 108, .1)"
        # "warning"
        color-admonition-title--warning: "#F1FA8C"
        color-admonition-title-background--warning: "rgba(241, 250, 140, .1)"
        # "danger"
        color-admonition-title--danger: "#FF5555"
        color-admonition-title-background--danger: "rgba(255, 85, 85, .1)"
        # "attention"
        color-admonition-title--attention: "#FF5555"
        color-admonition-title-background--attention: "rgba(255, 85, 85, .1)"
        # "error"
        color-admonition-title--error: "#FF5555"
        color-admonition-title-background--error: "rgba(255, 85, 85, .1)"
        # "hint"
        color-admonition-title--hint: "#50FA7B"
        color-admonition-title-background--hint: "rgba(80, 250, 123, .1)"
        # "tip"
        color-admonition-title--tip: "#50FA7B"
        color-admonition-title-background--tip: "rgba(80, 250, 123, .1)"
        # "important"
        color-admonition-title--important: "#FF79C6"
        color-admonition-title-background--important: "rgba(255, 121, 198, .1)"
        # "note"
        color-admonition-title--note: "#BD93F9"
        color-admonition-title-background--note: "rgba(189, 147, 249, .1)"
        # "seealso"
        color-admonition-title--seealso: "#6272A4"
        color-admonition-title-background--seealso: "rgba(98, 114, 164, .1)"
        # "admonition-todo"
        color-admonition-title--admonition-todo: "#808080"
        color-admonition-title-background--admonition-todo: "rgba(128, 128, 128, .1)"

      dark_css_variables:
        color-background-item: "#6272A4"
        color-brand-primary: "#50FA7B"
        color-brand-content: "#50FA7B"
        color-problematic: "#FF5555"
        color-foreground-primary: "#F8F8F2"
        color-foreground-secondary: "#6272A4"
        color-foreground-border: "#6272A4"
        color-background-primary: "#282A36"
        color-background-secondary: "#343746"
        color-background-hover: "#44475A"
        color-background-hover--transparent: "#44475A"
        color-highlighted-background: "#44475A75"

        # Admonitions
        color-admonition-background: "#343746"
        # "caution"
        color-admonition-title--caution: "#FFB86C"
        color-admonition-title-background--caution: "rgba(255, 184, 108, .1)"
        # "warning"
        color-admonition-title--warning: "#F1FA8C"
        color-admonition-title-background--warning: "rgba(241, 250, 140, .1)"
        # "danger"
        color-admonition-title--danger: "#FF5555"
        color-admonition-title-background--danger: "rgba(255, 85, 85, .1)"
        # "attention"
        color-admonition-title--attention: "#FF5555"
        color-admonition-title-background--attention: "rgba(255, 85, 85, .1)"
        # "error"
        color-admonition-title--error: "#FF5555"
        color-admonition-title-background--error: "rgba(255, 85, 85, .1)"
        # "hint"
        color-admonition-title--hint: "#50FA7B"
        color-admonition-title-background--hint: "rgba(80, 250, 123, .1)"
        # "tip"
        color-admonition-title--tip: "#50FA7B"
        color-admonition-title-background--tip: "rgba(80, 250, 123, .1)"
        # "important"
        color-admonition-title--important: "#FF79C6"
        color-admonition-title-background--important: "rgba(255, 121, 198, .1)"
        # "note"
        color-admonition-title--note: "#BD93F9"
        color-admonition-title-background--note: "rgba(189, 147, 249, .1)"
        # "seealso"
        color-admonition-title--seealso: "#6272A4"
        color-admonition-title-background--seealso: "rgba(98, 114, 164, .1)"
        # "admonition-todo"
        color-admonition-title--admonition-todo: "#808080"
        color-admonition-title-background--admonition-todo: "rgba(128, 128, 128, .1)"
