[tool.poetry]
name = "koldstart"
version = "0.6.19"
description = "koldstart is an easy-to-use Serverless Python Framework"
authors = ["Features & Labels <hello@fal.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
auth0-python = "^3.24.0"
requests = "^2.28.1"
isolate = "0.10.0"
grpcio = "^1.50.0"
dill = "0.3.5.1"
isolate-proto = "^0.0.19"
typing-extensions = "4.4"
click = "^8.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
koldstart = "koldstart.cli:cli"
