[build-system]
requires      = ["hatchling"]
build-backend = "hatchling.build"

[project]
name     = "manimxyzmove"
version  = "0.0.3"
authors  = [
  { name = "iHnR", email="ihnr@proton.me" },
]
description     = "Utitlity to move along an (x,y,z) defined path in manim."
readme          = "README.md"
requires-python = ">=3.8,<3.12"
dependencies    =[
  "manim",
  "numpy"
]
classifiers     = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
