[tool.poetry]
name = "jmanager"
version = "1.8.2"
description = "A lightweight Jupyter process manager"
authors = ["Yasunori Horikoshi <hotoku@users.noreply.github.com>"]
license = "MIT"


[tool.poetry.dependencies]
python = "^3.10"
jupyterlab = "^3.5.2"
click = "^8.1.3"


[tool.poetry.dev-dependencies]
bump2version = "^1.0.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
jmanager = "jmanager.cli:main"
