[build-system]
requires = ["setuptools","xlrd","openpyxl","pandas","PyPDF2","build","numpy","xlwt","pip","jupyter","numexpr","openpyxl","bottleneck","xarray"]
build-backend = "setuptools.build_meta"
[project]
name = "alacorder"
version = "70.5"
authors = [
  { name="Sam Robson", email="sbrobson@crimson.ua.edu" },
]
description = "pure-python"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = ["pandas","xarray","numpy","xlrd","openpyxl","setuptools","PyPDF2","xlwt","build","pip","jupyter","numexpr","bottleneck"]
