[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "literature_game_engine_raspuchin"
version = "0.0.1"
authors = [
  { name="Sachin Pothukuchi", email="sachinpothukuchi31@gmail.com" },
]
description = "Package to provide a game engine to play literature."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/raspuchin/literature-game"
"Bug Tracker" = "https://github.com/raspuchin/literature-game/issues"