[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "scriptie"
version = "0.1.0"
dependencies = [
    "aiohttp",
]

[project.scripts]
scriptie = "scriptie.server:main"

[tool.setuptools.package-data]
"*" = ["*.html", "*.js", "*.css"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]
asyncio_mode = "auto"
