[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "saxml"
version = "0.0.1"
authors = [
  { name="Saxml Team", email="sax-dev@google.com" },
]
description = "Saxml is an experimental system that serves Paxml models for inference."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
]

[project.urls]
"Homepage" = "https://github.com/google/saxml"
