# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: afilter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rafilter.proto\x12\x07\x61\x66ilter\"5\n\rFilterRequest\x12$\n\x07request\x18\x01 \x03(\x0b\x32\x13.afilter.OneRequest\"L\n\x0b\x46ilterReply\x12 \n\x05reply\x18\x01 \x03(\x0b\x32\x11.afilter.OneReply\x12\x1b\n\x04info\x18\x02 \x01(\x0b\x32\r.afilter.Info\"R\n\nOneRequest\x12!\n\x08\x63\x61m_data\x18\x01 \x01(\x0b\x32\x0f.afilter.Onemat\x12!\n\x08\x63\x61\x64_data\x18\x02 \x01(\x0b\x32\x0f.afilter.Onemat\"_\n\x08OneReply\x12\r\n\x05ok_ng\x18\x01 \x01(\x08\x12 \n\tcrop_bbox\x18\x02 \x01(\x0b\x32\r.afilter.Bbox\x12\"\n\x06\x64\x65\x66\x65\x63t\x18\x03 \x03(\x0b\x32\x12.afilter.Onedefect\"@\n\x04\x42\x62ox\x12\x0c\n\x04left\x18\x01 \x01(\x05\x12\x0b\n\x03top\x18\x02 \x01(\x05\x12\r\n\x05right\x18\x03 \x01(\x05\x12\x0e\n\x06\x62ottom\x18\x04 \x01(\x05\"8\n\tOnedefect\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\x04mask\x18\x02 \x01(\x0b\x32\x0f.afilter.Onemat\"F\n\x06Onemat\x12\x0c\n\x04rows\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x02 \x01(\x05\x12\x0e\n\x06\x64_type\x18\x03 \x01(\t\x12\x10\n\x08mat_data\x18\x04 \x01(\x0c\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xa2\x01\n\x13HealthCheckResponse\x12:\n\x06status\x18\x01 \x01(\x0e\x32*.afilter.HealthCheckResponse.ServingStatus\"O\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x03\"8\n\x04Info\x12\x18\n\x10infer_start_time\x18\x01 \x01(\t\x12\x16\n\x0einfer_end_time\x18\x02 \x01(\t2\x98\x02\n\x06\x46ilter\x12<\n\nFilterFunc\x12\x16.afilter.FilterRequest\x1a\x14.afilter.FilterReply\"\x00\x12:\n\nFilterChat\x12\x13.afilter.OneRequest\x1a\x11.afilter.OneReply\"\x00(\x01\x30\x01\x12H\n\x0b\x46ilterCheck\x12\x1b.afilter.HealthCheckRequest\x1a\x1c.afilter.HealthCheckResponse\x12J\n\x0b\x46ilterWatch\x12\x1b.afilter.HealthCheckRequest\x1a\x1c.afilter.HealthCheckResponse0\x01\x62\x06proto3')



_FILTERREQUEST = DESCRIPTOR.message_types_by_name['FilterRequest']
_FILTERREPLY = DESCRIPTOR.message_types_by_name['FilterReply']
_ONEREQUEST = DESCRIPTOR.message_types_by_name['OneRequest']
_ONEREPLY = DESCRIPTOR.message_types_by_name['OneReply']
_BBOX = DESCRIPTOR.message_types_by_name['Bbox']
_ONEDEFECT = DESCRIPTOR.message_types_by_name['Onedefect']
_ONEMAT = DESCRIPTOR.message_types_by_name['Onemat']
_HEALTHCHECKREQUEST = DESCRIPTOR.message_types_by_name['HealthCheckRequest']
_HEALTHCHECKRESPONSE = DESCRIPTOR.message_types_by_name['HealthCheckResponse']
_INFO = DESCRIPTOR.message_types_by_name['Info']
_HEALTHCHECKRESPONSE_SERVINGSTATUS = _HEALTHCHECKRESPONSE.enum_types_by_name['ServingStatus']
FilterRequest = _reflection.GeneratedProtocolMessageType('FilterRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILTERREQUEST,
  '__module__' : 'afilter_pb2'
  # @@protoc_insertion_point(class_scope:afilter.FilterRequest)
  })
_sym_db.RegisterMessage(FilterRequest)

FilterReply = _reflection.GeneratedProtocolMessageType('FilterReply', (_message.Message,), {
  'DESCRIPTOR' : _FILTERREPLY,
  '__module__' : 'afilter_pb2'
  # @@protoc_insertion_point(class_scope:afilter.FilterReply)
  })
_sym_db.RegisterMessage(FilterReply)

OneRequest = _reflection.GeneratedProtocolMessageType('OneRequest', (_message.Message,), {
  'DESCRIPTOR' : _ONEREQUEST,
  '__module__' : 'afilter_pb2'
  # @@protoc_insertion_point(class_scope:afilter.OneRequest)
  })
_sym_db.RegisterMessage(OneRequest)

OneReply = _reflection.GeneratedProtocolMessageType('OneReply', (_message.Message,), {
  'DESCRIPTOR' : _ONEREPLY,
  '__module__' : 'afilter_pb2'
  # @@protoc_insertion_point(class_scope:afilter.OneReply)
  })
_sym_db.RegisterMessage(OneReply)

Bbox = _reflection.GeneratedProtocolMessageType('Bbox', (_message.Message,), {
  'DESCRIPTOR' : _BBOX,
  '__module__' : 'afilter_pb2'
  # @@protoc_insertion_point(class_scope:afilter.Bbox)
  })
_sym_db.RegisterMessage(Bbox)

Onedefect = _reflection.GeneratedProtocolMessageType('Onedefect', (_message.Message,), {
  'DESCRIPTOR' : _ONEDEFECT,
  '__module__' : 'afilter_pb2'
  # @@protoc_insertion_point(class_scope:afilter.Onedefect)
  })
_sym_db.RegisterMessage(Onedefect)

Onemat = _reflection.GeneratedProtocolMessageType('Onemat', (_message.Message,), {
  'DESCRIPTOR' : _ONEMAT,
  '__module__' : 'afilter_pb2'
  # @@protoc_insertion_point(class_scope:afilter.Onemat)
  })
_sym_db.RegisterMessage(Onemat)

HealthCheckRequest = _reflection.GeneratedProtocolMessageType('HealthCheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKREQUEST,
  '__module__' : 'afilter_pb2'
  # @@protoc_insertion_point(class_scope:afilter.HealthCheckRequest)
  })
_sym_db.RegisterMessage(HealthCheckRequest)

HealthCheckResponse = _reflection.GeneratedProtocolMessageType('HealthCheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKRESPONSE,
  '__module__' : 'afilter_pb2'
  # @@protoc_insertion_point(class_scope:afilter.HealthCheckResponse)
  })
_sym_db.RegisterMessage(HealthCheckResponse)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), {
  'DESCRIPTOR' : _INFO,
  '__module__' : 'afilter_pb2'
  # @@protoc_insertion_point(class_scope:afilter.Info)
  })
_sym_db.RegisterMessage(Info)

_FILTER = DESCRIPTOR.services_by_name['Filter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILTERREQUEST._serialized_start=26
  _FILTERREQUEST._serialized_end=79
  _FILTERREPLY._serialized_start=81
  _FILTERREPLY._serialized_end=157
  _ONEREQUEST._serialized_start=159
  _ONEREQUEST._serialized_end=241
  _ONEREPLY._serialized_start=243
  _ONEREPLY._serialized_end=338
  _BBOX._serialized_start=340
  _BBOX._serialized_end=404
  _ONEDEFECT._serialized_start=406
  _ONEDEFECT._serialized_end=462
  _ONEMAT._serialized_start=464
  _ONEMAT._serialized_end=534
  _HEALTHCHECKREQUEST._serialized_start=536
  _HEALTHCHECKREQUEST._serialized_end=573
  _HEALTHCHECKRESPONSE._serialized_start=576
  _HEALTHCHECKRESPONSE._serialized_end=738
  _HEALTHCHECKRESPONSE_SERVINGSTATUS._serialized_start=659
  _HEALTHCHECKRESPONSE_SERVINGSTATUS._serialized_end=738
  _INFO._serialized_start=740
  _INFO._serialized_end=796
  _FILTER._serialized_start=799
  _FILTER._serialized_end=1079
# @@protoc_insertion_point(module_scope)
