[build-system]
requires = ["setuptools", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
force-exclude = '''
(
  *.__pycache__
)
'''

# [tool.ruff]
# Enable flake8-bugbear (`B`) rules.
# select = ["E", "F", "B", "D"]
# max-line-length = 88
# # Never enforce `E501` (line length violations).
# ignore = ["E501"]
# # Avoid trying to fix flake8-bugbear (`B`) violations.
# # Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
# except = ["**.__pycache__*"]
#
# [tool.ruff.per-file-ignores]
# "__init__.py" = ["E402"]
# "path/to/file.py" = ["E402"]

[tool.isort]
profile = "black"
multi_line_output = 3
ignore_missing_imports = true

[tool.pydocstyle]
inherit = false
add_ignore = "D100,D104,D105,D107,D205,D400,D401"
convention = "pep257"

[project]
name = "ka_utg"
description = "special Utilities"
license = {file = "LICENSE.txt"}
requires-python = ">=3.10"
dynamic = ["classifiers", "version", "dependencies"]
readme = "README.md"
authors = [{name = "Bernd Stroehle", email = "bernd.stroehle@dbs29.com"}]

[project.urls]
"Source Code" = "https://github.com/bs29/ka_utg"
"Homepage" = "https://kosakya.de/"
"Documentation" = "https://bs29.atlassian.net/wiki/spaces/SD/pages/164074/ka+utg"
# "Bug Tracker" = "https://kosakya.de/issues"
# "Changelog" = "https://kosakya.de/ka_utg/blob/master/CHANGELOG.md"
"GPLv3 License" = "https://www.gnu.org/licenses/gpl-3.0.en.html"
# "GPLv3 License" = "https://gitlab.com/bs29/licenses/gpl-1.0.en.html"

[tool.setuptools]
zip-safe = false
include-package-data = true

# [tool.setuptools.packages]
# find = {namespaces = true}
# namespace_packages = ka_utg

# [toolsetuotools.options.package_data]
# * = *.*

[tool.setuptools.packages.find]
# where = ["."]  # list of folders that contain the packages (["."] by default)
# include = ["ka_utg*"]  # package names should match these glob patterns (["*"] by default)
# exclude = ["ka_utg.tests*"]  # exclude packages matching these glob patterns (empty by default)
namespaces = true  # to disable scanning PEP 420 namespaces (true by default)

[tool.setuptools.dynamic]
version = {attr = "ka_utg.__version__.__version__"}
readme = {file = "README.md"}
dependencies = {file = ["requirements.txt"]}
classifiers = {file = ["classifiers.txt"]}
