[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hqx"
description = "The hqx upscaling algorithm in Python"
readme = "README.md"
requires-python = ">=3.10"
version = "1.0"
license = {text = "LGPL-2.1-only"}
authors = [{name = "WhoAteMyButter"}]
keywords = [
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Typing :: Typed",
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Other Audience",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Lesser General Public License v2 (LGPLv2)",
    "Topic :: Artistic Software",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Multimedia"
]
dependencies = [
    "Pillow >= 9.3.0"
]

[project.urls]
Source = "https://gitlab.com/whoatemybutter/hqx_python"
Changelog = "https://gitlab.com/whoatemybutter/hqx_python/-/blob/master/CHANGELOG.md"
Issues = "https://gitlab.com/whoatemybutter/hqx_python/-/issues"

[tool.black]
line-length = 120

[tool.pylint."MASTER"]
jobs = 10
py-version = "3.10"
max-line-length = 120
# Need these because impossible to implement otherwise
max-module-lines = 4500
max-branches = 520
max-statements = 4000

[tool.mypy]
ignore_missing_imports = true

[tool.setuptools.package-data]
hqx = ["py.typed"]
