
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-14T12:47:28-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "514cc1348bfc17eea8fae32743f5e95784b0e259",
 "version": "0.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
