
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-13T06:11:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "201ecde2cfd832aa83fe9795a00e0e91645c5a54",
 "version": "1.18.2.post0.dev82"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
