
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-14T15:24:15-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "6af6b242f9f495e15462823ee83f4201e4dfb2e8",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
