
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-13T05:16:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9401f05cc4d56a0b679e9296fefab0849e2d9e19",
 "version": "1.18.2.post0.dev76"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
