[build-system]
requires = ["setuptools>=61.0", "requests"]
build-backend = "setuptools.build_meta"
[project]
name = "speeshare"
version = "0.0.1"
authors = [
  { name="Fander Company", email="help@fandercompany.ru" },
]
description = "A small FILEtoURL package."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Fander-Company/speeshare"
"Bug Tracker" = "https://github.com/Fander-Company/speeshare/issues"