
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-10T13:26:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3953fb3d0ed6df27894b0a6193db8ade94950f91",
 "version": "3.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
