
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-12T12:30:03-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c8ff1238f7134612f1fcde49318754cdce09ff0a",
 "version": "0.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
