
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-13T13:25:29-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "52acb3b907cfb94a4e39273a2f29142c33a5b729",
 "version": "0.3.0.post0.dev36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
