[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "frappe"
version = "0.0.1"
authors = [
  { name="Frappe", email="developers@frappe.io" },
]
description = "Frappe placeholder package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
