[tool.poetry]
name = "ttos-py"
version = "0.1.0"
description = ""
authors = ["fixees"]
readme = "README.md"
packages = [{include = "TtoS.py"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
