[tool.poetry]
name = "celery-pubsub"
version = "1.0.0"
description = "A Publish and Subscribe library for Celery"
authors = ["Samuel GIFFARD <mulugruntz@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "2.7,^3.5"
celery = "^3.1.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
coverage = "5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
