[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mistery"
version = "0.0.3"
authors = [
  { name="Warrick Ball" },
]
dependencies = ["requests", "numpy"]
description = "Python module for retrieving data from the MESA Isochrones and Stellar Tracks (MIST) database of stellar models."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://warrickball.gitlab.io/mistery"
"Bug Tracker" = "https://gitlab.com/warrickball/mistery/issues"
