name: Publish Package

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:tricksterguy87/complx
        sudo apt-get update -qq
        sudo apt-get install -y castxml libpython3-dev libboost-python-dev liblc3-dev
        sudo python3 -m pip install --upgrade pip
        sudo pip3 install --upgrade scikit-build pygccxml pyplusplus wheel pip setuptools
    - name: Build Dist
      run: |
        sudo python3 setup.py sdist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
