[tool.poetry]
name = "imbox_sis"
version = "0.9.11"
description = ""
authors = ["zmcoding <841699090@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
chardet = "^5.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
