[tool.poetry]
name = "lets-debug-helper"
version = "1.5.2"
description = "This is a cli tool that interacts with the Let's Debug API"
authors = ["Jeffrey Crane <jediknight11206@gmail.com>"]
license = "License :: OSI Approved :: MIT License"
include = ["README.md"]
packages = [
    { include = "letsdebughelper" },
]

[tool.yapf]
based_on_style = "pep8"
column_limit = 120

[tool.coverage.run]
relative_files = true

[tool.poetry.scripts]
lets-debug = "letsdebughelper.letsdebug:main"

[tool.poetry.dependencies]
python = "^3.9"
argparse = "^1.4.0"
requests = "^2.27.1"
six = "^1.16.0"
rich = "^12.6.0"

[tool.poetry.group.dev.dependencies]
mock = "^4.0.3"
argparse = "^1.4.0"
parameterized = "^0.8.1"
flake8 = "^5.0.4"
coveralls = "^3.3.1"
pytest = "^7.1.2"
pytest-cov = "^4.0.0"
yapf = "^0.32.0"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
