[build-system]
requires = ["setuptools>=50.3.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "adetfs"
version = "1.2.0"
description = "Automated Data Extraction Tool for Fitbit Server"
readme = "README.md"
authors = [{ name = "herissonbleu", email = "herisson_bleu@outlook.com" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent"
]
keywords = ["fitbit", "data extraction", "automation","batch","research"]
dependencies = [
    "CherryPy >= 18.6.1",
    "fitbit >= 0.3.1",
    "pandas >= 1.4.1",
    "toml >= 0.10.2",
    "tqdm >= 4.64.0",
    "urllib3 >= 1.26.8",
    "setuptools >= 50.3.1",
    "oauthlib >= 3.1.1",
    "requests >= 2.27.1"
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = ["unittest","pip-tools","bumpver"]

[project.urls]
Homepage = "https://github.com/herissonbleu/adetfs-fitbit-tool"

[project.scripts]
adetfs_tool = "adetfs.__main__:main"
[tool.bumpver]
current_version = "1.2.0"
version_pattern = "MAJOR.MINOR.PATCH[TAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"','version = "{version}"',
]
"src/adetfs/__init__.py" = ["{version}"]
"setup.py" = [
    "{version}",
    "{pep440_version}",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["properties_ini_example.ini","CITATION.cff","tests","Licenses"]

