[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "GenomeManagement"
version = "1.4.0"
authors = [
  { name="Nattawet Sriwichai", email="nattawet.sri@kmutt.ac.th" },
]
description = "Genome Management Package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/evolu-tion/GenomeManagement"
"Bug Tracker" = "https://github.com/evolu-tion/GenomeManagement/issues"