[tool.black]
target-version = ["py39"]

[tool.isort]
profile = "black"
force_sort_within_sections = true
combine_as_imports = true

[tool.pylint.MASTER]
py-version = "3.9"
ignore = [
    "tests",
]
jobs = 2

[tool.pylint.BASIC]
good-names = [
    "_",
    "i",
    "e",
    "j",
    "k",
    "v",
    "ip",
    "dt",
    "id",
]

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "abstract-method",
    "unused-argument",
    "too-many-arguments",
    "too-few-public-methods",
    "too-many-instance-attributes",
    "duplicate-code",
]

[tool.mypy]
ignore_missing_imports = true
no_strict_optional = true
exclude = [
    "build",
    ".tox",
    ".git",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
