[tool.poetry]
name = "configloaders"
version = "0.3.3"
description = "Load configurations from various types of configuration files"
authors = ["jawide <jawide@qq.com>"]
readme = "README.md"
packages = [{include = "configloaders"}]

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
