[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Rajasthan"
version = "0.0.1"
authors = [
  { name="Jay Singh", email="jaysinghdulrasar@gmail.com" },
]
description = "<>"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Instagram" = "https://www.instagram.com/ij.a.y.s.i.n.g.h/"
"WebApp" = "https://bias-ai.web.app/"