[tool.poetry]
name = "git-analytics"
version = "0.1.0"
description = "The detailed analysis tool for git repositories."
authors = ["n0rfas <antsa@yandex.ru>"]
license = "MIT"
readme = "README.md"
packages = [{include = "git_analytics"}]

[tool.poetry.dependencies]
python = "3.7.15"
falcon = "^3.1.1"
GitPython = "^3.1.30"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
