"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.wrappers_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class NotificationId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___NotificationId = NotificationId

class ProcessorId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___ProcessorId = ProcessorId

class RegistrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> global___ProcessorId: ...
    @property
    def parameters(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(self,
        *,
        id: typing.Optional[global___ProcessorId] = ...,
        parameters: typing.Optional[google.protobuf.struct_pb2.Struct] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","parameters",b"parameters"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","parameters",b"parameters"]) -> None: ...
global___RegistrationRequest = RegistrationRequest

class ProcessorKey(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    INNER_ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> global___ProcessorId: ...
    inner_id: builtins.int
    def __init__(self,
        *,
        id: typing.Optional[global___ProcessorId] = ...,
        inner_id: builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","inner_id",b"inner_id"]) -> None: ...
global___ProcessorKey = ProcessorKey

class AwaitNotificationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TIMEOUT_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    @property
    def timeout(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def id(self) -> global___NotificationId: ...
    def __init__(self,
        *,
        timeout: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        id: typing.Optional[global___NotificationId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","timeout",b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","timeout",b"timeout"]) -> None: ...
global___AwaitNotificationRequest = AwaitNotificationRequest

class NotificationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    EXPECTED_EVENTS_FIELD_NUMBER: builtins.int
    name: typing.Text
    @property
    def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def expected_events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ExpectedEvent]: ...
    def __init__(self,
        *,
        name: typing.Text = ...,
        description: typing.Optional[google.protobuf.wrappers_pb2.StringValue] = ...,
        expected_events: typing.Optional[typing.Iterable[global___ExpectedEvent]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["description",b"description"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description",b"description","expected_events",b"expected_events","name",b"name"]) -> None: ...
global___NotificationRequest = NotificationRequest

class ExpectedEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TYPE_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    @property
    def type(self) -> global___EventType: ...
    count: builtins.int
    def __init__(self,
        *,
        type: typing.Optional[global___EventType] = ...,
        count: builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["count",b"count","type",b"type"]) -> None: ...
global___ExpectedEvent = ExpectedEvent

class EventType(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___EventType = EventType
