# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from th2_grpc_sense import sense_pb2 as th2__grpc__sense_dot_sense__pb2


class SenseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyOnEvents = channel.unary_unary(
                '/th2.sense.Sense/NotifyOnEvents',
                request_serializer=th2__grpc__sense_dot_sense__pb2.NotificationRequest.SerializeToString,
                response_deserializer=th2__grpc__sense_dot_sense__pb2.NotificationId.FromString,
                )
        self.AwaitNotificationOnEvents = channel.unary_unary(
                '/th2.sense.Sense/AwaitNotificationOnEvents',
                request_serializer=th2__grpc__sense_dot_sense__pb2.AwaitNotificationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RegisterProcessor = channel.unary_unary(
                '/th2.sense.Sense/RegisterProcessor',
                request_serializer=th2__grpc__sense_dot_sense__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=th2__grpc__sense_dot_sense__pb2.ProcessorKey.FromString,
                )
        self.UnregisterProcessor = channel.unary_unary(
                '/th2.sense.Sense/UnregisterProcessor',
                request_serializer=th2__grpc__sense_dot_sense__pb2.ProcessorKey.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class SenseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NotifyOnEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AwaitNotificationOnEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterProcessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterProcessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SenseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyOnEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyOnEvents,
                    request_deserializer=th2__grpc__sense_dot_sense__pb2.NotificationRequest.FromString,
                    response_serializer=th2__grpc__sense_dot_sense__pb2.NotificationId.SerializeToString,
            ),
            'AwaitNotificationOnEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.AwaitNotificationOnEvents,
                    request_deserializer=th2__grpc__sense_dot_sense__pb2.AwaitNotificationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RegisterProcessor': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterProcessor,
                    request_deserializer=th2__grpc__sense_dot_sense__pb2.RegistrationRequest.FromString,
                    response_serializer=th2__grpc__sense_dot_sense__pb2.ProcessorKey.SerializeToString,
            ),
            'UnregisterProcessor': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterProcessor,
                    request_deserializer=th2__grpc__sense_dot_sense__pb2.ProcessorKey.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'th2.sense.Sense', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sense(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NotifyOnEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.sense.Sense/NotifyOnEvents',
            th2__grpc__sense_dot_sense__pb2.NotificationRequest.SerializeToString,
            th2__grpc__sense_dot_sense__pb2.NotificationId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AwaitNotificationOnEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.sense.Sense/AwaitNotificationOnEvents',
            th2__grpc__sense_dot_sense__pb2.AwaitNotificationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterProcessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.sense.Sense/RegisterProcessor',
            th2__grpc__sense_dot_sense__pb2.RegistrationRequest.SerializeToString,
            th2__grpc__sense_dot_sense__pb2.ProcessorKey.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnregisterProcessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.sense.Sense/UnregisterProcessor',
            th2__grpc__sense_dot_sense__pb2.ProcessorKey.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
