[tool.black]
line-length = 88
target-version = ["py38"]

[tool.isort]
profile = "black"

[tool.poetry]
name = "freakble"
version = "0.3.0"
description = "A simple tool to send messages into FreakWAN over Bluetooth low energy."
authors = ["Daniele Tricoli <eriol@mornie.org>"]
readme = "README.md"
repository = "https://noa.mornie.org/eriol/freakble"
packages = [{include = "freakble", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
ble-serial = "^2.7.0"
click = "^8.1.3"
prompt-toolkit = "^3.0.36"

[tool.poetry.scripts]
freakble = "freakble.main:run"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
