name: Lint code

on: [workflow_dispatch, push]

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        python -m pip install pre-commit
        pre-commit install
    - name: Run all pre-commit hooks
      run: |
        pre-commit run --all-files
