
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-10T11:24:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b385f50617f487fadf4facc06e6be5b68d1ffbd2",
 "version": "1.50.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
