[tool.poetry]
name = "cpmax-toolbox"
version = "0.2.0"
description = ""
authors = ["JRoseCPMax <j.rose@cpmax.com>"]
readme = "README.md"
packages = [{include = "cpmax_toolbox"}]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
requests = "^2.28.2"
pytz = "^2022.7.1"
pandas = "^1.5.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
