DATASET:
  TRAIN: "datase/masks"
  VAL: "datase/masks"
  NAMES: "configs/coco.names"
MODEL:
  NC: 2
  INPUT_WIDTH: 352
  INPUT_HEIGHT: 352
TRAIN:
  LR: 0.001
  THRESH: 0.25
  WARMUP: true
  BATCH_SIZE: 6
  END_EPOCH: 300
  MILESTIONES:
    - 100
    - 200
    - 250