[tool.poetry]
name = "skinu"
version = "0.0.1.1"
description = "skadi support library package"
authors = ["JeongHun Lee"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
autopep8 = "2.0.1"
colorama = "0.4.6"
colorlog = "^6.7.0"
couchbase = "^4.1.2"
numpy = "^1.24.2"
pandas = "^1.5.3"
pycodestyle = "^2.10.0"
python-dateutil = "^2.8.2"
pytz = "^2022.7.1"
six = "^1.16.0"
tomli = "^2.0.1"
twine = "^4.0.2"


[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
