[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jeremydimond.python-hello-world"
version = "0.0.2"
description = "Hello world project to test built, test, publish, etc."
readme = "README.md"
authors = [{ name = "Jeremy Dimond", email = "jeremy@jeremydimond.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["jeremydimond", "helloworld", "hello", "world"]
requires-python = ">=3.9"
dependencies = []

[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "pytest-tldr", "bumpver", "build", "twine"]

[project.scripts]
say-hello = "helloworld.greeter:main_cli"

[project.urls]
Homepage = "https://github.com/jeremydimond/python-hello-world"

[tool.bumpver]
current_version = "0.0.2"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
"README.md" = [
    "Version: {version}",
]
