# Local file system configuration ##############################################

web_temp_dir:
  - /
  - Library
  - WebServer
  - Documents
  - Sites
  - progenetix
  - tmp

################################################################################

byc_root_pars:

  args: ~
  env: "server"
  request_path_root: "beacon"
  request_entity_path_id: ~
  request_entity_path_id_value: ~
  response_entity_path_id: ~
  request_entity_id: ~
  response_entity_id: ~
  response_entity: {}
  service_config: {}
  filters: []
  method: ""
  output: ""
  form_data: {}
  query_meta: {}
  original_queries: ~
  script_args: []
  include_handovers: False
  empty_query_all_count: False
  test_mode: False
  check_args: True
  debug_mode: False
  download_mode: False
  errors: []

schemas_root:
  - schemas

framework_path:
  - schemas
  - framework
  - json

default_model_path:
  - schemas
  - models
  - json
  - progenetix-model

schemas_paths:
  description: >-
    path elements as list from `schemas_root`
  items:
    - - models
      - json
      - progenetix-model
    - - models
      - json
      - progenetix-model
      - common
    - - models
      - json
      - progenetix-service-schemas
    - - models
      - json
      - progenetix-database-schemas
    - - framework
      - json
      - common
    - - framework
      - json
      - configuration
    - - framework
      - json
      - requests
    - - framework
      - json
      - responses
    - - framework
      - json
      - responses
      - sections

form_list_pars:
  description: >-
    form parameters which are processed as list
  items:
    - start
    - end
    - datasetIds
    - filters
    - ids
    - biosampleIds
    - variantIds
    - individualIds
    - callsetIds
    - analysisIds
    - collationTypes
    - selectedBeacons

resource_urls:
  ncbi_geosoft: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?form=text&acc=
  ncbi_geoweb: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=
  europepmc_pmid: https://europepmc.org/article/MED/
  cellosaurus_web: https://web.expasy.org/cellosaurus/

# dataset_ids here are used for db management; the information used by Beacon
# is defined separately
dataset_ids:
  - progenetix
  - cellz
  # - cellosaurus
  # - 1000genomesDRAGEN

queried_collections:
  - biosamples
  - callsets
  - individuals
  - variants
  - collations
  - frequencymaps
  - publications

info_db: progenetix
collations_coll: collations
frequencymaps_coll: frequencymaps
collations_source: biosamples
ontologymaps_coll: ontologymaps
beacon_info_coll: beaconinfo
beacon_counts:
  individual_count:
    collection: individuals
    info_key: individuals
    h->o_key: individuals._id
  sample_count:
    collection: biosamples
    info_key: biosamples
    h->o_key: biosamples._id
  variant_count:
    collection: variants
    info_key: variants_distinct
    h->o_key: variants.variant_internal_id
  call_count:
    collection: variants
    info_key: variants
    h->o_key: variants._id
handover_coll: querybuffer
genespans_coll: genespans

filter_flags:
  logic: '$and'
  precision: exact #'start'
  include_descendant_terms: True

plot_pars:
  dotalpha: 0.2
  color_var_snv_hex: '#EE00DD'
  color_var_snv_rgb: '2380221'
  color_var_break_hex: '#EE00DD'
  color_var_break_rgb: '2380221'
  color_var_dup_hex: '#FFC633'
  color_var_dup_rgb: '25519851'
  color_var_del_hex: '#33A0FF'
  color_var_del_rgb: '51160255'
  color_var_loh_hex: '#9326de'
  color_var_loh_rgb: '14738222'
  color_var_amp_hex: '#FF6600'
  color_var_amp_rgb: '2551020'
  color_var_homoloss_hex: '#0033CC'
  color_var_homoloss_rgb: '051204'
