
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-14T10:34:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e58d21507ae20ef2b429e227f5c0fafe48c21a2",
 "version": "0.74"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
