# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import typing_extensions

from ...core.datetime_utils import serialize_datetime
from ..util.content import Content
from ..util.with_embedding_type import WithEmbeddingType


class DocumentCreateRequest(WithEmbeddingType):
    source_url: str
    content: Content
    tags: typing.List[str]
    name: str

    class Partial(WithEmbeddingType.Partial):
        source_url: typing_extensions.NotRequired[str]
        content: typing_extensions.NotRequired[Content]
        tags: typing_extensions.NotRequired[typing.List[str]]
        name: typing_extensions.NotRequired[str]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
