VERSION_YEAR = 2023
VERSION_MONTH = int('02')
VERSION_DAY = int('12')
VERSION_HOUR = int('02')
VERSION_MINUTE = int('55')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202302120255
version_date = '2023/02/12 02:55'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
