[build-system]
requires = ["setuptools>=61.0"]
build-backend="setuptools.build_meta"
[project]
name = "sky_test"
version = "1.0"
authors = [
  { name="Example Author", email="xjgis@126.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]