PLACES = {
    "babina greda": ("Babina Greda", "Babina_Greda"),
    "bakar": ("Bakar", "Bakar"),
    "baška voda": ("Baška Voda", "Baska_Voda"),
    "baška": ("Baška", "Baska"),
    "baške oštarije": ("Baške Oštarije", "Baske_Ostarije"),
    "bednja": ("Bednja", "Bednja"),
    "beli manastir": ("Beli Manastir", "Beli_Manastir"),
    "belišće": ("Belišće", "Belisce"),
    "benkovac": ("Benkovac", "Benkovac"),
    "bilogora": ("Bilogora", "Bilogora"),
    "biograd": ("Biograd", "Biograd"),
    "bisko": ("Bisko", "Bisko"),
    "bistra": ("Bistra", "Bistra"),
    "bizovac": ("Bizovac", "Bizovac"),
    "biševo": ("Biševo", "Bisevo"),
    "bjelolasica": ("Bjelolasica", "Bjelolasica-Begovo_R"),
    "bjelolasica - begovo razdolje": ("Bjelolasica - Begovo Razdolje", "Bjelolasica-Begovo_R"),
    "bjelovar": ("Bjelovar", "Bjelovar"),
    "blato": ("Blato", "Blato"),
    "bol": ("Bol", "Bol"),
    "bosiljevo": ("Bosiljevo", "Bosiljevo"),
    "božava": ("Božava", "Bozava"),
    "brela": ("Brela", "Brela"),
    "breznički hum": ("Breznički Hum", "Breznicki_Hum"),
    "brijuni": ("Brijuni", "NP_Brijuni"),
    "brinje": ("Brinje", "Brinje"),
    "brodski stupnik": ("Brodski Stupnik", "Brodski_Stupnik"),
    "buje": ("Buje", "Buje"),
    "buzet": ("Buzet", "Buzet"),
    "cavtat": ("Cavtat", "Cavtat"),
    "cista provo": ("Cista Provo", "Cista_Provo"),
    "cres": ("Cres", "Cres"),
    "crikvenica": ("Crikvenica", "Crikvenica"),
    "crni lug": ("Crni Lug", "Crni_Lug-NP_Risnjak"),
    "dalj": ("Dalj", "Dalj"),
    "darda": ("Darda", "Darda"),
    "daruvar": ("Daruvar", "Daruvar"),
    "davor": ("Davor", "Davor"),
    "delnice": ("Delnice", "Delnice"),
    "donja dubrava": ("Donja Dubrava", "Donja_Dubrava"),
    "donja stubica": ("Donja Stubica", "Donja_Stubica"),
    "donji lapac": ("Donji Lapac", "Donji_Lapac"),
    "donji miholjac": ("Donji Miholjac", "Donji_Miholjac"),
    "drniš": ("Drniš", "Drnis"),
    "drvenik": ("Drvenik", "Drvenik"),
    "dubrovnik čilipi": ("Dubrovnik Čilipi", "Zracna_luka_Dubrovni"),
    "dubrovnik": ("Dubrovnik", "Dubrovnik"),
    "duga resa": ("Duga Resa", "Duga_Resa"),
    "dugo selo": ("Dugo Selo", "Dugo_Selo"),
    "dugopolje": ("Dugopolje", "Dugopolje"),
    "dvor na uni": ("Dvor na Uni", "Dvor"),
    "fazana": ("Fazana", "Fazana"),
    "fužine": ("Fužine", "Fuzine"),
    "garešnica": ("Garešnica", "Garesnica"),
    "generalski stol": ("Generalski Stol", "Generalski_Stol"),
    "glina": ("Glina", "Glina"),
    "goričan": ("Goričan", "Gorican"),
    "gornja ploča": ("Gornja Ploča", "Gornja_Ploca"),
    "gospić": ("Gospić", "Gospic"),
    "goveđari": ("Goveđari", "Govedari"),
    "gradac": ("Gradac", "Gradac"),
    "gradina": ("Gradina", "Gradina"),
    "gradište": ("Gradište", "Gradiste"),
    "gračac": ("Gračac", "Gracac"),
    "grožnjan": ("Grožnjan", "Groznjan"),
    "grubišno polje": ("Grubišno Polje", "Grubisno_Polje"),
    "gruda": ("Gruda", "Gruda"),
    "gunja": ("Gunja", "Gunja"),
    "gvozd": ("Gvozd", "Gvozd"),
    "hreljin": ("Hreljin", "Hreljin"),
    "hrvatska dubica": ("Hrvatska Dubica", "Hrvatska_Dubica"),
    "hrvatska kostajnica": ("Hrvatska Kostajnica", "Hrvatska_Kostajnica"),
    "hvar": ("Hvar", "Hvar"),
    "ilok": ("Ilok", "Ilok"),
    "imotski": ("Imotski", "Imotski"),
    "ist": ("Ist", "Ist"),
    "ivanec": ("Ivanec", "Ivanec"),
    "ivanić grad": ("Ivanić Grad", "Ivanic_Grad"),
    "jablanac": ("Jablanac", "Jablanac"),
    "jasenovac": ("Jasenovac", "Jasenovac"),
    "jastrebarsko": ("Jastrebarsko", "Jastrebarsko"),
    "jelenje": ("Jelenje", "Jelenje"),
    "jelsa": ("Jelsa", "Jelsa"),
    "josipdol": ("Josipdol", "Josipdol"),
    "kanfanar": ("Kanfanar", "Kanfanar"),
    "karlobag": ("Karlobag", "Karlobag"),
    "karlovac": ("Karlovac", "Karlovac"),
    "kastav": ("Kastav", "Kastav"),
    "klanjec": ("Klanjec", "Klanjec"),
    "klek": ("Klek", "Klek"),
    "kloštar podravski": ("Kloštar Podravski", "Klostar_Podravski"),
    "knin": ("Knin", "Knin"),
    "koločep": ("Koločep", "Kolocep"),
    "komin": ("Komin", "Komin"),
    "komiža": ("Komiža", "Komiza"),
    "koprivnica": ("Koprivnica", "Koprivnica"),
    "korenica": ("Korenica", "Korenica"),
    "korita": ("Korita", "Korita-NP_Mljet"),
    "kornati": ("Kornati", "NP_Kornati"),
    "korčula": ("Korčula", "Korcula"),
    "kostrena": ("Kostrena", "Kostrena"),
    "kraljevica": ("Kraljevica", "Kraljevica"),
    "krapina": ("Krapina", "Krapina"),
    "krasno polje": ("Krasno Polje", "Krasno-NP_Sjeverni_V"),
    "kravarsko": ("Kravarsko", "Kravarsko"),
    "križevci": ("Križevci", "Krizevci"),
    "križišće": ("Križišće", "Krizisce"),
    "krk most": ("Krk most", "Most_Krk"),
    "krk": ("Krk", "Krk"),
    "kukuljanovo": ("Kukuljanovo", "Kukuljanovo"),
    "kuna": ("Kuna", "Kuna"),
    "kutina": ("Kutina", "Kutina"),
    "kutjevo": ("Kutjevo", "Kutjevo"),
    "labin": ("Labin", "Labin"),
    "lastovo": ("Lastovo", "Lastovo"),
    "lekenik": ("Lekenik", "Lekenik"),
    "lipik": ("Lipik", "Lipik"),
    "lipovac": ("Lipovac", "Lipovac"),
    "lički osik": ("Lički Osik", "Licki_Osik"),
    "lopar": ("Lopar", "Lopar"),
    "lopud": ("Lopud", "Lopud"),
    "lovran": ("Lovran", "Lovran"),
    "lovreć": ("Lovreć", "Lovrec"),
    "lozovac": ("Lozovac", "Lozovac-NP_Krka"),
    "lubenice": ("Lubenice", "Lubenice"),
    "ludbreg": ("Ludbreg", "Ludbreg"),
    "lumbarda": ("Lumbarda", "Lumbarda"),
    "lupoglav": ("Lupoglav", "Lupoglav"),
    "macelj": ("Macelj", "Macelj"),
    "makarska": ("Makarska", "Makarska"),
    "mali lošinj - zračna luka": ("Mali Lošinj - Zračna Luka", "Zracna_luka_Mali_Los"),
    "mali lošinj": ("Mali Lošinj", "Mali_Losinj"),
    "malinska": ("Malinska", "Malinska"),
    "marija bistrica": ("Marija Bistrica", "Marija_Bistrica"),
    "maslenica": ("Maslenica", "Maslenica"),
    "matulji": ("Matulji", "Matulji"),
    "medulin": ("Medulin", "Medulin"),
    "metković": ("Metković", "Metkovic"),
    "milna": ("Milna", "Milna"),
    "molat": ("Molat", "Molat"),
    "molve": ("Molve", "Molve"),
    "motovun": ("Motovun", "Motovun"),
    "mošćenička draga": ("Mošćenička Draga", "Moscenicka_Draga"),
    "mrkopalj": ("Mrkopalj", "Mrkopalj"),
    "mursko središće": ("Mursko Središće", "Mursko_Sredisce"),
    "murter": ("Murter", "Murter"),
    "našice": ("Našice", "Nasice"),
    "nerezine": ("Nerezine", "Nerezine"),
    "nin": ("Nin", "Nin"),
    "nova gradiška": ("Nova Gradiška", "Nova_Gradiska"),
    "nova kapela": ("Nova Kapela", "Nova_Kapela"),
    "novalja": ("Novalja", "Novalja"),
    "novi marof": ("Novi Marof", "Novi_Marof"),
    "novi vinodolski": ("Novi Vinodolski", "Novi_Vinodolski"),
    "novigrad istra": ("Novigrad Istra", "Novigrad"),
    "novska": ("Novska", "Novska"),
    "obrovac": ("Obrovac", "Obrovac"),
    "ogulin": ("Ogulin", "Ogulin"),
    "okučani": ("Okučani", "Okucani"),
    "olib": ("Olib", "Olib"),
    "omiš": ("Omiš", "Omis"),
    "opatija": ("Opatija", "Opatija"),
    "opuzen": ("Opuzen", "Opuzen"),
    "orahovica": ("Orahovica", "Orahovica"),
    "orebić": ("Orebić", "Orebic"),
    "osijek klisa": ("Osijek Klisa", "Zracna_luka_Osijek"),
    "osijek": ("Osijek", "Osijek"),
    "otočac": ("Otočac", "Otocac"),
    "ozalj": ("Ozalj", "Ozalj"),
    "pag most": ("Pag most", "Most_Pag"),
    "pag": ("Pag", "Pag"),
    "pakoštane": ("Pakoštane", "Pakostane"),
    "pakrac": ("Pakrac", "Pakrac"),
    "palagruža": ("Palagruža", "Palagruza"),
    "pazin": ("Pazin", "Pazin"),
    "perušić": ("Perušić", "Perusic"),
    "petrinja": ("Petrinja", "Petrinja"),
    "pirovac": ("Pirovac", "Pirovac"),
    "pisarovina": ("Pisarovina", "Pisarovina"),
    "pitomača": ("Pitomača", "Pitomaca"),
    "pleternica": ("Pleternica", "Pleternica"),
    "plitvička jezera": ("Plitvička jezera", "NP_Plitvicka_jezera"),
    "ploče": ("Ploče", "Ploce"),
    "podgora": ("Podgora", "Zivogosce"),
    "podstrana": ("Podstrana", "Podstrana"),
    "podsused": ("Podsused", "Podsused"),
    "pokupsko": ("Pokupsko", "Pokupsko"),
    "polača": ("Polača", "Polaca"),
    "popovača": ("Popovača", "Popovaca"),
    "poreč": ("Poreč", "Porec"),
    "porozina": ("Porozina", "Porozina"),
    "posedarje": ("Posedarje", "Posedarje"),
    "postira": ("Postira", "Postira"),
    "povile": ("Povile", "Povile"),
    "povlja": ("Povlja", "Povlja"),
    "povljana": ("Povljana", "Povljana"),
    "požega": ("Požega", "Pozega"),
    "pregrada": ("Pregrada", "Pregrada"),
    "prelog": ("Prelog", "Prelog"),
    "prevlaka": ("Prevlaka", "Prevlaka"),
    "prgomet": ("Prgomet", "Prgomet"),
    "primošten": ("Primošten", "Primosten"),
    "prizna": ("Prizna", "Prizna"),
    "pula loborika": ("Pula Loborika", "Zracna_luka_Pula"),
    "pula": ("Pula", "Pula"),
    "puntijarka": ("Puntijarka", "Puntijarka"),
    "rab": ("Rab", "Rab"),
    "ravna gora": ("Ravna Gora", "Ravna_Gora"),
    "ravča": ("Ravča", "Ravca"),
    "ražanac": ("Ražanac", "Razanac"),
    "rijeka omišalj": ("Rijeka Omišalj", "Zracna_luka_Rijeka"),
    "rijeka": ("Rijeka", "Rijeka"),
    "rogotin": ("Rogotin", "Rogotin"),
    "rogoznica": ("Rogoznica", "Rogoznica"),
    "rovinj": ("Rovinj", "Rovinj"),
    "rugvica": ("Rugvica", "Rugvica"),
    "rupa": ("Rupa", "Rupa"),
    "sali": ("Sali", "Sali"),
    "samobor": ("Samobor", "Samobor"),
    "savudrija": ("Savudrija", "Savudrija"),
    "selce": ("Selce", "Selce"),
    "senj": ("Senj", "Senj"),
    "sesvete": ("Sesvete", "Sesvete"),
    "severin na kupi": ("Severin na Kupi", "Severin_na_Kupi"),
    "silba": ("Silba", "Silba"),
    "sinj": ("Sinj", "Sinj"),
    "sisak": ("Sisak", "Sisak"),
    "skrad": ("Skrad", "Skrad"),
    "skradin": ("Skradin", "Skradin"),
    "slano": ("Slano", "Slano"),
    "slatina": ("Slatina", "Slatina"),
    "slavonski brod": ("Slavonski Brod", "Slavonski_Brod"),
    "slavonski šamac": ("Slavonski Šamac", "Slavonski_Samac"),
    "slunj": ("Slunj", "Slunj"),
    "solin": ("Solin", "Solin"),
    "split resnik": ("Split Resnik", "Zracna_luka_Split"),
    "split": ("Split", "Split"),
    "sredanci": ("Sredanci", "Sredanci"),
    "stari grad": ("Stari Grad", "Starigrad"),
    "starigrad-paklenica": ("Starigrad-Paklenica", "Starigrad-NP_Pakleni"),
    "ston": ("Ston", "Ston"),
    "stružec": ("Stružec", "Struzec"),
    "suhopolje": ("Suhopolje", "Suhopolje"),
    "sukošan": ("Sukošan", "Sukosan"),
    "sumartin": ("Sumartin", "Sumartin"),
    "supetar": ("Supetar", "Supetar"),
    "sutivan": ("Sutivan", "Sutivan"),
    "sveta nedelja": ("Sveta Nedelja", "Sveta_Nedjelja"),
    "sveti ivan zelina": ("Sveti Ivan Zelina", "Sveti_Ivan_Zelina"),
    "sveti ivan žabno": ("Sveti Ivan Žabno", "Sveti_Ivan_Zabno"),
    "sveti križ začretje": ("Sveti Križ Začretje", "Sveti_Kriz_Zacretje"),
    "sveti martin": ("Sveti Martin", "Sveti_Martin"),
    "sveti rok": ("Sveti Rok", "Sveti_Rok"),
    "tisno": ("Tisno", "Tisno"),
    "tkon": ("Tkon", "Tkon"),
    "topusko": ("Topusko", "Topusko"),
    "tovarnik": ("Tovarnik", "Tovarnik"),
    "trakošćan": ("Trakošćan", "Trakoscan"),
    "tribunj": ("Tribunj", "Tribunj"),
    "trilj": ("Trilj", "Trilj"),
    "trogir": ("Trogir", "Trogir"),
    "trstenik": ("Trstenik", "Trstenik"),
    "trsteno": ("Trsteno", "Trsteno"),
    "tuhelj": ("Tuhelj", "Tuhelj"),
    "tučepi": ("Tučepi", "Tucepi"),
    "udbina": ("Udbina", "Udbina"),
    "ugljan": ("Ugljan", "Ugljan"),
    "umag": ("Umag", "Umag"),
    "unije": ("Unije", "Unije"),
    "urinj": ("Urinj", "Urinj"),
    "uskoplje": ("Uskoplje", "Uskoplje"),
    "učka": ("Učka", "PP_Ucka"),
    "valpovo": ("Valpovo", "Valpovo"),
    "varaždin": ("Varaždin", "Varazdin"),
    "varaždinske toplice": ("Varaždinske Toplice", "Varazdinske_Toplice"),
    "vardarac": ("Vardarac", "Vardarac-Kopacki_rit"),
    "vela luka": ("Vela Luka", "Vela_Luka"),
    "velika gorica": ("Velika Gorica", "Velika_Gorica"),
    "velika": ("Velika", "Velika"),
    "veliko trgovišće": ("Veliko Trgovišće", "Veliko_Trgovisce"),
    "vinkovci": ("Vinkovci", "Vinkovci"),
    "vir": ("Vir", "Vir"),
    "virje": ("Virje", "Virje"),
    "virovitica": ("Virovitica", "Virovitica"),
    "vis": ("Vis", "Vis"),
    "vodice": ("Vodice", "Vodice"),
    "vodnjan": ("Vodnjan", "Vodnjan"),
    "vojnić": ("Vojnić", "Vojnic"),
    "vrbovec": ("Vrbovec", "Vrbovec"),
    "vrbovsko": ("Vrbovsko", "Vrbovsko"),
    "vrgorac": ("Vrgorac", "Vrgorac"),
    "vrlika": ("Vrlika", "Vrlika"),
    "vrpolje": ("Vrpolje", "Vrpolje"),
    "vrsar": ("Vrsar", "Vrsar"),
    "vukova gorica": ("Vukova Gorica", "Vukova_Gorica"),
    "vukovar": ("Vukovar", "Vukovar"),
    "zabok": ("Zabok", "Zabok"),
    "zadar zemunik": ("Zadar Zemunik", "Zracna_luka_Zadar"),
    "zadar": ("Zadar", "Zadar"),
    "zagreb - zračna luka": ("Zagreb - Zračna Luka", "Zracna_luka_Zagreb"),
    "novi zagreb": ("Zagreb - Novi Zagreb", "Novi_Zagreb"),
    "zagreb - novi zagreb": ("Novi Zagreb", "Novi_Zagreb"),
    "zagreb": ("Zagreb Grič", "Zagreb"),
    "zagreb grič": ("Zagreb Grič", "Zagreb"),
    "zagreb maksimir": ("Zagreb Maksimir", "Zagreb_Maksimir"),
    "zagvozd": ("Zagvozd", "Zagvozd"),
    "zaprešić": ("Zaprešić", "Zapresic"),
    "zaton obrovački": ("Zaton Obrovački", "Zaton"),
    "zavižan": ("Zavižan", "Zavizan"),
    "zlarin": ("Zlarin", "Zlarin"),
    "zlatar": ("Zlatar", "Zlatar"),
    "čabar": ("Čabar", "cabar"),
    "čakovec": ("Čakovec", "Cakovec"),
    "čavle": ("Čavle", "Cavle"),
    "čazma": ("Čazma", "cazma"),
    "čačinci": ("Čačinci", "cacinci"),
    "đakovo": ("Đakovo", "Dakovo"),
    "đurmanec": ("Đurmanec", "Durmanec"),
    "đurđevac": ("Đurđevac", "Durdevac"),
    "šestanovac": ("Šestanovac", "sestanovac"),
    "šibenik": ("Šibenik", "Sibenik"),
    "šolta": ("Šolta", "Solta"),
    "žirje": ("Žirje", "zirje"),
    "žminj": ("Žminj", "Zminj"),
    "žrnovnica": ("Žrnovnica", "Zrnovnica"),
    "županja": ("Županja", "Zupanja"),
}
