[tool.poetry]
name = "essencia-model"
version = "0.1.0"
description = ""
authors = ["Daniel Arantes"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = {extras = ["email", "dotenv"], version = "^1.10.4"}
deta = {version = "1.1.0a2", extras = ["async"]}
starlette = "^0.24.0"
Jinja2 = "^3.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
