# Generated by Django 4.1.6 on 2023-02-14 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogorama", "0002_comment_active_comment_post_alter_ban_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postflag",
            options={"verbose_name": "PostFlag", "verbose_name_plural": "PostFlags"},
        ),
    ]
