[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "MAOC"
version = "0.0.1"
authors = [
  { name="Stiv Llenga", email="stiv.llenga@h-its.org" },
  { name="Ganna (Anya) Gryn'ova", email="ganna.grynova@h-its.org" }
]
description = "The script required to create the recently proposed MAOC representation "
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

