# Changes here will be overwritten by Copier
_commit: v0.0.6
_src_path: gh:lincc-frameworks/python-project-template
author_email: delucchi@andrew.cmu.edu
author_name: Melissa DeLucchi
module_name: hipscat
project_name: hipscat
