[package]
name = "scandir"
version = "2.3.2"
authors = ["Martin Bammer <mrbm74@gmail.com>"]
description = "A fast directory scanner."
edition = "2021"
license = "MIT"
repository = "https://github.com/brmmm3/scandir-rs"
homepage = "https://github.com/brmmm3/scandir-rs"
readme = "README.md"
keywords = ["fast", "scandir", "walk"]
include = ["Cargo.toml", "src/*"]

[lib]
name = "scandir"
crate-type = ["lib"]

[dependencies]
jwalk = { git = "https://github.com/brmmm3/jwalk", tag = "0.8.1" }
rayon = "1.6"
flume = "0.10"
glob = { git = "https://github.com/brmmm3/glob.git", tag = "0.4.0" }
speedy = { version = "0.8", optional = true }

[dev-dependencies]
tempfile = "3.3"
unix-named-pipe = "0.2"

[features]
speedy = ["dep:speedy"]

[target.'cfg(unix)'.dependencies]
expanduser = "1.2"
