name: Nix linting

on:
  push:
    branches-ignore: gh-pages

jobs:
  check-nix-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-21.05

    - run: ./nix/lint.sh
    - run: ./nix/format.sh --check
