[tool.poetry]
name = "git-timemachine"
version = "0.3.0"
description = "A command-line utility to help you manage Git commits for various time nodes."
authors = ["HE Yaowen <he.yaowen@hotmail.com>"]
license = "GPL-3.0"
readme = "README.md"
packages = [{include = "git_timemachine", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
click = "^8.1.3"

[tool.poetry.scripts]
git-timemachine= "git_timemachine.__main__:cli"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
pylint = "^2.16.1"
chance = "^0.110"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
