[build-system]
requires = ["setuptools","xlrd","openpyxl","xlsxwriter","tabulate","matplotlib","pandas","PyPDF2","build","numpy","xlwt","pip","jupyter","numexpr","openpyxl","bottleneck","xarray","tabulate","ipython","pytz","fsspec","gcsfs" ]
build-backend = "setuptools.build_meta"
[project]
name = "alacorder"
version = "70.5.9.9.9"
authors = [
  { name="Sam Robson", email="sbrobson@crimson.ua.edu" },
]
description = ""
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = ["setuptools","xlrd","openpyxl","xlsxwriter","tabulate","matplotlib","pandas","PyPDF2","build","numpy","xlwt","pip","jupyter","numexpr","openpyxl","bottleneck","xarray","tabulate","ipython","pytz","fsspec","gcsfs" ]
