[tool.poetry]
name = "jommerce"
version = "1.1.0.post"
description = "django ready apps"
license = "MIT"
authors = ["githashem <PersonalHashem@gmail.com>"]
readme = "README.md"
keywords = ["djplus"]
packages = [
    {include = "djplus"},
]

repository = "https://github.com/githashem/djplus"

include = [
    "README.md",
    "LICENSE",
    "CHANGELOG.md",
    "djplus/project_template/*",
]

classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 4.0",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
     "Programming Language :: Python :: 3 :: Only",
]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.0.3"
bcrypt = {version = "^3.2.2", optional = true}
argon2-cffi = {version = "^21.3.0", optional = true}

[tool.poetry.extras]
bcrypt = ["bcrypt"]
argon2 = ["argon2-cffi"]

[tool.poetry.dev-dependencies]
django-debug-toolbar = "^3.2.4"
ipython = "^8.2.0"
Sphinx = "^5.0.1"
sphinx-rtd-theme = "^1.0.0"

[tool.poetry.scripts]
djplus = "djplus.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
