[package]
name = "sha_rs"
version = "1.0.0"
authors = ["Seok Won <ikr@kakao.com>"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sha_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.0", features = ["extension-module"] }
sha3 = "0.10"
hex = "0.4.3"