from api_and_utils import OptionType, BarrierType, KnockType, ContractType, InstrumentType


CONFIG_DICT = {
    ContractType.CONTRACTTYPE_BARRIER: {
        "CUI": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BARRIER,
                 "RULES": {"OPTION_TYPE": OptionType.CALL,
                           "BARRIER_TYPE": BarrierType.UP,
                           "KNOCK_TYPE": KnockType.IN,
                           "TRADE_DIRECTION": 1}}],
        "CUO": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BARRIER,
                 "RULES": {"OPTION_TYPE": OptionType.CALL,
                           "BARRIER_TYPE": BarrierType.UP,
                           "KNOCK_TYPE": KnockType.OUT,
                           "TRADE_DIRECTION": 1}}],
        "CDI": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BARRIER,
                 "RULES": {"OPTION_TYPE": OptionType.CALL,
                           "BARRIER_TYPE": BarrierType.DOWN,
                           "KNOCK_TYPE": KnockType.IN,
                           "TRADE_DIRECTION": 1}}],
        "CDO": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BARRIER,
                 "RULES": {"OPTION_TYPE": OptionType.CALL,
                           "BARRIER_TYPE": BarrierType.DOWN,
                           "KNOCK_TYPE": KnockType.OUT,
                           "TRADE_DIRECTION": 1}}],
        "PUI": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BARRIER,
                 "RULES": {"OPTION_TYPE": OptionType.PUT,
                           "BARRIER_TYPE": BarrierType.UP,
                           "KNOCK_TYPE": KnockType.IN,
                           "TRADE_DIRECTION": 1}}],
        "PUO": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BARRIER,
                 "RULES": {"OPTION_TYPE": OptionType.PUT,
                           "BARRIER_TYPE": BarrierType.UP,
                           "KNOCK_TYPE": KnockType.OUT,
                           "TRADE_DIRECTION": 1}}],
        "PDI": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BARRIER,
                 "RULES": {"OPTION_TYPE": OptionType.PUT,
                           "BARRIER_TYPE": BarrierType.DOWN,
                           "KNOCK_TYPE": KnockType.IN,
                           "TRADE_DIRECTION": 1}}],
        "PDO": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BARRIER,
                 "RULES": {"OPTION_TYPE": OptionType.PUT,
                           "BARRIER_TYPE": BarrierType.DOWN,
                           "KNOCK_TYPE": KnockType.OUT,
                           "TRADE_DIRECTION": 1}}],
    },

    ContractType.CONTRACTTYPE_ASIAN: {
        "CALL": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_ASIAN,
                  "RULES": {"OPTION_TYPE": OptionType.CALL,
                            "TRADE_DIRECTION": 1}}],
        "PUT": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_ASIAN,
                 "RULES": {"OPTION_TYPE": OptionType.PUT,
                           "TRADE_DIRECTION": 1}}],
    },

    ContractType.CONTRACTTYPE_BINARY: {
        "CALL": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BINARY,
                  "RULES": {"OPTION_TYPE": OptionType.CALL,
                            "TRADE_DIRECTION": 1}}],
        "PUT": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BINARY,
                 "RULES": {"OPTION_TYPE": OptionType.PUT,
                           "TRADE_DIRECTION": 1}}],
    },

    ContractType.CONTRACTTYPE_LINEAR_ACC: {
        "ACCUMULATOR": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_VANILLA,
                         "RULES": {"OPTION_TYPE": OptionType.PUT,
                                   "TRADE_DIRECTION": -1,
                                   "STRIKE_PRICE": 'l_bound',
                                   'BARRIER_PRICE': 'N/A',
                                   "LEVERAGE_AFFECTED": True}},
                        {"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_SHARKFIN,
                         "RULES": {"OPTION_TYPE": OptionType.CALL,
                                   "TRADE_DIRECTION": 1,
                                   "STRIKE_PRICE": 'l_bound',
                                   'BARRIER_PRICE': 'u_bound',
                                   "LEVERAGE_AFFECTED": False}}
                        ],
        "DECUMULATOR": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_SHARKFIN,
                         "RULES": {"OPTION_TYPE": OptionType.PUT,
                                   "TRADE_DIRECTION": 1,
                                   "STRIKE_PRICE": 'u_bound',
                                   'BARRIER_PRICE': 'l_bound',
                                   "LEVERAGE_AFFECTED": False}},
                        {"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_VANILLA,
                         "RULES": {"OPTION_TYPE": OptionType.CALL,
                                   "TRADE_DIRECTION": -1,
                                   "STRIKE_PRICE": 'u_bound',
                                   'BARRIER_PRICE': 'N/A',
                                   "LEVERAGE_AFFECTED": True}}
                        ]
    },

    ContractType.CONTRACTTYPE_FIXED_ACC: {
        "ACCUMULATOR": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_VANILLA,
                         "RULES": {"OPTION_TYPE": OptionType.PUT,
                                   "TRADE_DIRECTION": -1,
                                   "LEVERAGE_AFFECTED": True}},
                        {"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BINARY,
                         "RULES": {"OPTION_TYPE": OptionType.CALL,
                                   "TRADE_DIRECTION": 1,
                                   "LEVERAGE_AFFECTED": False}}
                        ],
        "DECUMULATOR": [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_VANILLA,
                         "RULES": {"OPTION_TYPE": OptionType.CALL,
                                   "TRADE_DIRECTION": -1,
                                   "LEVERAGE_AFFECTED": True}},
                        {"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BINARY,
                         "RULES": {"OPTION_TYPE": OptionType.PUT,
                                   "TRADE_DIRECTION": 1,
                                   "LEVERAGE_AFFECTED": False}}
                        ]
    },

    ContractType.CONTRACTTYPE_SNOWBALL: {
        'STANDARD': {"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_SNOWBALL,
                     'RULES': {"OPTION_TYPE": OptionType.CALL}},
        'REVERSE': {"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_SNOWBALL,
                    'RULES': {"OPTION_TYPE": OptionType.PUT}}},

    ContractType.CONTRACTTYPE_AIRBAG: {
        'STARNDARD': [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BARRIER,
                       "RULES": {"OPTION_TYPE": OptionType.CALL,
                                 "BARRIER_TYPE": BarrierType.DOWN,
                                 "KNOCK_TYPE": KnockType.IN,
                                 "TRADE_DIRECTION": 1}},
                      {"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BARRIER,
                       "RULES": {"OPTION_TYPE": OptionType.PUT,
                                 "BARRIER_TYPE": BarrierType.DOWN,
                                 "KNOCK_TYPE": KnockType.IN,
                                 "TRADE_DIRECTION": -1}},
                      {"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BARRIER,
                       "RULES": {"OPTION_TYPE": OptionType.CALL,
                                 "BARRIER_TYPE": BarrierType.DOWN,
                                 "KNOCK_TYPE": KnockType.OUT,
                                 "TRADE_DIRECTION": 'participate_rate'}}],
        'REVERSE': [{"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BARRIER,
                     "RULES": {"OPTION_TYPE": OptionType.CALL,
                               "BARRIER_TYPE": BarrierType.UP,
                               "KNOCK_TYPE": KnockType.IN,
                               "TRADE_DIRECTION": -1}},
                    {"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BARRIER,
                     "RULES": {"OPTION_TYPE": OptionType.PUT,
                               "BARRIER_TYPE": BarrierType.UP,
                               "KNOCK_TYPE": KnockType.IN,
                               "TRADE_DIRECTION": 1}},
                    {"INSTRUMENT_TYPE": InstrumentType.INSTRUMENTTYPE_BARRIER,
                     "RULES": {"OPTION_TYPE": OptionType.CALL,
                               "BARRIER_TYPE": BarrierType.UP,
                               "KNOCK_TYPE": KnockType.OUT,
                               "TRADE_DIRECTION": 'participate_rate'}}],
    }
}
