[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy; platform_system=='Darwin'",
    "oldest-supported-numpy; platform_system!='Darwin'",
]

[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux_2_28"
musllinux-x86_64-image = "musllinux_1_1"
skip = ["*-win32", "*-manylinux_i686", "*musllinux*"]
