
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-10T11:58:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b0339e60299c4dc3b9c9360495c90f6dd1787e1e",
 "version": "1.18.2.post0.dev49"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
