[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "simple_pygame"
version = "0.0.1"
description = "A set of Python modules that provides many features using pygame and other packages."
readme = "README.md"
requires-python = ">= 3.7"
authors = [
    {name = "YoutuberTom"}
]
keywords = ["pygame"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Education",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3"
]
dependencies = [
    "pygame >= 2.1.2",
    "moviepy >= 1.0.3"
]