# Generated by Django 4.1.1 on 2023-02-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnoticias_auth", "0004_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
