
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-14T14:43:42-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "757cec0b3b85844a7953d1276eeda705799df1e1",
 "version": "0.3.0.post0.dev52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
