[tool.poetry]
name = "optipack"
version = "0.0.14-dev"
description = "The optimal package for ML at OM"
authors = ["indigoYoshimaru"]
readme = "README.md"
include = ["optipack/.config/project_structure.yaml"]

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.7.0"
rich = "13.3.1"
pyyaml = "6.0"
Pillow = "9.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
optipack = "optipack.__main__:start"

