[tool.poetry]
name = "basketix"
version = "0.1.28"
description = ""
authors = ["tlartigau <thomaslartigau@hotmail.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
isoweek = "^1.3.3"
pytz = "^2022.6"
python-dateutil = "^2.8.2"
boto3 = "^1.26.22"
typing-extensions = "^4.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
